### ISSUE TITLE
Poor error on sliced neuron->neuron connection

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1000]
If I make a network like this:

``` python
with nengo.Network() as model:
    a = nengo.Ensemble(100, 1)
    b = nengo.Ensemble(100, 1)
    nengo.Connection(a.neurons[:10], b.neurons)
```

I get this exception:

```
nengo.exceptions.ValidationError: Connection.function: function output size is incorrect; should return a vector of size 100
```

The real problem here is that I'm trying to connect something of size 10 (`a.neurons[:10]`) to something of size 100 (`b.neurons`). Nengo doesn't seem to realize that this is a neuron->neuron connection, so the function has nothing to do with things.

**Comment by drasmuss** [comment]
This gives a better error message now ("nengo.exceptions.ValidationError: Connection.transform: Transform output size (10) not equal to connection output size (100)").
