### ISSUE TITLE
Automatic docs and code checking with param system

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1002]
With the very nice param system that is in place, I'm thinking out loud about whether there are ways that we can leverage it to do some other nice things.
1. One thing that comes to mind is we could write a unit test which automatically goes through all of the `__init__` signatures to do certain sanity checks (e.g. `optional = True` iff it is a keyword argument, and `Default` should be the value if one is supplied)?
2. Another idea would be to somehow augment the documentation with this extra information. Sphinx seems pretty extendable, and so one possibility is to introduce some new notation that would act a placeholder to pull in some auto-generated strings. For example, since the `synapse` argument appears in the same way for many different methods in Nengo,
   
   ```
   """
   synapse : float, optional
       Post-synaptic time constant (PSTC) to use for filtering.
   """
   
   synapse = SynapseParam('synapse', default=Lowpass(0.005))
   ```
   
   could be replaced with something like:
   
   ```
   """
   @auto:synapse
   """
   
   synapse = SynapseParam('synapse', default=Lowpass(0.005))
   ```
   
   And then the doc generation would know to reference the `SynapseParam` to determine the underlying type and default, and get some snippet of documentation. This becomes reusable wherever the synapse parameter appears in other parts of the codebase, and keeps everything consistent. It could also create a link to [a common part](https://pythonhosted.org/nengo/user_api.html#synapses) of the documentation.

These ideas have the goal of reducing the burden of synchronizing code and documentation, keeping things consistent within and between methods, as well as reducing the burden of documenting new methods that essentially duplicate preexisting documentation.

**Comment by hunse** [comment]
There's some related discussion in #959.

**Comment by Seanny123** [comment]
Did some quick searching on this and came up with nothing, so I've asked the following question on StackOverflow:  [Verify code and documentation match](http://stackoverflow.com/q/41071661/1079075)

As for de-duplicating documentation, [this is possible](http://stackoverflow.com/a/13766599/1079075), but might be a little bit ugly.

Finally, for checking the param system, we'd probably have to write our own script to:
1. Check the [arguments of the function](http://stackoverflow.com/q/2677185/1079075)
2. Check the associate params (not sure how to do this).

Could be a fun quick hack for when I'm bored.

**Comment by Seanny123** [comment]
I made a quick draft of some code doing the sanity checks that @arvoelke suggested. Where should I put this code? is `nengo/utils/numpydoc.py` a good place to put it?

**Comment by drasmuss** [comment]
This still seems like a good idea, but probably won't be prioritized any time soon (since the docstrings are already written at this point and don't change that often). We have long term plans to separate the param system out into its own package, which might be a good point to revisit this.
