### ISSUE TITLE
Getting rid of magic transforms in SPA

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1007]
I was trying to find an existing issue for this, but apparently there is none? :cry: That's sad because we had already a lot of discussion on this. Anyways, I'm creating this issue now to get the ball rolling.
### Possible ways to match up vocabularies

I think, first of all we need a list of potential ways one might want to match up two different vocabularies.
- "reinterpret": No transformation at all is performed, vectors will just be compared to a different set semantic pointers.
- "transform": Create a projection matrix projection semantic pointers from one vocab into another vocab. There are different variants possible as keys might only exist in one of the vocabularies:
  - Base transform only on the intersection of the sets of keys.
  - Transform semantic pointers missing in the target set to some special vector (might be the null vector).
  - Add new semantic pointers to the target vocabulary for missing keys.
  - Keys only in the target vocabulary, should not pose a problem?
### Syntax

I would propose something similar to function calls (e.g. "reinterpret(output)"). I have to leave right now so I'll flesh that out later.

**Comment by tcstewar** [comment]
Thanks for starting this issue.  :)  The picture in my head has been something like:

```module1 = translate(module2, module1)```

with arguments allowed in there, giving things like:

```module1 = translate(module2, module1, keys=['DOG', 'CAT', 'RAT'])```

I could also see doing

```module1 = module2.translate_to(module1)```

**Comment by tcstewar** [comment]
(note: I used ```translate``` instead of ```transform``` just because we use the word ```transform``` in ```Connection```s, and I wanted to avoid two uses of the term)

**Comment by jgosmann** [comment]
With #1137 merged (with the branch incidentally called `no-magic-transform`), this has been resolved.
