### ISSUE TITLE
Documentation theme?

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1008]
Pinging everyone to give their opinion!

I've been doing a bunch of documentation stuff lately, and as part of that looking at different Sphinx themes. There's nothing wrong with the readthedocs theme, but I think there are better themes out there. I wanted to get consensus on which one to move forward with, as I'll likely customize the theme a bit to make it distinct. We'll use this theme on all Nengo docs for consistency (i.e., use the same theme in Nengo GUI docs, nengo.github.io, etc) so the more votes / opinions the better!

I'm going to add a separate comment for each theme. Use the emoji reaction :+1: to vote for your favorite. Try to only vote for one, but if you're really split you could vote for two. If you really don't like one you can use :-1: to express your distaste.

In general, don't worry about anything that seems a little off, like weird colors in certain places, as whatever theme we choose is likely to need a bit of sprucing up and customizing to a certain color scheme. Just go by overall impression, whether you think the layout / organization of information makes sense, in particular for examples and API documentation pages. I'll put a link to an example of the important pages in each post.

**Comment by tbekolay** [comment]
## Alabaster theme

![alabaster](https://cloud.githubusercontent.com/assets/203709/14319309/b38f51ae-fbde-11e5-903e-8fd17df132c8.png)

* [Index page](http://www.bekolay.org/nengodocs-alabaster/)
* [Page with mostly text, some code](http://www.bekolay.org/nengodocs-alabaster/getting_started.html)
* [Example with some math](http://www.bekolay.org/nengodocs-alabaster/examples/controlled_oscillator.html)
* [Example with lots of plots](http://www.bekolay.org/nengodocs-alabaster/examples/nef_summary.html)
* [API documentation](http://www.bekolay.org/nengodocs-alabaster/user_api.html#network)

**Comment by tbekolay** [comment]
## Better theme

![better](https://cloud.githubusercontent.com/assets/203709/14319373/f1f8ddca-fbde-11e5-9405-72a6f5a7aa4d.png)

* [Index page](http://www.bekolay.org/nengodocs-better/)
* [Page with mostly text, some code](http://www.bekolay.org/nengodocs-better/getting_started.html)
* [Example with some math](http://www.bekolay.org/nengodocs-better/examples/controlled_oscillator.html)
* [Example with lots of plots](http://www.bekolay.org/nengodocs-better/examples/nef_summary.html)
* [API documentation](http://www.bekolay.org/nengodocs-better/user_api.html#network)

**Comment by tbekolay** [comment]
## Guzzle theme

![guzzle](https://cloud.githubusercontent.com/assets/203709/14319398/0b8c9bf0-fbdf-11e5-9ec2-9a8b3e9665fb.png)

* [Index page](http://www.bekolay.org/nengodocs-guzzle/)
* [Page with mostly text, some code](http://www.bekolay.org/nengodocs-guzzle/getting_started.html)
* [Example with some math](http://www.bekolay.org/nengodocs-guzzle/examples/controlled_oscillator.html)
* [Example with lots of plots](http://www.bekolay.org/nengodocs-guzzle/examples/nef_summary.html)
* [API documentation](http://www.bekolay.org/nengodocs-guzzle/user_api.html#network)

**Comment by tbekolay** [comment]
## Readable theme

![readable](https://cloud.githubusercontent.com/assets/203709/14319423/24121268-fbdf-11e5-8f37-c342afcd0c93.png)

* [Index page](http://www.bekolay.org/nengodocs-readable/)
* [Page with mostly text, some code](http://www.bekolay.org/nengodocs-readable/getting_started.html)
* [Example with some math](http://www.bekolay.org/nengodocs-readable/examples/controlled_oscillator.html)
* [Example with lots of plots](http://www.bekolay.org/nengodocs-readable/examples/nef_summary.html)
* [API documentation](http://www.bekolay.org/nengodocs-readable/user_api.html#network)

**Comment by tbekolay** [comment]
## ReadTheDocs theme

![rtd](https://cloud.githubusercontent.com/assets/203709/14319450/3b357c32-fbdf-11e5-8bdd-0cd57e396ccd.png)

* [Index page](http://www.bekolay.org/nengodocs-rtd/)
* [Page with mostly text, some code](http://www.bekolay.org/nengodocs-rtd/getting_started.html)
* [Example with some math](http://www.bekolay.org/nengodocs-rtd/examples/controlled_oscillator.html)
* [Example with lots of plots](http://www.bekolay.org/nengodocs-rtd/examples/nef_summary.html)
* [API documentation](http://www.bekolay.org/nengodocs-rtd/user_api.html#network)

**Comment by tbekolay** [comment]
That's all of them for now. If anyone sees any other themes online and they want to see how the Nengo docs look in that theme, let me know and I'll add more comments to vote on!

**Comment by hunse** [comment]
ReadTheDocs and Guzzle both look quite visually appealing to me. The reason I voted for ReadTheDocs is that it has a few things I like a bit better, including the version number in the sidebar (I hate looking at docs and not knowing what version they're for), clearer inline source code (with the little box), pluses to expand headings in the sidebar, and a nicer title/subtitle font.

If people have other things that really stood out to them about particular themes, please point them out. I think it's nice to have a bit of discussion, too, to really identify what we're looking for.

**Comment by tbekolay** [comment]
The version number, inline source formatting, and title/subtitle font are definitely in the realm of little things that we can add to the Guzzle theme. Expanding the headings in the sidebar might be a bit more work, but probably doable.

But yes, agreed, feel free to comment on pros and cons if they stand out to you :)

**Comment by jgosmann** [comment]
The math in Guzzle has weird colors ... :rainbow:

**Comment by jgosmann** [comment]
Also the notebook input boxes exceed the page margin which looks somewhat weird.

**Comment by hunse** [comment]
Also, do we have to do this for 2.1.0? I'd really like to get it released, because then I can get `nengo_ocl` released and pull everything into master, which right now is confusing people because not everyone who wants to use `nengo_ocl` knows that right now you have to use the `v2.1dev` branch with current `nengo` master. Anyway, it just doesn't seem to me that ReadTheDocs is that terrible that we have to worry about this right now.

> The math in Guzzle has weird colors ... :rainbow: 

I just noticed that as well.

**Comment by tbekolay** [comment]
The notebook input widths and math colors in Guzzle can also be fixed; I suspect Guzzle and Mathjax share some CSS class name.

> do we have to do this for 2.1.0?

Not necessarily, but I have to regenerate the docs for 2.1.0 anyhow and switching the theme takes little effort if the decision's been made. Building the notebooks has been the main bottleneck (as you might notice from some oddities in the Examples page right now).

**Comment by hunse** [comment]
> Not necessarily, but I have to regenerate the docs for 2.1.0 anyhow and switching the theme takes little effort if the decision's been made

I just don't want to rush the decision, and if we're talking about making customizations to a theme that might take a bit more time too.

**Comment by tbekolay** [comment]
True true; additionally, there will have to be some discussion about other assets (logo, color scheme, etc) also, so I'll for sure take this out of the 2.1.0 milestone.

**Comment by celiasmith** [comment]
I've not voted yet because i think that guzzle (and readable) are much more visually appealing than readthedocs, but the latter definitely has a better left side menu. I must admit i prefer serif fonts, admittedly an aesthetic thing (http://alexpoole.info/blog/which-are-more-legible-serif-or-sans-serif-typefaces/).

**Comment by hunse** [comment]
I'd like to go through each aspect of the whole thing, and pick stuff that we think is best for each, because I don't feel like any of these themes have all the things I want. For example, I'd like the syntax highlighting to be ideally the same as Jupyter, and that can be independent of the color theme.

This seems like a good discussion topic for a dev meeting, especially if it's not too hard to mix and match things so that we can try stuff out in real time. I think the layout will be the hardest thing to change, so if we like the ReadTheDocs layout best, it might be best to start with that and then change the colours, styles, and fonts as we desire.

**Comment by jgosmann** [comment]
#1338 switches to guzzle, I suppose this issue can be closed?

**Comment by tbekolay** [comment]
Yep. Also, in this thread someone mentioned Guzzle having weird math colours; I've [fixed that](https://github.com/nengo/nengo/blob/482eec45b92545336d272420ed91ffafdd0937d8/docs/_static/custom.css#L1) (the issue was that both Guzzle and MathJax used the same CSS class for some elements).
