### ISSUE TITLE
Nengo parameters let you set silly names

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1020]
As @drasmuss and I found out, the following code using the old parameter syntax throws no error:
```
net.config[nengo.Connection].set_param(
    "insert_weights", nengo.params.BoolParam(False))
```

Under the new parameter syntax, the correct code would be:
```
net.config[nengo.Connection].set_param(
    "insert_weights", nengo.params.BoolParam("test", default=False))
```

Can we check the `type` of `name` [on initialisation](https://github.com/nengo/nengo/blob/master/nengo/params.py#L48) so that it throws an error for anything that isn't a string?

**Comment by tcstewar** [comment]
> Can we check the type of name on initialisation so that it throws an error for anything that isn't a string?

That seems like a good idea -- this exact same problem caused issues with nengo_spinnaker and nengo_gui
