### ISSUE TITLE
SPA default synapse

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1030]
The default synaptic time constant for connections created by SPA actions is 0.01 (this time constant is used into and from channels for example). This is different from the default synapse of manually created connections (0.005) and might be surprising.

I would propose to set the to the same value (that would also allow to simplify some code a little bit). Probably 0.005 as that won't influence every model, but only SPA models.

**Comment by tcstewar** [comment]
Hmm...  my intent there was that SPA stuff is starting to make biological claims, and so should choose biologically reasonable values.  However, I'm not sure exactly where that 0.01 came from -- I believe it came from somewhere but now I can't see where.

**Comment by jgosmann** [comment]
Made the change as discussed in the dev meeting to see if it breaks anything.

**Comment by jgosmann** [comment]
bump
Any new comments on this, given #1038?
