### ISSUE TITLE
Remove Copy operator

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1034]
As it turns out, we only use the `Copy` operator in one place, whereas we use `SlicedCopy` twice. Since `SlicedCopy` can do normal copies as well, perhaps we should remove `Copy` and rename `SlicedCopy` -> `Copy`?

**Comment by jgosmann** [comment]
With respect to #1035 I'm against it because the multiple `Copy` operators can be merged into one, but with `SlicedCopy` this is not as easy because of the slicing.

**Comment by jgosmann** [comment]
I took another look at the `SlicedCopy` code and figured that merging of `SlicedCopy`s is not as complicated as I thought. There are basically three cases:

1. Real slices: These are handled by slicing the signal. This case is already handled in the optimizer code.
2. No slicing/Ellipsis: This is basically a `Copy`, so no problem here too.
3. Slicing with list of indices: Can be handled by joining the lists together (and adjusting the indices accordingly).

So I suppose I'm also in favor of this now ... (though it might be good to test an actual implementation of merging `SlicedCopy`s first to make sure I didn't overlook anything).

**Comment by jgosmann** [comment]
I changed my mind again. The optimizer will be (potentially a lot) faster with two separate classes. If there are *n* `SlicedCopy` and *m* `Copy` it has a complexity of O(*n*² + *m*²) versus a complexity of O((*n* + *m*)²) = O(*n*² + *m*² + 2*nm*). The optimizer will also probably never be able to merge a sliced copy with a non-sliced copy.

**Comment by hunse** [comment]
I don't see how it makes any difference. It seems like just names to me. If we merge things, you can always go through the operators and treat any copy with `src_slice` or `dst_slice` set differently, can't you? All the information you need is still there.

**Comment by jgosmann** [comment]
The code checks (in the worst case¹) for every combination of *a* and *b* where *a* and *b* are from a set of operators whether they can be merged. If `SlicedCopy` and `Copy` get unified, both are in one set. Of course I could go through that set and separate it again in linear time, but it
* complicates the optimizer code which is already quite complex
* adds special case code for just this operator type to the optimizer

¹: I figured that I can sort the operators by the order of the memory access first which allows me to cut the loop short in many cases. So the average runtime is probably much better, but that is something to be tested on some real models.

**Comment by jgosmann** [comment]
The most recent version of the optimizer is doing grouping by the bases of views and thus my concerns might not apply anymore, but this should be tested.
