### ISSUE TITLE
Cannot use node after changing size_in

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1039]
Consider a network where a passthrough node's size is changed after it is initialized:

```
with nengo.Network() as model:
    x = nengo.Node(size_in=1)
    x.size_in = 2
    p = nengo.Probe(x)

nengo.Simulator(model)
```

This gives the error:

```
BuildError: Incompatible shapes in ElementwiseInc: Trying to do (1, 1L) += (1, 1) * (1, 2L)
```

Commenting either `x.size_in = 2` or `p = nengo.Probe(x)` will prevent the error.

To solve the issue, the user also has to add the line:

```
x.size_out = 2
```

This is because the default `size_out` inherits the value of `size_in`, but only during initialization. I am going to argue that this is a headache for the average user to debug. I think the `size_out` should automatically adjust itself as well? Or we shouldn't let users tweak them independently without validation (could give a friendlier error).

**Comment by jgosmann** [comment]
Not sure what the use case is here, but depending on the node function `size_in` might differ from `size_out`. Changing `size_out` with `size_in` would be some magic that could equally well be hard to debug.

To me it it seems the right thing to do, would be to raise an exception at build time because the node function produces an output size that does not match the value of `size_out`.

**Comment by arvoelke** [comment]
The idea with the magic is it would only be used when the `size_out` was already being set automatically in the first place (as in the above snippet), but of course not if a function has been supplied.

If this is too nuanced I'd be happy with a better error.

The use case was that I have this wrapper around Nengo that possibly changes dimensionality each time a method is called (since a target function is supplied after model creation, but before build time). This method should be idempotent. The alternative would be to create a new node and throw the old one away, but not sure if that is possible.

**Comment by tcstewar** [comment]
I think I'd lean towards doing a better error message and forcing people to set both the ```size_in``` and ```size_out``` attributes.  It just feels like too much magic to me to have something automatically happen both when someone sets ```size_in``` on a passthrough Node and when they set ```size_out```....  (or only for one of those but then I have to remember which one).

**Comment by hunse** [comment]
We have some attributes that are read only after initialization (e.g. pre
and post on Connection), and I think this could be one of those cases.

**Comment by tcstewar** [comment]
> We have some attributes that are read only after initialization (e.g. pre
> and post on Connection), and I think this could be one of those cases.

Hmm...  I've had a few situations where it was useful to be able to modify this on a passthrough Node.  if you can't change this, then you have to delete the Node and build a new one.  I'd prefer to allow attributes to be changed unless there's a technical reason why they can't be.

**Comment by arvoelke** [comment]
> It just feels like too much magic to me to have something automatically happen both when someone sets size_in on a passthrough Node and when they set size_out.... 

The idea is that it should be no more magical than the automatic setting that's already happening when the node is initialized. The user doesn't specify `size_out`, but it gets set for the user anyway. To me it seems less intuitive that I never set `size_out` in the first place, but now I have to readjust it because it was automatically set in one context but not within another. It's almost as though `size_out` were an automatic property to begin with (I believe in the vast majority of cases it's not actually set by the user). If one of the parameters wasn't set automatically to begin with, then of course we shouldn't change it automatically later on. The proposed change in my last post would make this more consistent.

We also already do this sort of magic in `Connection` to update `size_out` whenever the `transform` is changed.

**Comment by hunse** [comment]
> Hmm... I've had a few situations where it was useful to be able to modify this on a passthrough Node.

Okay. I was assuming that there wouldn't really be any situations where that would be necessary.

> I'd prefer to allow attributes to be changed unless there's a technical reason why they can't be.

The main reason why they can't be is that it makes validation way easier. If you've made a node that has a particular size_in and connected something into it, and you then go and change that size_in, we should really be validating that connection again to make sure things match up. And it would be easy to get into situations where you want to change some attributes, but can't, because they both have to change simultaneously to satisfy the validator. For example, if you wanted to change the size_in of a node, but also had to change the transform of an incoming connection to accommodate that. (We already have some things like this in the code, for example functions and transforms in connections, so I'm not saying we should avoid conflicting constraints like this, only that when there are constraints like this it makes the ability to change something like size_in after initialization less useful.)

**Comment by tcstewar** [comment]
> The idea is that it should be no more magical than the automatic setting that's already happening when the node is initialized.

Hmm... that is a good point.  Yup, I could see the consistency in that -- you should only be expected to change the setting that you would have had to set on the constructor.

**Comment by tcstewar** [comment]
> The main reason why they can't be is that it makes validation way easier. If you've made a node that has a particular size_in and connected something into it, and you then go and change that size_in, we should really be validating that connection again to make sure things match up.

Also a good point.  Basically this comes down to the question of whether we want to use the validation to make sure that the Network is *always* in a valid buildable state.  Right now, we

**Comment by jgosmann** [comment]
A note, if we decide for the automatic updating: The #984 PR introduces the possibility to define the parameter initialization order which might be useful in the implementation of that (e.g. to figure out which other parameters might need updating).

**Comment by tbekolay** [comment]
The decision at the dev meeting today was that we definitely want to keep the ability to change things like `n_neurons`, `dimensions`, `size_in` etc, but we should give better error messages through a validation step in the builder.

Just adding a validation step is not an easy task though, so instead I'll do this as part of #1189, which is already a big job. By virtue of writing #1189 in this comment, this issue now shows up as being referenced in #1189, so I'm going to close this now as I'll be going through all of the issues referencing #1189 when working on that PR.

PS: #1189 #1189 #1189
