### ISSUE TITLE
Should allow solvers on ensemble array default outputs

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo#1040]
It would be nice to be able to pass a solver to an ensemble array, so when it creates the default output, you can control how it solves.  The solver is passed in through add_output in general.  When it's called automatically it just uses the default:
`self.add_output('output', function=None)`

**Comment by tcstewar** [comment]
Hmm, this feels like something the config system could handle, rather than adding an argument to the constructor.  Something like this seems to work:

```python
    cfg = nengo.Config(nengo.Connection)
    cfg[nengo.Connection].solver=nengo.solvers.NnlsL2()
    with cfg:
        a = nengo.networks.EnsembleArray(n_neurons=100, n_ensembles=3)
```

**Comment by hunse** [comment]
Yeah, I'd really rather not have a constructor argument, because I think it would look like that argument should be applied to *all* outputs, even when using `add_output` later.

The other option is to store the connections in some intelligent way, so that users can modify the solver post-creation. Unfortunately, we make multiple connections per output, so this isn't as clean as I might like it to be:

```python
a = nengo.networks.EnsembleArray(n_neurons=100, n_ensembles=3)
for conn in a.get_output_connections('output'):
    conn.solver = nengo.solvers.NnlsL2()
```

As a side note, it would be great to be able to make a quick config as a one-liner:

```python 
with nengo.Config(nengo.Connection).set('solver', nengo.solvers.NnlsL2()):
    a = nengo.networks.EnsembleArray(n_neurons=100, n_ensembles=3)
```

**Comment by tcstewar** [comment]
> As a side note, it would be great to be able to make a quick config as a one-liner:

Ooo, good idea.  Although I think I'd prefer the syntax:

```python
with nengo.Config(nengo.Connection, solver=nengo.solvers.NnLsL2()):
    ...
```

**Comment by jgosmann** [comment]
I also think that we should not a constructor argument. Besides the workaround with the config system, one could use `add_output` to add another output with the desired solver (though this will solve for decoders twice with different solvers which might be a performance issue in some cases).

I'd vote to close this issue if there are no strong arguments for adding such a constructor argument.

**Comment by tbekolay** [comment]
I agree with Jan, and no one's been too bothered by this in over a year, so closing.

**Comment by arvoelke** [comment]
I've taken the extra `add_output` approach in my code. @jgosmann does your new build optimizer prune away any parts of the graph that don't eventually connect to some probe or side-effect-node? Just wondering if there are extra connections / nodes in the final model that are dangling.

**Comment by jgosmann** [comment]
> @jgosmann does your new build optimizer prune away any parts of the graph that don't eventually connect to some probe or side-effect-node?

No, it is not. If we were to do it, it's probably best to do it before the build to avoid computing unused decoders.
