### ISSUE TITLE
Cache throws 'open' not defined error in Python 3

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#1041]
After running a model in python3, the cache system throws the following error when closing down the simulation (after the model has successfully ran):

```
Simulation finished in 0:01:32.                                                 
Exception ignored in: <bound method CacheIndex.__del__ of <nengo.cache.CacheIndex object at 0x7f57521f8588>>
Traceback (most recent call last):
  File "/home/abruser/git/nengo/nengo/cache.py", line 110, in __del__
  File "/home/abruser/git/nengo/nengo/cache.py", line 126, in sync
  File "/home/abruser/git/nengo/nengo/cache.py", line 115, in _load_index
NameError: name 'open' is not defined
```

**Comment by tbekolay** [comment]
Found [this relevant StackOverflow question](http://stackoverflow.com/questions/23422188/why-am-i-getting-nameerror-global-name-open-is-not-defined-in-del)...

**Comment by jgosmann** [comment]
@xchoo Can you test if PR #1053 solves the problem?

**Comment by jgosmann** [comment]
@xchoo Did PR #1053 (now merged into master) solve the problem and can this issue be closed?

**Comment by jgosmann** [comment]
@xchoo It's been 8 days. Can I close the issue?

**Comment by xchoo** [comment]
Uh yup. I'll open it again if another issue arises with Python3 (I don't use it very often). :smile:
