### ISSUE TITLE
Cache does not consider solver regularization

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1044]
```
import nengo

nengo.cache.get_default_decoder_cache().invalidate()

with nengo.Network() as model_foo:
    x = nengo.networks.EnsembleArray(100, 1, seed=0)
    x.add_output('foo', function=None, solver=nengo.solvers.LstsqL2(reg=0.001))
    p_foo = nengo.Probe(x.foo, synapse=0.01)
    
with nengo.Simulator(model_foo) as sim_foo:
    sim_foo.run(1.0)

# nengo.cache.get_default_decoder_cache().invalidate()
    
with nengo.Network() as model_bar:
    x = nengo.networks.EnsembleArray(100, 1, seed=0)
    x.add_output('bar', function=None, solver=nengo.solvers.LstsqL2(reg=1000))
    p_bar = nengo.Probe(x.bar, synapse=0.01)
    
with nengo.Simulator(model_bar) as sim_bar:
    sim_bar.run(1.0)

print nengo.utils.numpy.rms(sim_foo.data[p_foo])
print nengo.utils.numpy.rms(sim_bar.data[p_bar])
```

Running this gives the output:
```
0.0329802255974
0.0329802255974
```

But if I uncomment the line in between to invalidate the cache:
```
0.0329802255974
3.57156978133e-07
```

The latter result is the correct one (since `bar` is supposed to be heavily regularized). This means that the cache is not key'ing on the solver's regularization.

**Comment by arvoelke** [comment]
(@celiasmith discovered this bug)

**Comment by jgosmann** [comment]
This was probably broken by a53203c612c6ab68286ae6318bdc4c065bb268e7 which stores the regularization as a parameter instead of an instance attribute. The cache requires the objects the key is based on to be pickleable which is not given for parameters.

There's a good chance that this problem is fixed by PR #984 which is marked for the 2.1.1 release Though, to me it seems like a new feature than just a bugfix. But I don't think there would be any other easy bugfix?

**Comment by jgosmann** [comment]
* [ ] Oh, and I should add a test to check that the solver parameters are respected by the cache.

**Comment by hunse** [comment]
I'm working on making Solvers FrozenObjects, since they really ought to be. Then you can pickle them and this should be easy.

**Comment by jgosmann** [comment]
#984 isn't that complicated either (at least compared to the other stuff I was doing lately). But that should go well along with solvers being frozen. I guess, we just have to decide with which option we want to go first and how the timeline for a 2.1.1 release should be.

**Comment by jgosmann** [comment]
#1046 fixes it for me, #1047 adds the test.
#984 needs a rebase and produces a bunch of merge conflicts where I don't have the patience right now to resolve them.

**Comment by jgosmann** [comment]
Rebased #984 and it also fixes this problem.

**Comment by arvoelke** [comment]
I'm trying to think of a way to solve this problem in a way that is compatible with 2.1.0, without just invalidating the cache or preventing the user from setting a seed on my EnsembleArray, or from passing me an arbitrary solver. Is there a way I can force a cache miss on only one connection in particular?

**Comment by arvoelke** [comment]
Figured out a nice hack:

```
import logging
import sys

root = logging.getLogger()
root.setLevel(logging.DEBUG)

import nengo
import numpy as np

for _ in range(2):
    solver = nengo.solvers.LstsqL2(reg=np.random.random())
    solver._hack = np.random.random()
    with nengo.Network() as model:
        a = nengo.Ensemble(10, 1, seed=0)
        nengo.Connection(a, a, solver=solver, seed=0)
    nengo.Simulator(model)
```

The line `solver._hack = np.random.random()` will force a cache miss by giving the solver a different finger-print each time. Note that even though the regularization is different each time, the extra line is still needed because it currently doesn't pay attention to the special attribute. Let me know if you think of anything better, but in the mean time this trick works for me!

**Comment by arvoelke** [comment]
Also @jgosmann haven't looked too closesly at `test_cache.py`, but something to consider with `SolverMock`: when you change `n_calls` that will change the fingerprint of the solver. Consequently I think any cache miss will _always_ result in the _next_ call being a miss whenever you use the same mock object (because the solver now looks different). But the converse is not necessarily true (a cache hit does not change the result of the next call). Has this been considered?
