### ISSUE TITLE
TypeError when adding vocab to spa model

### ISSUE THREAD

**Issue by boomsbloom** [nengo/nengo#1049]
dimensions = 16
       rng = np.random.RandomState(0)
       vocab = spa.Vocabulary(dimensions=dimensions, rng=rng)
       model = spa.SPA(vocabs=vocab)

returns:

       Traceback (most recent call last):
         line 39, in <module>
           model = spa.SPA(vocabs=vocab)
         File "/Library/Python/2.7/site-packages/nengo/spa/spa.py", line 89, in __init__
           for vo in vocabs:
         File "/Library/Python/2.7/site-packages/nengo/spa/vocab.py", line 137, in __getitem__
           if not key[0].isupper():
       TypeError: 'int' object has no attribute '__getitem__'

I was able to crudely workaround this by modifying spa.py's init

    def __init__(self, dimensions, label=None, seed=None, add_to_container=None,
                 vocabs=None):
        super(SPA, self).__init__(label, seed, add_to_container)
        vocabs = [] if vocabs is None else vocabs
        enable_spa_params(self)
        self._modules = {}
        self._default_vocabs = {}

        # for vo in vocabs:
        #     if vo.dimensions in self._default_vocabs:
        #         warnings.warn("Duplicate vocabularies with dimension %d. "
        #                       "Using the last entry in the vocab list with "
        #                       "that dimensionality." % (vo.dimensions))
        #     self._default_vocabs[vo.dimensions] = vo

        self._default_vocabs[dimensions] = vocabs

and calling it as `model = spa.SPA(dimensions, vocabs=vocab)` but I should be able to add my own vocabulary to the spa model the initial way, right?

**Comment by jgosmann** [comment]
I think `vocabs` expects as list. Try `model = spa.SPA(vocabs=[vocab])`.

**Comment by boomsbloom** [comment]
You're right - thanks!
