### ISSUE TITLE
When creating spa thalamus network, put bias and gate ensembles into separate subnetwork.

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#1051]
Currently, when you create a spa thalamus network using the spa action system, the bias node, gate ensembles, and channels get put into the destination module's root network. This clutters things up in the UI. I think it'd be better to create a subnetwork for all that stuff to go into.

**Comment by jgosmann** [comment]
Check out #1014, it's doing exactly that. =)

**Comment by xchoo** [comment]
Unless I am reading the code wrong, it looks like it is still placing things in the `parent_module` (default case when no net is specified)?

**Comment by jgosmann** [comment]
If I recall correctly what I did, it creates a subnetwork for each rule to group stuff by.

**Comment by xchoo** [comment]
Ohhh. Maybe? But I was requesting that one big subnetwork be created for all of the stuff the thalamus code adds to the modules. i.e. if there are 10 bg rules targeting a module, there'd be 1 subnetwork (with 10 subsubnetworks inside it) instead of 10 subnetworks in the module.

**Comment by jgosmann** [comment]
I see, that should be fairly easy to do with the changes in #1014, but I wasn't sure how useful that actually is. To me it seemed more useful in some cases to be able to drag the individual modules to where the input comes from. I suppose there is no right or wrong answer here and depending on the model different things might work better. Not sure what structure would be the most useful in the majority of cases.

**Comment by jgosmann** [comment]
@tcstewar and I are both happy with how things are currently grouped in the new-spa branch and we will leave at that for now. We can discuss alternate groupings at a later point again.
