### ISSUE TITLE
Place for common configs

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1058]
I repeatedly run across situations where I want to create thresholding ensembles and it would be nice to sort of have a network for that. But it is not really a network, but only a set of config options set on the ensemble. So I was wondering if we should have a place for functions that create such configs?

Not sure if there are other common sets of configuration options that get used?

In the thresholding case it would look somewhat like this:
```python
def ThresholdingConfig(threshold):
    config = nengo.Config(nengo.Ensemble)
    config[nengo.Ensemble].dimensions = 1
    config[nengo.Ensemble].intercepts = nengo.dists.Exponential(0.15, threshold, 1.)
    config[nengo.Ensemble].encoders = nengo.dists.Choice([[1]])
    config[nengo.Ensemble].eval_points = nengo.dists.Uniform(threshold, 1.)
    return config
```
and be used like this
```python
with ThresholdingConfig(0.3):
    threshold = nengo.Ensemble(50)  # might be better to give dimensions explicitely?
```

**Comment by tbekolay** [comment]
This is a great idea! Never occurred to me, but I can already think of a bunch of places that this would be super useful. It's a nice level of abstraction above the regular objects, but below networks... Could make our network construction code more concise / consistent. Exciting!

**Comment by tbekolay** [comment]
From the meeting: let's steal Handbrake's terminology and call these "presets".

**Comment by jgosmann** [comment]
Any other presets than thresholding that people have and want to see included?

**Comment by tbekolay** [comment]
Presets for different receptor types could be useful; `networks.BasalGanglia` makes configs for AMPA and GABA receptors.

**Comment by Seanny123** [comment]
@xchoo has a wide variety of configs that he uses for Spaun, including one for a ramp network if I remember correctly, but I think those more esoteric configs can wait until later.

Is the next step for this issue to make a pull request? And by pull request, I mean one containing:
- [ ] Threshold config
- [ ] Documentation indicating that these configs are available

**Comment by jgosmann** [comment]
Yes, I will add my thresholding config (I think the example above needed some minor changes, I have a working version lying around).

**Comment by jgosmann** [comment]
Added a PR for this.

**Comment by tbekolay** [comment]
#1077 was merged, so this has been done!
