### ISSUE TITLE
Division Problem - Help appreciated

### ISSUE THREAD

**Issue by Philipp114** [nengo/nengo#1059]
Hello 

I am pretty new in using nengo and i am looking for a place to ask some questions regarding calculations. (i am trying to program a little calculator using LIF-neurons).
I realise that this is probably not the appropriate spot, so a link to a better help/discussion forum would already be a good step.

One major issue is the division and how to choose the correct values to make it feasible.
Here is a very simple example:

```
model = nengo.Network()
with model:

#simple varying function between 1 and 11 to avoid pole problems
input_1 = nengo.Node(lambda t:5* np.sin(t)+6)  

#first Ensemble just to pass the value
a = nengo.Ensemble(600, dimensions=1, neuron_type=nengo.neurons.LIFRate(tau_rc=0.01, tau_ref=0.002),radius=11)

#second Ensemble to show results
b = nengo.Ensemble(600, dimensions=1, neuron_type=nengo.neurons.LIFRate(tau_rc=0.01, tau_ref=0.002),radius=1, seed=124)

#seed No. 124 shows an extreme result which is of course not wanted 


#simple Division
def div(x):
    return 1/x[0]

nengo.Connection(input_1, a)

nengo.Connection(a, b,function=div)
```

My main problem is to get consistent results when using a function like 1/x. (I realise the pole at 0 gives numerical problems, but I would only need it to work for certain foreseeable ranges).
How do i manage to choose the eval_points and intercepts for a problem like this?

Any help would be greatly appreciated.

**Comment by Seanny123** [comment]
Hello! This forum is fine for questions.

@jgosmann tells me that the NEF is really bad at division because of non-linearities, which I see you've tried to remedy by choosing a different function. However, the inverse of the function you're inputting is still highly non-linear.

@xchoo tried to tackle this probelm as well, if I recall correctly. I think what he ended up doing was putting everything into the log-domain and then using subtraction as division.

That's all I know, but hopefully the people I pinged will be able to help you further!

**Comment by xchoo** [comment]
Actually, I did it by rescaling and biasing the denominator (and then taking that into account when computing the division). 

@tcstewar was the one who did it by transforming the inputs into the log domain, doing the subtraction, and then taking the exponent of the result to get the appropriate answer.

**Comment by xchoo** [comment]
In general, the problem with division is very hard to do in neurons for any general range of numbers. The problem becomes sightly easier to handle (with any of the methods mentioned above) if the input and output ranges are restricted to specific ranges. (e.g. the denominator can only be between 0.5 and 1)

**Comment by tcstewar** [comment]
> How do i manage to choose the eval_points and intercepts for a problem like this?
> 
> Any help would be greatly appreciated.

I generally find that it's sufficient just to choose the ```eval_points```.  And I normally do it by just determining what distribution of inputs I'll be feeding into the system when it's running.  So in your case, I'd just use the sine wave between 1 and 11:

```python
    pts = 5*np.sin(np.linspace(0, 2*np.pi, 1000))+6
    pts.shape = 1000,1

    nengo.Connection(a, b, function=div, eval_points=pts/a.radius)
```

One rather non-intuitive aspect of this is that the ```eval_points``` automatically get scaled by the radius, so you have to divide by the radius in this case.  Alternatively, you can do

```python
    pts = 5*np.sin(np.linspace(0, 2*np.pi, 1000))+6
    pts.shape = 1000,1

    nengo.Connection(a, b, function=div, eval_points=pts, scale_eval_points=False)
```

The documentation for the Connection object can be found here: https://pythonhosted.org/nengo/frontend_api.html#nengo.Connection

and you can also get it inside the Nengo GUI by just doing ```help(nengo.Connection)```

Let us know if that works!

**Comment by xchoo** [comment]
If you want to see my approach, there's a notebook here you can look at: [link](https://www.dropbox.com/s/dudxs1mypkd563d/TestNormalization.ipynb?dl=0)

Look for cell `In [88]`. Note that this uses the old Product network (with the 2D ensemble). 
You can find that [here](https://github.com/xchoo/spaun2.0/blob/master/_spaun/_networks/product_2D_ens.py)

**Comment by Philipp114** [comment]
First of all i want to thank you all for the fast responses, they already helped me a lot in understanding the program.

I tested your idea with the eval points and for this range it did give much better results. Thanks :)

While trying it out a little more i can now see where some of my original problems lie.
Since the value range is very limited as xchoo already stated, i am going to take a look at your approach next and will let you know if i need any help understanding it.

With the logarithmic approach i had similar problems, so i will have to do some more testing there as well.

Another little idea of mine was to compute a maximum of some values, i did look at some algorithms for it but maybe someone here has already seen if this would even be possible using neurons.

**Comment by Seanny123** [comment]
Hey @Philipp114 did you end up resolving your problem? If yes, would you mind closing this issue? If not, would you like to continue the discussion at forum.nengo.ai

**Comment by Seanny123** [comment]
Closing to keep the issue tracker tidy. If you still have this issue or related issues please post on the forums. (:
