### ISSUE TITLE
spa Semantic Pointer Values Saturating High

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo#1081]
Using spa, semantic pointer similarity value is saturating high at 2.5-3; expecting 1-1.5. Used this code as a script and on the GUI. Same result on both so should be unrelated to GUI.

on `server-refactor` branch for GUI and `master` for nengo

```
import nengo
import nengo.spa as spa
import matplotlib.pyplot as plt
D = 32

vocab = spa.Vocabulary(D)

words = ['ORANGE', 'APRICOT', 'CHERRY', 'STRAWBERRY', 'APPLE']

for word in words:
    vocab.parse(word)

model = spa.SPA()
with model:
    
    model.a = spa.State(D, neurons_per_dimension = 100, vocab = vocab)
    model.b = spa.State(D, neurons_per_dimension = 100, vocab = vocab)
    
    nengo.Connection(model.a.input, model.b.output)
    nengo.Connection(model.b.output, model.b.input, synapse = 0.1)
    model.input = spa.Input(a = words[0])
    
    out = nengo.Probe(model.b.output)

#Comment out below for GUI
with nengo.Simulator(model) as sim:
    sim.run(2)

plt.figure()
plt.plot(sim.trange(), nengo.spa.similarity(sim.data[out], vocab))
plt.legend(vocab.keys, loc='best')
plt.xlabel("t [s]")
```

![gui_high_saturation](https://cloud.githubusercontent.com/assets/18405463/15902252/00e34998-2d75-11e6-8d51-f4112d2bb23a.PNG)

![script_high_saturation](https://cloud.githubusercontent.com/assets/18405463/15902250/fd01ce62-2d74-11e6-9129-8becde0c197e.png)

**Comment by arvoelke** [comment]
Change `nengo.Connection(model.a.input, model.b.output)` to `nengo.Connection(model.a.input, model.b.input)`.

**Comment by bmorcos** [comment]
Good catch,

Switched to :
```
    nengo.Connection(model.a.output, model.b.input)
    nengo.Connection(model.b.output, model.b.input, synapse = 0.1)
```
Still getting 1.8-2... is this expected? seems high still

![gui_high_saturation2](https://cloud.githubusercontent.com/assets/18405463/15905933/daa3f696-2d84-11e6-886d-5d8b32de28d7.PNG)

**Comment by jgosmann** [comment]
Yes, you have the input from `a` to `b` and the recurrent input from `b` to `b` itself. Thus, the similarity ends up to be whatever the neurons end up saturating with.

**Comment by bmorcos** [comment]
Is saturating at ~2 normal?  If this is normal there is no issue we can close this.

**Comment by jgosmann** [comment]
Yes, it depends on the total number of dimensions, the `subdimensions` parameter, and the ensemble radius. I'll cover this in some more detail in my tutorial.
