### ISSUE TITLE
Document nengo.ipynb

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1084]
We should document and recommend using `%load_ext nengo.ipynb` in Jupyter notebooks.

**Comment by celiasmith** [comment]
this wasn't working for lots of people yesterday when they tried to use 
your notebook. i suspect it was some kind of path problem?

Jan Gosmann wrote:

**Comment by jgosmann** [comment]
As long as `import nengo` works, `%load_ext nengo.ipynb` should work too (it's basically not doing much more than `import nengo.ipynb` and running a specific function).

**Comment by celiasmith** [comment]
pretty sure import nengo was working. to get the notebook you had 
working, we just told people to delete the %load_ext line, and then they 
could run the notebook.

Jan Gosmann wrote:

**Comment by jgosmann** [comment]
Do you have any more details on the error? Without I can't really debug it.

**Comment by celiasmith** [comment]
I know it happened to Bruno, so we should check out what happened when 
he tried to run it with that line in there.

Jan Gosmann wrote:

**Comment by jgosmann** [comment]
Works now on Bruno's computer. No idea why it didn't before.

**Comment by tbekolay** [comment]
I installed the latest version of Jupyter lately and I got an error telling me to do

```
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

at the command line. Maybe he did that which made it work again.

**Comment by jgosmann** [comment]
Can't reproduce with Jupyter notebook 4.2.1 (which seems to be the latest version).

**Comment by tbekolay** [comment]
I was also on Python 3 if that makes a difference?

**Comment by jgosmann** [comment]
Can reproduce now (Python 2.7): `%load_ext nengo.ipynb` line works, the warning is only printed when running the simulation and it is just a warning and everything except the progress bar still works.

**Comment by jgosmann** [comment]
The progress bar is not working in the most recent Jupyter notebook (#1085). *sigh*
But it's not a hard failure; it just doesn't show up. Everything else still works.

**Comment by Seanny123** [comment]
Where would you want to put this documentation?

**Comment by jgosmann** [comment]
This is now obsolete as `nengo.ipynb` is deprecated.
