### ISSUE TITLE
Cannot generate vectors satisfying max similarity with 60 concepts and 128 dimensions.

### ISSUE THREAD

**Issue by jelmerborst** [nengo/nengo#1092]
With random generation and 100 attempts we should expect to generate 60 vectors that are approximately orthognal. Is this expected?

**Comment by jgosmann** [comment]
The expected similarity of two random unit vectors with 128 dimensions is about 0.07 (the approximation formula for `d` dimensions is `1/sqrt(π/2 * (d - 1))`). That is pretty close to the default `max_similarity` of 0.1, so the probability of exceeding this threshold gets pretty high when the space is already populated by a number of random vectors.

Also note that the random sampling does not make the best use of the available space.

**Comment by tcstewar** [comment]
> Also note that the random sampling does not make the best use of the available space.

If I remember correctly, @arvoelke had some code to do a better job of placing those vectors.  Is that around somewhere?

**Comment by arvoelke** [comment]
If you install [nengolib](https://github.com/arvoelke/nengolib/) you can generate scattered unit vectors like so:

```
from nengolib.stats import sphere
sphere.sample(n_vectors, n_dimensions)
```

However the library it's using only works up to 40 dimensions. Past that point it will revert back to our default sampling...

**Comment by arvoelke** [comment]
Alternatively `nengolib.stats.leech_kissing()` will return the [Leech lattice](https://en.wikipedia.org/wiki/Leech_lattice), which is optimally tiled (196560 unit vectors with `max_similarity=0.5`) in 24 dimensions.

**Comment by Seanny123** [comment]
@jelmerborst Did using `nengolib` solve you problem? Can we close this issue now?

**Comment by jelmerborst** [comment]
It still gives the warning, but it works fine in practice.
