### ISSUE TITLE
How to set intercepts on spa.State?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1096]
I want to use the vOja learning rule, so I need to set the intercepts on an ensemble. However, I would also like that ensemble to be contained in `spa.State` so that I can use the SPA visualisations provided in the Nengo GUI. I thought I could accomplish this by setting the intercepts in a config and then using the config when I created my `spa.State`, but I get the following error:

```
ValidationError: ClassParams.intercepts: n_neurons not yet initialized; cannot determine if shape is correct. Consider using a distribution instead.
```

How can I set the intercepts in a `spa.State` do I have to make my own SPA module?

**Comment by jgosmann** [comment]
Did you "Consider using a distribution instead."?

**Comment by Seanny123** [comment]
Ugh, I only realised that I could make a distribution with a single choice, which solves my problem.

**Comment by jgosmann** [comment]
Close issue?

**Comment by Seanny123** [comment]
Noted it as something to document later.
