### ISSUE TITLE
Document change to eval points from 1.4 to 2.0

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1101]
This was mentioned at the dinner? I don't know the details, but I thought I would write it down.

**Comment by jgosmann** [comment]
I think the problem at the summer school was not porting from 1.4 to 2.0 but running code from the summer school 2 years ago with the current Nengo. I'm not sure what the behaviour in 1.4 was, but if it differs we should add that to the converting from Nengo 1.4 to 2.0 section.

Also note, that the change in the behaviour for the 2.0 development line was done before the release of 2.0 and thus I don't think it needs to be mentioned.

Commit introducing the change: 98f093d8e16612df12bfeb6a96196ee8427e8249
Related discussion: #564

**Comment by jgosmann** [comment]
Given my previous comment: Is there anything we should document and if so how do we do that in a reasonable way? If not, let us close this issue.
