### ISSUE TITLE
Node Frequency cap? 

### ISSUE THREAD

**Issue by Philipp114** [nengo/nengo#1103]
Hi again

After some testing on creating different input functions, i have found that at a certain frequency the functions are no longer reaching their intended values, but are getting squashed.

```
with model:    
    frequency=3  # 
   
    input= nengo.Node(lambda t: np.sin(frequency*2*math.pi*t))
```
Already when increasing a frequency to 5 or 10 the maximum value given by the node decreases to 0.8 or lower.
Is there a way to circumvent this?

Also i would like to let my ensemble calculate the amplitude of a given function, and i was wondering if anybody got an idea of how this could work with ensembles?

Any help would be really appreciated :)

**Comment by tcstewar** [comment]
That's a side effect of the synapse that's being applied.  When you make a Connection, the default synapse is 0.005 seconds, so that's smoothing your high-frequency sine wave, and that smoothing will become more obvious the higher the frequency.  You can change this synapse value this way:

```python
nengo.Connection(input, ens, synapse=0)
```

It should be noted that this Connection synapse value is independent of the Value plot in the user interface.  For the Value plot, the default synapse is 0.01 seconds, and you can change it by right-clicking on the plot.

**Comment by tcstewar** [comment]
> Also i would like to let my ensemble calculate the amplitude of a given function, and i was wondering if anybody got an idea of how this could work with ensembles?

Hmm...  that depends a lot on what you mean by the "amplitude of the function".  Are you expecting to always have a sine wave (of different frequencies) as input, and you're looking for its amplitude?  What range of frequencies?  How quickly does it change frequencies?  Or are you looking for the magnitude of the vector that's currently being represented by the ensemble?

**Comment by Philipp114** [comment]
> It should be noted that this Connection synapse value is independent of the Value plot in the user interface. For the Value plot, the default synapse is 0.01 seconds, and you can change it by right-clicking on the plot.

Ahh thank you for clarifying this, i was expecting something like that but must have missed the default value of the value plot...

> Hmm... that depends a lot on what you mean by the "amplitude of the function". Are you expecting to always have a sine wave (of different frequencies) as input, and you're looking for its amplitude? What range of frequencies? How quickly does it change frequencies? Or are you looking for the magnitude of the vector that's currently being represented by the ensemble?



Basically my ensemble is going to add 2 phase shifted sin functions together which works completely fine and i would like to have an ensemble find out its peak value for further use. (depending how the phaseshift is given there is a different peak which i would like to compare)

The functions are as simple as the sin one above so values between -2 and 2. 
I have tried using queues to save old values and feeding them to the ensemble to compare but the results are not very good so far

**Comment by tcstewar** [comment]
> Basically my ensemble is going to add 2 phase shifted sin functions together which works completely fine and i would like to have an ensemble find out its peak value for further use. (depending how the phaseshift is given there is a different peak which i would like to compare)

Interesting....  Hmmm....  It's a nasty function if you want to do exactly the mathematical function of finding the peak (over some window in time, I assume).  But given the situation you're describing, I'd be kind of tempted to just do a Connection that computes the square of the value, and then put a long synapse on it.  This seems to mostly work:

```python
import nengo
import numpy as np

model = nengo.Network()
with model:
    f = 10
    stim1 = nengo.Node(lambda t: np.sin(f * 2 * np.pi * t))
    stim2 = nengo.Node(lambda t, x: np.sin(f * 2 * np.pi * t + 2 * np.pi * x[0]), size_in=1)
    
    phase = nengo.Node([0.25])
    nengo.Connection(phase, stim2, synapse=None)
    
    a = nengo.Ensemble(100, 1, radius=2)
    nengo.Connection(stim1, a)
    nengo.Connection(stim2, a)
    
    b = nengo.Ensemble(100, 1, radius=2)
    
    nengo.Connection(a, b, function=lambda x: x**2, synapse=0.2)
```

**Comment by Philipp114** [comment]
Hmm this seems very promising, its pretty much what i am trying to do, thanks a lot for this idea. So both my issues can actually be tackled by changing the synapse value.. 
Tho i did not completely understand yet how this does what it does but it seems to give good results, so i will try this out. :)

**Comment by jgosmann** [comment]
Here's an alternative option for finding the maximum of a function over time:
```python
import nengo
import numpy as np


def ThresholdingPreset(threshold):
    """Configuration preset for a thresholding ensemble.
    This preset adjust ensemble parameters for thresholding. The ensemble
    neurons will only fire for values above the threshold. One can either
    decode the represented value (if it is above the threshold) or decode a
    step function if a binary classification is desired.
    This preset sets:
    - The intercepts to be between `threshold` and 1 with an exponential
      distribution (shape parameter of 0.15). This clusters intercepts near
      the threshold for a better approximation.
    - The encoders to 1.
    - The dimensions to 1.
    - The evaluation points to be between `threshold` and 1. with a uniform
      distribution.
    Parameters
    ----------
    threshold : float
        Threshold of ensembles using this configuration preset.
    Returns
    -------
    :class:`nengo.Config`
        Configuration with presets.
    """
    config = nengo.Config(nengo.Ensemble)
    config[nengo.Ensemble].dimensions = 1
    config[nengo.Ensemble].intercepts = nengo.dists.Exponential(
        0.15, threshold, 1.)
    config[nengo.Ensemble].encoders = nengo.dists.Choice([[1]])
    config[nengo.Ensemble].eval_points = nengo.dists.Uniform(threshold, 1.)
    return config

model = nengo.Network()
with model:
    f = 10
    stim1 = nengo.Node(lambda t: np.sin(f * 2 * np.pi * t))
    stim2 = nengo.Node(lambda t, x: np.sin(f * 2 * np.pi * t + 2 * np.pi * x[0]), size_in=1)

    phase = nengo.Node([0.25])
    nengo.Connection(phase, stim2, synapse=None)

    a = nengo.Ensemble(100, 1, radius=2)
    nengo.Connection(stim1, a)
    nengo.Connection(stim2, a)

    with ThresholdingPreset(0.):
        b = nengo.Ensemble(100, 1, radius=2)
    c = nengo.Ensemble(100, 1, radius=2)
    
    nengo.Connection(a, b)
    nengo.Connection(b, c)
    nengo.Connection(c, b, transform=-1)
    nengo.Connection(c, c, synapse=0.1, transform=0.98)
```

The `ThresholdingPreset` is from PR #1077. `b` is used to represent the difference of the current input value (from `a`) and the current stored value (in `c`). Because of the `ThresholdingPreset` no negative numbers will be represented. So whenever the difference is larger than 0 we will feed additive input to the integrator `c`. The `transform` on the recurrent connection `c` to `c` controls how quickly the last peak will be forgotten.

**Comment by Seanny123** [comment]
@Philipp114 did this end up solving the problem? May we close the issue or do you have further questions? (:

**Comment by Philipp114** [comment]
Yes the main problem was solved, thanks very much for all the feedback. :D
