### ISSUE TITLE
Probe connection afferents

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#1108]
With large models (e.g. Spaun) there can be a lot of connections from different files going to multiple places. For debugging purposes, it would be nice to be able to probe connection afferents (i.e. the different signals that combine to make up the summed signal going into an ensemble or node).

Here's an example:
```
import nengo

with nengo.Network() as model:
    ens1 = nengo.Ensemble(50, 1)
    ens2 = nengo.Ensemble(50, 1)
    out = nengo.Node(size_in=1)

    nengo.Connection(ens1, out, function=lambda x: x ** 2)
    nengo.Connection(ens2, out)

    # Current probe system:
    p1 = nengo.Probe(out) 
    # > Probes the output of 'out' which is ens1**2 + ens2
    # What i'd like:
    # probe_list = nengo.Probe_input(out)
    # and the probe list would look something like this:
    # [nengo.Probe(ens1, function=lambda x: x**2), nengo.Probe(ens2)]
```

**Comment by hunse** [comment]
You can probe their combined value with `nengo.Probe(out, 'input')`. Or you can probe them all with something like `[nengo.Probe(c) for c in model.all_connections() if c.post_obj is out]`. Would either of those do what you want?

**Comment by xchoo** [comment]
The latter. :smile: 
`[nengo.Probe(c) for c in model.all_connections() if c.post_obj is out]` would do it, but it's very computationally expensive for large models (i think?)

**Comment by jgosmann** [comment]
You can do it on the subnetwork containing the connections, but that might still be a lot of connections?

**Comment by xchoo** [comment]
Unfortunately, a lot of these connections in Spaun are at the highest network level (from spa module to spa module).

**Comment by hunse** [comment]
Is it computationally expensive? It's just iterating over a bunch of lists. Even for a model 10 times as large as Spaun, if that's taking more than a few milliseconds I would be surprised. Have you tried it @xchoo?

**Comment by xchoo** [comment]
No. I haven't. Can give it a shot though.

**Comment by xchoo** [comment]
Fun fact, spaun has just over 400k connections, and it takes 20ms to generate the list of all the connections, and 1.5s to iterate through all of them (and filter the right ones out).

**Comment by hunse** [comment]
Hmm, that seems like a lot longer than it should take, especially the filtering. It could be that our parameter system makes it slower to access parameters for filtering than with a normal python object.

I'm also surprised that Spaun has so many connections: with 5 million neurons, that's just 12 or 13 neurons per connection on average, which seems low.

Oh well, in the scope of building Spaun, this is a negligible amount of time, so I think this approach is fine for now.

**Comment by xchoo** [comment]
Hmm. I think the low neurons per connection average is because the connection count is counting connections to and from nodes (e.g. for a 512D ensemble array, there are already 1024 connections, half from the input node, half to the output node). 

And yes, 1.5s out of 2000s is insignificant, but every second helps!

I'll close this issue for now.
