### ISSUE TITLE
Get object references for automagically created SPA networks

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#1109]
The current SPA system automagically creates networks (typically in the BG & cortical action systems). Unfortunately, adjusting the properties of these networks (e.g. to change the radii of the internal ensembles) is pretty tedius. Having a helper function (or some way of specifying the parameters you want to use for said connection) would be real great!

**Comment by jgosmann** [comment]
That's something I want to take into consideration with #1014, #941, etc.
As discussed in the last dev meeting we probably won't implement any new features in the current SPA system and move the development to a new repository. But to make this new repository the official SPA nengo/nengo_gui#797 has to be resolved.

I added a SPA label for issues to easily find these issues that need to be considered once the new repository is created.

**Comment by xchoo** [comment]
Ah yes. I was just making the feature request as a reminder. :smile:

**Comment by jgosmann** [comment]
Please take a look at #1209. Does that seem sufficient?

**Comment by jgosmann** [comment]
Done in #1209.
