### ISSUE TITLE
__len__ of Signals

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1115]
82fa8221e8b3c18353a75794e5e52d2391f8b724 (by @drasmuss and @hunse) removed the `__len__` function from `Signal` (and `SignalView`). Is there a specific reason for that change or was it just overlooked?

This change currently breaks `nengo_detailed_neurons` (though easily fixable by using `.shape` instead of `len`). But I wonder whether we should reintroduce `__len__` on `Signal`s?

**Comment by hunse** [comment]
I'm guessing it was just an oversight. I'd have no problem adding it back in, though if `__len__` is implemented does that create the assumption that one should be able to iterate over a Signal? That would be my only concern.

**Comment by jgosmann** [comment]
I think technically you could iterate over it because `__getitem__` is implemented.

**Comment by hunse** [comment]
Oh, does that automatically implement iteration? Even if it doesn't, we could always implement `__iter__` or whatever is needed along with `__len__`.

**Comment by jgosmann** [comment]
If `__getitem__` is implemented accepts indices starting at 0 it can be used to iterate over something (no other methods, not even `__len__` required). For efficiency it can make sense to implement `__iter__` anyways. But I probably would not bother for `Signal`s as we currently not iterating over them.

**Comment by tbekolay** [comment]
Alternatively, we can explicitly raise an exception in `__iter__`... what would iterating over a signal give us? Views on each element of the underlying signal? Not sure we really want to encourage that...

**Comment by jgosmann** [comment]
I don't think we're encouraging it and I don't think we need to explicitly prevent that usage.

**Comment by hunse** [comment]
Frankly, I'm not convinced that `__len__` is particularly useful in this situation. I think it's clearer and more explicit if we leave it unimplemented and make people use `.shape[0]` everywhere. Why have two ways to do things? :)

**Comment by jgosmann** [comment]
Because it's consistent with NumPy?

Personally I would use `__len__` only for 1d signals, where `len(signal)` seems clearer to me than `signal.shape[0]`. Anyways, it's not a strong preference.

**Comment by hunse** [comment]
The big difference I see with Numpy is that it has other things built in for iteration, which we may not support (I think all the iteration business might warrant further discussion). I would be happiest to keep `__len__` out for now if it's not a strong preference.

**Comment by jgosmann** [comment]
I don't think `__len__` has to do a lot with iteration. Just by having a `__getitem__` method that accepts integer indices, it is possible to iterate over it.

**Comment by drasmuss** [comment]
I've never liked the len/shape redundancy in numpy, so if we have the
option to avoid it here that'd be my vote. Not a strong preference though.

**Comment by studywolf** [comment]
+1

**Comment by tbekolay** [comment]
Also +1, I've never bothered to remember what `len(ndarray)` even gives you because looking at the shape is more explicit and obvious.

**Comment by bjkomer** [comment]
I haven't done much with Signals, but my preference would be to keep the `__len__` function. I use `len(ndarray)` in numpy all the time (seems more clear and less typing for the cases where I use it) so maybe somebody would want to do that with Signals.

**Comment by jgosmann** [comment]
It seems most people lean towards not providing `__len__` and just closing this issue is the path of least resistance (as opposed to making a PR reimplementing `__len__`). `nengo_detailed_neurons` has been changed to use `shape` anyways.
