### ISSUE TITLE
Make encoders probeable on ensembles

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1117]
Right now, to probe changing encoders, you probe a Voja learning rule object. However, since encoders 'belong' to ensembles, it makes more more sense to probe them on an ensemble rather than the learning rule. We should make it possible to probe encoders on ensembles (for the same reason we can probe the weights on connections).

**Comment by bmorcos** [comment]
Once encoders are probeable directly from the ensembles do we want to keep encoders probeable from the learning rule as well or remove that?
>Encoders probeable from **ensemble & learning rule**
>Encoders probeable from **only ensemble**

**Comment by drasmuss** [comment]
I should mention, I implemented this for a different PR (https://github.com/nengo/nengo/pull/553, see commit 4a572c340bcfcf3c0b64f1724bbab9f482acb703.  I just added probing to the ensemble (leaving the learning rule as is), but I think it'd probably make sense to remove it from the learning rule.  I also didn't test that change at all, just tried it out for the specific use case in that PR.

**Comment by shrutisneha2011** [comment]
how can we check the synaptic weights in nengo  @drasmuss kindly reply

**Comment by drasmuss** [comment]
Hi @shrutisneha2011.  The best way to get help with modelling questions is to post them on https://forum.nengo.ai/

**Comment by shrutisneha2011** [comment]
Thank you so much Sir for your reply. It really means a lot, i tried so far
reaching you but failed.

**Comment by shrutisneha2011** [comment]
Youth4workHi ,Shruti Sneha, your contact & who has this profileSuggests you to try a quick, 5 min, Online Skill test to know your own skillshttps://www.youth4work.com/onlinetalenttestIt’s a fun test that helps you know where you stand for your skills across the globe. It also helps you get professional opportunities.Regards,Youth4workUnsubscribe
