### ISSUE TITLE
Should Network.all_networks include self?

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#1125]
I just found myself writing this code for making a list of the parents of each Node:

```python
parents = {}
for net in model.all_networks:
    for node in net.nodes:
        parents[node] = net
```

That doesn't actually handle all the Nodes in the Network.  What I actually have to do is this:

```python
parents = {}
for net in [model] + model.all_networks:
    for node in net.nodes:
        parents[node] = net
```

Right now, ```all_networks``` doesn't actually return all the Networks.  It just returns all the Networks that are *inside* the top-level network (i.e. all the sub-networks).  

This is perfectly reasonable behaviour, and it's not particularly hard to work around it for this case, but it did take me a few minutes to figure out why my first version didn't work.  It might be slightly more intuitive if all_networks did include the top-level network itself, but I thought I'd solicit other opinions.  :)

**Comment by jgosmann** [comment]
While it seems to me that in most use cases one probably wants `[model] + model.all_networks`:
* `all_networks` returns all subnetworks which is consistent with `networks` returning all direct subnetworks.
* It is easier to add `model` to the list than to filter `model` out of the list.

**Comment by tbekolay** [comment]
I agree with @jgosmann, the current behavior is more consistent, and it's harder to filter than to add.

One alternative is to switch the behavior of `all_networks` to include `self` and add a `model.all_subnetworks` which does what `model.all_networks` does now. Personally I'd rather not do it, but it's a possibility.

**Comment by jgosmann** [comment]
There seems to be no one strongly in favor of this change. Can we close this issue?

**Comment by hunse** [comment]
I'm also mildly in favour of keeping things the way they currently are.

It's up to @tcstewar whether he wants to close the issue, or try to sell us on his point of view :)

**Comment by tcstewar** [comment]
I'm good to close it and leave things how they are.  :)  After thinking about it, I don't feel particularly strongly about it either way, but the feedback was useful.  Thanks all!
