### ISSUE TITLE
Synchrony in the ensemble

### ISSUE THREAD

**Issue by vignan21** [nengo/nengo#1126]
Is there any function to find synchrony in the ensemble?

**Comment by arvoelke** [comment]
Hello @vignan21. Could you please repost this on the [Nengo forums](https://forum.nengo.ai) which we have just recently set up for such questions? The GitHub issues are now reserved for bugs and software-related discussion. Thanks!

That said, I don't know if we have such a function in `master`. It may be easiest to take someone else's code that does the analysis you want and pass it the Nengo spike trains.

**Comment by arvoelke** [comment]
[Question moved here.](https://forum.nengo.ai/t/synchrony-in-the-ensemble/62)
