### ISSUE TITLE
Nengo freezes periodically

### ISSUE THREAD

**Issue by arnav-gudibande** [nengo/nengo#1138]
<img width="756" alt="screen shot 2016-08-05 at 11 20 26 am" src="https://cloud.githubusercontent.com/assets/15108659/17446554/b817fc06-5afe-11e6-9e38-eb5b9b1f7ecb.png">

While running my project on macOS 10.12, nengo complains about an unavailable resource and freezes intermittently during runtime. However, when running on Ubuntu 14.04 LTS, nengo runs the project without any issues.

Is there any way I can get nengo to stop complaining about this temporarily unavailable resource?

[Source Code for Project](https://github.com/arnav-gudibande/nengopacman)

**Comment by jgosmann** [comment]
Thank you for the bug report.
From the output you have posted, it seems that this is not a Nengo, but a [nengo_gui](https://github.com/nengo/nengo_gui) bug. Would you mind reposting the issue there? (Then you still get updates to the issue.)

Furthermore, we have rewritten a major part of the underlying server architecture of nengo_gui. This hasn't been part of an official release yet, but if you go to the linked page you can download the current development version (the green button at top right). Try to install it and see if that problem persists. If you're lucky it might already be fixed. If not, it would be very helpful to get the error output that you get with that version.

Also, as macOS 10.12 is still in beta, we haven't tested nengo or nengo_gui on it yet.

**Comment by arnav-gudibande** [comment]
Ok, thanks for the reply. I'll go ahead and move it to nengo_gui
