### ISSUE TITLE
Import/Export function ?

### ISSUE THREAD

**Issue by Philipp114** [nengo/nengo#1139]
Hello together, hope youre having a nice summer

I am still working on some small functions using nengo and would like to add a few more features.

**One problem** i start running into is the simulation time needed to test out my codes.
Since i have one bigger program i wanted to ask if there is an easy way to export/import the results of a simulation inside nengo to maybe split it into 2 modules?
_For example:_  
Module 1 runs 5 Seconds and calculates a function.
Module 2 needs this function as an input to carry on.

**A second problem** is a program using an array of many ensembles to calculate different sums. I would like now to identify the ensembles that have the highest (highest 3, or even those above a certain threshold) values for further usage (maybe by inhibiting the others?!).

Any help would be greatly appreciated!

**Comment by Seanny123** [comment]
Hey Phillip! We would be happy to help, but would you mind moving your question to [our forums](https://forum.nengo.ai/) so we can help you there instead?

**Comment by Philipp114** [comment]
Oh is that a new forum? thanks for the link, i posted the question there so this can be closed then.

**Comment by tbekolay** [comment]
Thanks!
