### ISSUE TITLE
ensemble process macroblock

### ISSUE THREAD

**Issue by vanbommel** [nengo/nengo#1140]
Thank you for reading my question.

I am using Nengo 1.4 to create model for unsupervised learning. It seems the document of Nengo 1.4 saying no example about how a ensemble process a macroblock and update weights accordingly.
Given I create one ensemble of 4 neural nodes (one dimension), I want each node load exactly one element from one 2x2 input array, this 2x2 ensemble is connected with one single-neuron ensemble as output. The synaptic weights will be updated proportional to the product of input and output, saying, like Oja‘s rule. 
How can I create such network ? 
Also how can I know the indexing of neurons in the input ensemble ? 
Is this question more easily resolved by Nengo 2.0 ? I have installed it as well. 
Many thanks.

**Comment by tbekolay** [comment]
Hi @vanbommel! Unsupervised learning is not very well supported in Nengo 1.4 (the repository for Nengo 1.4, by the way, is [here](https://github.com/nengo/nengo_1.4)), so what you're asking for is possible, but not easy. You would likely have to write your own learning rule, as described in [this technical report](http://compneuro.uwaterloo.ca/files/publications/bekolay.2010c.pdf).

Nengo 2.0 does make this type of network easier to create. [This notebook](http://pythonhosted.org/nengo/examples/learn_unsupervised.html) shows how to do unsupervised learning, including with Oja's rule.

Let me know if that's enough to get you started. If it is, then I'd encourage you to ask more questions as you develop your model in our new [forum](https://forum.nengo.ai/), which is better suited to answering questions. Github is better suited to bug reports and new features and the like.

Thanks!

**Comment by vanbommel** [comment]
Oh, amazing fast response in 15min (I have ever had technically) :) Thanks a lot ! @tbekolay
 Sorry for that, just realized I should put question in the new forum. 
Have a nice summer ~

**Comment by tbekolay** [comment]
No worries, the forum is quite new so we don't have links to it everywhere that we should :) We'll fix that soon, hopefully!
