### ISSUE TITLE
API for data generated during build.

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1145]
We should define an API how information generated during the build (e.g., decoders, encoders, sample points) can be accessed. The reference builder currently provides `sim.model.params`, but not all backends provide `sim.model`.

#933 is related and should be considered together with this.

This sort of API is relevant for PRs as #995, #941 (even without deferrables), #1062, and #553.

**Comment by tbekolay** [comment]
Actually the "correct" place to access these things is through `sim.data`; e.g. to get the decoders of a connection it's `sim.data[conn].weights`. But obviously this is not well documented or advertised, in part because #933 hasn't moved in a while.

**Comment by jgosmann** [comment]
Does that work without probing and for all parameters?

**Comment by tbekolay** [comment]
Yeah, we basically copy `sim.model.params` into `sim.data`.

**Comment by jgosmann** [comment]
But there are things like the ensemble radius that are not in `sim.model.params`?

**Comment by tbekolay** [comment]
Yeah, that's true, we could add them. In the builder refactoring that I started (but haven't worked on for a while) I add everything to `BuiltEnsemble` so that it's a second type of canonical representation for ensembles, and so on for other objects.

**Comment by jgosmann** [comment]
Given the discussion in #933, I would propose the following:

All static parameters (in the sense they don't change during the simulation) on Nengo objects should be stored as attributes of `sim.data[obj]` where `obj` is the Nengo object. This includes sampled evaluation points, encoders, and `solver_info` on connections. This should be recommended for all backends (or they won't be feature complete and other Nengo things might not work, like plotting tuning curves or generic learning rules).

Access of these things via `sim.model` should be considered as obsolete (if it happens outside of the builder) because it is backend dependent.


I could potentially be convinced to go with [static probes](https://github.com/nengo/nengo/issues/933#issuecomment-172116510), because it matches our existing probe syntax nicely. But [there are some issues](https://github.com/nengo/nengo/issues/933#issuecomment-241233795) that would make the implementation more complex (and even without these issues it would probably be higher degree of complexity because the build of the static probes will be decoupled from the place where the evaluation points for example are generated).
