### ISSUE TITLE
Decoder cache should “touch” legacy.txt each time

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1154]
On Sharcnet it makes sense to write the cache files to the cluster-local `/scratch` (faster than `/home` or `/work`). The files in `/scratch` expire after 62 days and will be deleted. This is fine for normal cache files, but should not happen to `legacy.txt` because it means that the cache will be reinitialized discarding all other (not yet expired) cached files.

It's probably sufficient to “touch” (i.e., set the modification time to the current time) legacy.txt each time we instantiate a cache to prevent this.

**Comment by tbekolay** [comment]
Seems too specific to a specific environment in my opinion... you could touch `legacy.txt` in your model to have the desired effect without affecting other super specific environments.

I'm not sure how long it takes to touch a file, but it's common for me to spin up a ton of simulators to test something in a small model; modifying the file system on each of those would add up. So given that, we could add some kind of check to only touch it if it's past a certain number of days, but then how many days, so then we make that configurable, and then it becomes a thing that is spread out over different parts of the code that we now have to maintain... as opposed to a one line change in each model you run on sharcnet.

**Comment by jgosmann** [comment]
> we could add some kind of check to only touch it if it's past a certain number of days, but then how many days

Reading the modification time will probably take at least as long as touching the file, so just touching it would be faster. I don't think that this would performance largely, because if the cache is activated it has to access at least the cache index and an additional touch should not really make any difference.

I also don't think it's super specific to have the modification time updated. It's basically just a way to say this legacy information is correct as of *date*. And on some systems this fixes some problems (I assume other HPC clusters might have similar data storage).

**Comment by tbekolay** [comment]
> on some systems this fixes some problems

I'm hesitant to add it in... it's hard to predict whether this will also cause some problems on some systems.

If this were the only possible solution to the issue, I would err on the side of including it, but since it's possible to fix this in a user model I say leave it. If it ends up appearing in a significant portion of user models across multiple users, then we could add it in, but for now this seems premature. Happy to hear other people's thoughts (I think ours are already pretty clear @jgosmann).

**Comment by jgosmann** [comment]
> it's hard to predict whether this will also cause some problems on some systems.

I'm not sure what problems you expect. It's changing the modification time of a file we access anyways in a directory that needs to be writable anyways (and in some instances we even have to write the file in the first place). If that fails a lot of other things in the cache should fail too.

> but since it's possible to fix this in a user model I say leave it

But it's ugly. I have to add it to every single model, I have to figure out the correct path (which is to some degree an implementation detail of the cache and might change), there might be race conditions (in the cache all access to legacy.txt happens in a lock, if I do the same in my model what could be a one-line change becomes way more complicated).

**Comment by drasmuss** [comment]
Even if no changes were made to the user model, doesn't this mean that in the worst case the decoders would need to be recomputed once every 62 days?

**Comment by jgosmann** [comment]
It would throw away all of the cache every 62 days (even decoders that might have cached just a day ago).

**Comment by jgosmann** [comment]
arg, accidently commited and pushed onto master, I'll fix this.

**Comment by jgosmann** [comment]
fixed

**Comment by tbekolay** [comment]
I made an [HPC category on the forum](https://forum.nengo.ai/c/hpc) which could be a good place to accumulate knowledge about using Nengo in HPC environments like sharcnet.

**Comment by jgosmann** [comment]
Made a PR with the actual one-line change that would be required and verifyed that the performance impact is negligible.
