### ISSUE TITLE
Put link to forum in README

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1170]
I think this would make it easier for people to find, and result in fewer questions being asked here.

**Comment by Seanny123** [comment]
I'll shove it in under the `Documentation` section? Or should I rename the section to `Documentation and Help`?

**Comment by tbekolay** [comment]
I think make a separate "Support" section (could be named "Getting help" or something else instead).

**Comment by Seanny123** [comment]
Resolved in #1193
