### ISSUE TITLE
Move documentation to Github pages

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1171]
I ran `upload_sphinx` as I normally do to put docs on pythonhosted.org, but got the following message:

```
Upload failed (410): Uploading documentation is no longer supported, we recommend using https://readthedocs.org/.
```

Unfortunately, uploading docs to readthedocs.org is not [implemented yet](https://github.com/rtfd/readthedocs.org/issues/1083).

For the time being, I've uploaded the docs manually to pythonhosted.org, but this is probably a good time to solidify a plan for where to put this stuff moving forward. I've posted a plan of attack at https://github.com/nengo/nengo.github.io/issues/10; please feel free to check out that issue, I'd appreciate feedback on whether the end product makes sense.

Once that plan's been finalized and implemented, we'll need to:
- [x] Update all references to pages hosted at pythonhosted.org to the correct page at nengo.ai

**Comment by Seanny123** [comment]
Can this be closed now? Are there any references lingering around?

**Comment by tbekolay** [comment]
I thiiiiink it should all be updated now yep :+1:
