### ISSUE TITLE
Tell depsy.org that Nengo is research software

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1172]
Today I came across the site [depsy.org](http://depsy.org/) that tries to give credit to the impact of research code. It also offers badges (in fact the badge on [matplotlib.org](http://matplotlib.org/) led me there). Unfortunately, they think than [Nengo is not research software](http://depsy.org/package/python/nengo). But they have a “guessed wrong” link (where you apparently just open a GitHub issue?).

Shall we tell them that Nengo (and nengo_ocl etc.) is research software?
Do we want to include the badge?

**Comment by tbekolay** [comment]
I don't see why not! Go ahead and file an issue with them @jgosmann. We wanted to add a link to the forum also, so might as well add the badge while we're editing the readme.

**Comment by jgosmann** [comment]
I created the issue: Impactstory/depsy#76
Until that is resolved, it probably does not make sense to include the badge as Nengo is placed in the 0th impact percentile right now.

**Comment by jgosmann** [comment]
Closing this because depsy.org is not actively maintained any more. :disappointed:
