### ISSUE TITLE
Plots from iPython notebook aren't rendering on pythonhosted

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1174]
All of the iPython notebook examples aren't rendering their plots on `pythonhosted`.

Maybe related to #1171 ?

**Comment by tbekolay** [comment]
Thanks for pointing that out; I saw that the release version had changed on the index page and assumed that the zip had uploaded successfully despite pythonhosted.org giving me a 503 timeout error. I'll keep trying to upload it, but it's continually giving me 503 errors when I upload, so perhaps getting a github pages solution going is high priority.

**Comment by tbekolay** [comment]
Turns out the zip file I originally uploaded didn't have the image files for some reason? Anyway, it should be [fixed now](http://pythonhosted.org/nengo/examples/nef_summary.html), please verify and close if they work for you!
