### ISSUE TITLE
Option to not normalize encoders

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1191]
It would be nice if encoder normalization could be turned off.

**Comment by jgosmann** [comment]
Can't you set the gains accordingly? And if it were possible to use non-normalized encoders, you probably still want to set the gains to something non-random?

**Comment by hunse** [comment]
Actually, in my case, it's that I already have intercepts found assuming the encoders are unnormalized. You're right, that this can be done by setting the gains properly. It's just more work to figure out.

**Comment by arvoelke** [comment]
I've wanted to do this before too, without changing the gains. I don't remember why... think it had something do with representing a vector where the dimensions were pairwise mutually exclusive... Hopefully I'll remember at some point and report here.

**Comment by tbekolay** [comment]
We've already got [`scale_eval_points`](https://github.com/nengo/nengo/blob/master/nengo/connection.py#L377), I suppose there's no harm in `scale_encoders`? ¯\\_(ツ)_/¯

**Comment by jgosmann** [comment]
> I already have intercepts found assuming the encoders are unnormalized. You're right, that this can be done by setting the gains properly. It's just more work to figure out.

I see.

> I suppose there's no harm in scale_encoders?

A few more lines in the builder?
Slightly longer function signature?

But I'm fine with that if other people are fine with that. I would only change the name to `norm_encoders` or `normalize_encoders`. They don't get scaled (e.g. by the radius as eval points), but just normalized.

**Comment by hunse** [comment]
> Slightly longer function signature?

I'm guessing it won't be used very often, so I'm fine if it's not part of `Ensemble.__init__`.

I agree, `normalize_encoders` makes more sense to me.

**Comment by tcstewar** [comment]
I'd also like the ability to not normalize encoders.... It's not a frequent thing, but it's more of a "once or twice a year" thing that I've wanted to do....  :)

**Comment by Seanny123** [comment]
Resolved in #1267
