### ISSUE TITLE
Should we warn on accessing `sim.model`?

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1198]
In #1173 we made `sim.model` effectively private by making it accessible through a property that raises a warning when it's accessed. This ended up causing an [issue with OCL](https://github.com/nengo/nengo/issues/1180) that I [fixed](https://github.com/nengo/nengo_ocl/pull/128), but the fix is admittedly not ideal. An alternative would be to revert part of [#1173](https://github.com/nengo/nengo/pull/1173) and allow access to `sim.model`, but not encourage it. It should be noted that even in the current implementation, one is free to access `sim._model`, but the underscore is used as a convention to say "access at your own risk".

This is one instance of the back-and-forth we often have on Java-like control in which we try to prevent the user from being able to make any mistakes (e.g. all of [`nengo.params`](https://github.com/nengo/nengo/blob/master/nengo/params.py)) and giving the user more control, which they can easily misuse (e.g. `Connection.function` and `Node.output`). Python tends to lean toward the latter approach, but as things scale up there often ends up being a need for more control to help guide the user in the right direction.

So, the question is whether accessing `sim.model` is one of those cases. Let's share our thoughts in this issue (by Thursday evening at the latest), and if there's a clear consensus we'll move forward with the consensus decision. If it seems close, then we'll make a vote on the forum.

---

My opinion is that we should revert back to not warning on accessing the model. I think that it's fine for the public interface of each backend to differ from other backends -- there's really no way around that, as they all have different concerns.

We definitely should be more clear about what each backend is required to implement, which could be achieved through an abstract base class or something to that effect, but I think that's not a sufficiently pressing reason to change the public interface of `Simulator`. I think that if people are using another backend and `sim.model` doesn't work, it's not the end of world (especially since it's not necessarily true that the information will be accessible in `sim.data` either), whereas limiting access to `sim.model` when people might be using it for legitimate (though advanced) purposes feels :crying_cat_face:

So yeah, I think that we should not consider `nengo.Simulator` to be the specification that all backends must adhere to, but instead has its own API. If we feel we should limit access to `sim.model` it should be because it makes the most sense for `nengo.Simulator`, not because of a general backend spec (which should be separate).

I'm pretty sure I wrote a short version of that spec somewhere, but I can't remember where... I'll update this post when I find it.

**Comment by drasmuss** [comment]
I'm also +1 on reverting the warning.

**Comment by tbekolay** [comment]
Oh, found it, it was in that paper I wrote that got retracted. Of course the full text is still available online: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4609756/ see section 2.1.2. I can copy that text into the documentation somewhere, but yeah, it's tough to justify taking that much time to write things for backend designers since there are only like four of them.

**Comment by tcstewar** [comment]
I'm also in favour of reverting the warning, and I like @tbekolay 's argument "that it's fine for the public interface of each backend to differ from other backends".

**Comment by tcstewar** [comment]
That said, @jgosmann makes some good and relevant points here: https://github.com/nengo/nengo_ocl/pull/128#issuecomment-260777231

I think one possible idea in the direction that @jgosmann is going there is to say that the reference Simulator's public interface (i.e. everything without an ```_underscore```) is the set of things that all Simulators should provide.  If that could work, then that would be a very good argument for having it be ```_model``` and leaving this warning. I still want to think a bit on that idea, though.... But in the meantime, I think that'd be a bigger job and I'd still want to get rid of this warning for now and then switch over to the ```_underscore``` approach in the future.

**Comment by jgosmann** [comment]
-1 on reverting the warning.

> I like @tbekolay 's argument "that it's fine for the public interface of each backend to differ from other backends".

Yes, but in my opinion that is neither an argument for or against the warning. It only says that Nengo OCL (and other backends) can make their own decision whether to support access to `sim.model`. As @tbekolay  says:

> If we feel we should limit access to sim.model it should be because it makes the most sense for nengo.Simulator, not because of a general backend spec (which should be separate).

I agree with that, but I don't think it makes sense for `nengo.Simulator` to expose the model.

* It violates the Zen of Python: “There should be one-- and preferably only one --obvious way to do it.” and I haven't heard a good argument why it should violate this principle.
* For advanced users there are still ways to get access to the model. Either via `sim._model` which indicates that this is something that might depend on implementation details that could change in the future. Or users can create their own `Model` instance and pass it into the `Simulator` constructor.
* At the moment there is no good documentation whether to use `sim.data` or `sim.model.params`. The warning helps to point users in the right directions and prevents future issues with their code.

**Comment by jgosmann** [comment]
I also wouldn't be surprised if the builder refactoring changes the way one is supposed to access `model` if one desires so.

**Comment by drasmuss** [comment]
I just don't think it's useful, or Pythonic, to try to prevent users from accessing attributes of an object.  The idea that attributes specific to the reference simulator should all be preceded by a `_` is not a policy we have consistently enforced at all (see `sim.signals`, `sim.rng`, `sim.dg`).  And I think there's a good reason for that, namely that the vast majority of the attributes of a class tend to be specific to that class, and if you precede them all by `_` and add properties all over the place it just makes things needlessly complicated and messy.

I think the better solution is to explicitly define the public interface, either through an abstract class or documentation, rather than having a semi-enforced, semi-consistent `_` policy.

**Comment by tbekolay** [comment]
> It violates the Zen of Python: “There should be one-- and preferably only one --obvious way to do it.” and I haven't heard a good argument why it should violate this principle.

My issue with this argument is that there are lot of things stored on `sim.model` that aren't copied to `sim.data`, most notably the signal and ops dictionaries (the Simulator stores them with less structure), which is a useful thing to have access to when you have to hack in something that we don't currently have an interface for.

One alternative would be to put the built classes directly in `sim.data` directly instead of storing them on the model, but then we get into the same issue as in the deferrables PR where the model has to know about the simulator, which shouldn't happen.

How would you feel about privatize `Model.params` instead? We can make it `Model._params` with an attribute you can access with a warning?

> At the moment there is no good documentation whether to use sim.data or sim.model.params. The warning helps to point users in the right directions and prevents future issues with their code.

I feel like this argument is made a lot in these comment threads, and as the person who writes ~75% of the documentation, it really bums me out. There [is documentation](http://pythonhosted.org/nengo/backend_api.html#reference-simulator), but of course it's not written in a way that is immediately obvious when someone is facing a specific issue. The thing is, once you encounter an issue like this, and ask someone or find an example to answers the question, it no longer feels like it should documented because you're essentially documenting where the documentation is, if that makes sense. I feel like people end up doing a lot of self-documentation where they chronicle their journey to learn a bunch of stuff, which feels good and productive, but doesn't necessarily help many other people because people have to go through their own journey to learn these things before they will understand the documentation that you just wrote.

Note, I'm definitely the most guilty of doing this, which is why I've been thinking about it, but the short summary is that there's no way we can anticipate all the possible questions people might have and answer them all in the documentation. This is the role that things like the forum play, to have a publicly accessible location to ask those questions.

> I also wouldn't be surprised if the builder refactoring changes the way one is supposed to access model if one desires so.

Yes, this is definitely true. Which I think is an argument for keeping things the way they were, as things are going to change in a bigger way in the future anyhow.

**Comment by jgosmann** [comment]
@drasmuss That's a good point. But I still lean towards the warning because `sim.model.params` has been used where `sim.data` should have been used (even in our tests). If someone accesses the other attributes, they probably have a legit reason, whereas in most cases when they access `sim.model` they do so to access `sim.model.params` which should be done via `sim.data`.

> My issue with this argument is that there are lot of things stored on sim.model that aren't copied to sim.data, most notably the signal and ops dictionaries (the Simulator stores them with less structure), which is a useful thing to have access to when you have to hack in something that we don't currently have an interface for.

You still get access to those either via `_model` or passing in your own model instance and if you're hacking something in, than it doesn't seem wrong to me to obtain access to the model instance in a hacky way.

> How would you feel about privatize Model.params instead? We can make it Model._params with an attribute you can access with a warning?

That would require the builder code to do the access via `_params` to avoid the warning I assume. I don't like that because then we are accessing private attributes from outside of the class.

> Which I think is an argument for keeping things the way they were, as things are going to change in a bigger way in the future anyhow.

For me it is an argument to keep the warning to prevent people from relying on the access of `sim.model`.

**Comment by jgosmann** [comment]
I probably should also say that while I have a strong opinion about this from an idealistic/philosophical standpoint, the practical implications seem pretty minor either way. So I could live without the warning.

**Comment by tbekolay** [comment]
As discussed in the dev meeting Monday, anyone who cares has weighed in at this point and the majority is for reverting. Made #1210 to do the revert.
