### ISSUE TITLE
Sorting of examples in slow and fast is incorrect when non-notebook files exist in folder

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1204]
I was observing that the test suite would fail on examples even though it had passed before. Turns out that the sorting in slow and fast notebooks screws up when there are files not ending in `.ipynb` in the example directories. Then it can get pretty random which examples are excuted and which are skipped.

**Comment by tbekolay** [comment]
Hm... I think I checked for the `.ipynb` extension in some places in [test_examples.py](https://github.com/nengo/nengo/blob/master/nengo/tests/test_examples.py#L43), but not all of them... probably used too many list comprehensions there ¯\\\_(ツ)\_/¯

Also, workflow-wise, if you're planning to fix a bug, no need to make an issue reporting that bug beforehand... you can just make the PR fixing the bug. Having an issue and a PR (assuming the PR is relatively quick) means we have to remember to also close the issue, and it means that multiple people might work on it the same bug, which is a waste.

**Comment by jgosmann** [comment]
Yeah, I know, but sometimes I don't have the time or motivation to immediately fix the bug and create an issue as a reminder for myself.
