### ISSUE TITLE
Jupyter is angry again

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1216]
Maybe related to #1087, running Jupyter 4.2 on the master Nengo branch gives me the following warnings:
```

/usr/local/lib/python2.7/dist-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)
/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
```

Is it just me or does the Jupyter project move so quickly it's kind of amazing/horrible?

**Comment by jgosmann** [comment]
What exact statement are you executing? `import nengo`? `%load_ext nengo.ipynb`?
What is `IPython.version_info[0]` on your system (requires `import IPython`)?

**Comment by Seanny123** [comment]
I'm just doing `import nengo`, I'll give you the rest of the info when I get to my laptop, because I can't reproduce on my desktop, which makes me think it might just be my horrible Python install.

**Comment by tbekolay** [comment]
I suspect it's something to do with your [IPython configuration](http://ipython.readthedocs.io/en/stable/development/config.html) -- you might have a profile from a ways back still active. We only ever import from `IPython.config` [if in IPython 3 or earlier](https://github.com/nengo/nengo/blob/master/nengo/utils/ipython.py#L48).

**Comment by Seanny123** [comment]
I tried deleting the whole `.ipython` directory, but that didn't fix anything. However, at this point I'm 90% sure it's just my psychotic (5 years old, progressively upgraded from 12.04 to 16.04) Ubuntu install that's to blame so I'm closing the issue.
