### ISSUE TITLE
Conda fails in Travis a lot

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1217]
Often the reason for our unit-tests failing is that one of the conda packages failing to download.

How silly of an idea would it be to host our own mirror of `miniconda` and the Conda packages we need to reduce the chances of the download failing?

**Comment by tbekolay** [comment]
Yes, conda's flakiness is unfortunate. Hosting a mirror of miniconda and relevant packages would be an option, though might end up costing money so would hope to avoid it... another option might be to use TravisCI's [caching mechanism](https://docs.travis-ci.com/user/caching/); I'd have to look at it more closely, but you can cache [arbitrary directories](https://docs.travis-ci.com/user/caching/#Arbitrary-directories), so caching the directory with conda might give us what we want?

**Comment by Seanny123** [comment]
[Some other people](https://github.com/broadinstitute/viral-ngs/blob/31d8e5ae993444dbb2979eb35440ad45a900d0b0/.travis.yml#L5) are already caching with conda, so I'll make a pull request to try that out and see if it works. While I'm at it, what do you feel about moving the scripts we currently have in `travis.yml` into their own `travis/` directory so they're easier to read and edit, like they do in the linked repository?

**Comment by tbekolay** [comment]
> what do you feel about moving the scripts we currently have in travis.yml into their own travis/ directory

Yeah, I've seen this in a few places. I would consider it if it reduced code duplication (e.g., if some of the scripts were shared between TravisCI and Appveyor) or if our .travis.yml was super long, but at less than 100 lines I think I'd prefer to keep it as one file for now. If either of the those criteria changes, we can revisit.

**Comment by jgosmann** [comment]
I wonder if this is still an issue. I can't remember seeing a TravisCI failure because of conda, but that might not mean anything.

**Comment by tbekolay** [comment]
I agree, I haven't seen a failure related to Conda in quite some time (there was definitely a time when it happened a fair bit). Closing!
