### ISSUE TITLE
Distribution for single dimension of UniformHypersphere(surface=False)

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1218]
As was discovered in https://github.com/nengo/nengo_extras/issues/34, the following two samples have the same distribution:

```
CosineSimilarity(d+2).sample(n) === UniformHypersphere(surface=False).sample(n, d)[:, 0]
```

this is analogous to the (currently documented) connection that the following two samples also have the same distribution:

```
CosineSimilarity(d).sample(n) === UniformHypersphere(surface=True).sample(n, d)[:, 0]
```

The latter is useful for projecting encoders onto one dimension (see the docstring for `CosineSimilarity`), while the former is useful for projecting evaluation points onto one dimension (see https://github.com/nengo/nengo_extras/issues/34). Both of these distributions have a role in optimizing intercepts for higher dimensions.

(Interestingly, this implies that:
```
UniformHypersphere(surface=True).sample(n, d+2)[:, 0] ===
UniformHypersphere(surface=False).sample(n, d)[:, 0]
```
which is really weird!!)

Since it took a bunch of work from multiple people to prove this (deceptively simple) relationship, we should consider making `CosineSimilarity(d+2)` into its own distribution, and/or documenting the above connection.

**Comment by jgosmann** [comment]
btw: I believe the following holds:
```
UniformHypersphere(surface=True).sample(n, d+2)[:, :d] ===
UniformHypersphere(surface=False).sample(n, d)
```
(There is nothing special about the index `i=0`, it should hold for any index.)

**Comment by arvoelke** [comment]
Yeah but you have to be a little careful. While it holds independently for each index, the dimensions are correlated differently in the two cases. In concrete terms we'd say their marginal distributions are identical but their joint distributions are not. So I believe the above statement is technically incorrect if we're trying to be rigorous, but you could say the _seemingly similar_ statement:

```
for i = 0 ... d-1:
    UniformHypersphere(surface=True).sample(n, d+2)[:, i] ===
    UniformHypersphere(surface=False).sample(n, d)[i]
```

**Comment by arvoelke** [comment]
Ignore my previous comment. I realized that my direct proof of `x3 <=> x4` in the other thread can be worked to agree with you formally. So not only are the marginals the same, but the entire joint distribution is as well. This result is very surprising to me, and seems [unheard of if Wikipedia is any way to guage](https://en.wikipedia.org/wiki/N-sphere#Generating_random_points)...

**Comment by jgosmann** [comment]
The Wikipedia page gives you how to go from a distribution in the n-ball to the (n-1)-sphere, so from `surface=False` to `surface=True`. Sampling from `UniformHypersphere(surface=False).sample(n, d)[i]` will not directly give us that, because `UniformHypersphere(surface=True).sample(n, d+2)` has an additional degree of freedom that we need to sample. Whin seems to be more complicated than the described method.

What we can do is to directly sample from `UniformHypersphere(surface=True).sample(n, d+2)` and throw away two dimensions to get `UniformHypersphere(surface=False).sample(n, d)`. That would be from `surface=True` to `surface=False` and the Wikipedia page doesn't talk about that. It is also not super useful because usually we start with generating samples in the unit ball first and normalize them to get the surface distribution.

**Comment by arvoelke** [comment]
> The Wikipedia page gives you how to go from a distribution in the n-ball to the (n-1)-sphere, so from surface=False to surface=True.

Not quite.. the Wikipedia page gives you how to go from normally distributed samples (that are unnormalized) to the surface (by normalizing). So `N(0, 1)` to `surface=True`.

> That would be from `surface=True` to `surface=False` and the Wikipedia page doesn't talk about that.

It does actually. The subsection directly below says how to go from `surface=True` to `surface=False` (by scaling by a uniform variable), and this is precisely what we do in our code. In our code we go `N(0, 1) -> surface=True` with an optional step to `surface=False`.

I still do agree that this alone is not super useful as an algorithm (even though it does correspond to the transformation that we need to do). At most it would avoid needing to invoke the `rng` twice (we would avoid one call to uniform `rand` at the expense of two additional `N(0, 1)` samples, per neuron). But mathematically it's still interesting that these two distributions are equivalent, and this seems concrete enough to at least warrant a mention.

**Comment by tcstewar** [comment]
I'm glad everyone else is finding this as unintuitive as I am...  I still can't get my head around the implication of this when you set D=1:

```python
UniformHypersphere(surface=True).sample(n, 3)[:, i] === Uniform(-1, 1).sample(n, 1)
```

In other words, if you randomly pick points on the surface of a sphere, their x-values are uniformly distributed between -1 and 1.  That's just *weird*....

```python
seaborn.distplot(nengo.dists.UniformHypersphere(surface=True).sample(n=100000, d=D+2)[:,0])
```

![image](https://cloud.githubusercontent.com/assets/2380772/20694118/f6923c6e-b5b0-11e6-9ad4-1888877519a9.png)

**Comment by arvoelke** [comment]
Yeah that is the main reason I thought this couldn't be at first. It is very strange. The way I eventually convinced myself around this apparent contradiction is by rotational symmetry. Keeping focus on the x-axis (i.e., the equator of a globe), if you spin the sphere around rapidly (so that the x-axis undergoes constant circular shift) and then randomly stop it, there's nothing that biases you to be towards any part of the line in particular. The reason this is unintuitive at first is because we like to visualize the sphere as a 2D projection that has edges on the outside of the circle, when in reality these edges do not exist because we can rotate our frame of reference arbitrarily. But even when armed with this intuition, I still can't help but find it hard to accept.

**Comment by arvoelke** [comment]
And just because this is "fun" (?) here is another perspective / thought-experiment that might be more helpful and compliment the above. Firstly the choice of projecting to the x-axis is arbitrary. We can pick any unit-length vector to project onto by rotational symmetry. So pick some vector, and pick some frame of reference (let's say the vector is going directly to the "right" of where I'm facing). Assume by way of contradiction that this sampling isn't uniform. Identify a patch on the surface that you think is more dense (for instance the patch facing you) and a patch on surface that you think is more sparse (for instance the right "edge" in your imaginary 2D projection). Now rotate the sphere so that the sparse patch is where you thought the dense patch was (so the vector is likely facing you now). Now repeat your sampling on this rotated sphere with your new frame of reference. If you were consistent in how you imagined the sampling to occur, you should obtain a contradiction where the spare region is now dense. However, the two samplings should have agree'd on where they were sparse and where they were dense (by rotational symmetry). Thus the difficulty in intuition lies in correctly imagining a sampling procedure that is not biased towards your frame of reference. Hope this helps? Honestly my head hurts.

**Comment by jgosmann** [comment]
It ocurred to me that the
```
UniformHypersphere(surface=True).sample(n, d+2)[:, :d] ===
UniformHypersphere(surface=False).sample(n, d)
```
relationship might be helpful. We know that uniform sampling is not the best way of sampling, if we had a better sampling method for either the n-sphere or the n-ball it might be possible to easily adjust it to sample the other structure.

**Comment by arvoelke** [comment]
> We know that uniform sampling is not the best way of sampling, 

I assume you mean MC sampling? Reminder / plug about [this notebook](https://github.com/arvoelke/nengolib/blob/master/doc/notebooks/research/sampling_high_dimensional_vectors.ipynb) and [this implementation](https://github.com/arvoelke/nengolib/blob/master/nengolib/stats/ntmdists.py) of NTM sampling. It turns out that the hypercube is the important case, as everything reduces to that in the referenced text.

**Comment by jgosmann** [comment]
> I assume you mean MC sampling?

Yes.

So, is “Choosing the semantic pointers in a vocabulary” actually “strictly harder” than sampling? I suppose the sampling doesn't ensure the `max_similarity` constraint, but we could throw away samples violating that (which is what we're doing now, but with MC sampling). Would that allow as to get a denser packing of the semantic pointers or would it at least be faster generating them?

**Comment by arvoelke** [comment]
It might help, but I wouldn't expect much as it gets dense, as this doesn't really get around the "hard part" of the problem. Some things that I can point you to that do help: approximations such as locality sensitive hashing (which uses the [Johnson–Lindenstrauss lemma](https://en.wikipedia.org/wiki/Johnson%E2%80%93Lindenstrauss_lemma); also see my [literature review](https://www.researchgate.net/publication/305845399_Advances_in_Locality-Sensitive_Hashing?ev=prf_pub)), optimal sphere packings for specific cases such as the Leech lattice (see [this book](http://www.springer.com/gp/book/9780387985855), [my implementation](https://github.com/arvoelke/nengolib/blob/master/nengolib/stats/leech.py), and [this paper](https://www.researchgate.net/publication/305828018_Efficient_SpiNNaker_simulation_of_a_heteroassociative_memory_using_the_Neural_Engineering_Framework?ev=prf_pub) which uses it to design an optimal memory for Nengo), and the clever use of space-filling curves in geometric data structures (e.g., [this paper](http://doi.acm.org/10.1145/545381.545444) and its cousins). It would also be wise to relax the problem for the specific application. But this is a pretty deep topic and I don't want to derail this thread. :)

**Comment by arvoelke** [comment]
FYI here is a separate implementation for `UniformHypersphere` that is >20% faster on my computer for `surface=False`, because it avoids scaling the same array twice:

```
    def sample(self, n, d, rng=np.random):
        if d is None or d < 1:  # check this, since other dists allow d = None
            raise ValidationError("Dimensions must be a positive integer", 'd')

        samples = rng.randn(n, d)
        c = 1 if self.surface else rng.rand(n, 1) ** (1.0 / d)
        return samples * c / npext.norm(samples, axis=1, keepdims=True)
``` 

It's equivalently the same (just rearranging the conditional), so feel free to use.

**Comment by celiasmith** [comment]
so, oddly, i can't see this comment on github... did you remove it or 
something?

best, .c

Aaron Voelker wrote:

**Comment by arvoelke** [comment]
FYI, I deleted my post from yesterday because my profiling was messed up -- the speed claims were incorrect.

**Comment by arvoelke** [comment]
I've documented this here with Jan and Terry: http://compneuro.uwaterloo.ca/publications/voelker2017.html

Feel free to cite this in the code and/or close this thread as desired. :)
