### ISSUE TITLE
Voja learning rule missing _argreprs

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo#1219]
Noticed while working on #387

https://github.com/nengo/nengo/blob/master/nengo/learning_rules.py#L274

**Comment by Seanny123** [comment]
Aw jeez. I just realized you assigned yourself to this. Just a heads up, I resolved it in #1221 if you want to review it. I'm sorry if this inconveniences you at all.

**Comment by bmorcos** [comment]
No problem :)
