### ISSUE TITLE
Warn about intercepts out of radius

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1231]
Especially the `Exponential` distribution (if one forgets to specify `high`) makes it easy to accidentally generate intercepts outside of the ensemble radius. This leads to flipped response curves.
![index](https://cloud.githubusercontent.com/assets/850157/21113559/13357bfc-c078-11e6-844c-a5af78d082c5.png)

I think Nengo should at least warn or even raise an exception when this is happening.

**Comment by arvoelke** [comment]
This was also pointed out by #1212.

**Comment by jgosmann** [comment]
Closing this as a duplicate.
