### ISSUE TITLE
Add test instance with SciPy to Travis-CI

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1237]
We have some features that depend on SciPy, especially the optimizer (#1035) adds some more complex code that depends on SciPy and should be tested. I propose to either add one test instance to the Travis-CI config that installs SciPy or to install it on all test instances and add one test instance without SciPy (so that the fallbacks are still tested).

Note that #1035 contains e168ba44992f1d4c7f443fac6246eb6981d1de15 which adds SciPy to all Travis-CI instances, but doesn't add a non-SciPy instance so far.

**Comment by arvoelke** [comment]
In case this helps for reference, I have a `travis.yml` [here](https://github.com/arvoelke/nengolib/blob/master/.travis.yml) which adds scipy to some of my Travis-CI instances.
