### ISSUE TITLE
Downloads per month badge seems to be broken

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1238]
It seems to always say 0 downloads/month.

**Comment by tbekolay** [comment]
It's a PyPI issue. [They need help](https://bitbucket.org/pypa/pypi/issues/396/download-stats-have-stopped-working-again).

**Comment by jgosmann** [comment]
Does it make sense to remove the badge until fixed? It seems legacy PyPI won't be fixed and I didn't see any information on when a transition of PyPI to Warehouse (?) might happen.

**Comment by tbekolay** [comment]
> Does it make sense to remove the badge until fixed?

We could. There are probably more important things to do with our time, but if it gets removed that's probably better proudly displaying 0 downloads / month.
