### ISSUE TITLE
Learning across multiple connections

### ISSUE THREAD

**Issue by AlperenAydin** [nengo/nengo#1293]
Hello. I have a small question to ask. I know you can a connection between two ensembles. I want to know if you can train multiple connections at the same time. 

For example, let's say I have 3 ensembles A, B, C organized as such: A->B->C. I wish to train the two connections in there so that a certain error is reduced. Is there an example somewhere that shows how to do this? What I am asking essentially is whether there is back-propagation in Nengo?

**Comment by Seanny123** [comment]
Hello!

This repository is where we track issues with the Nengo software. If you want help with the Nengo software, please post your question at https://forum.nengo.ai (:

@hunse is working on back-prop in Nengo and will be happy to help you once you post a question in the forum and close this issue.

**Comment by tbekolay** [comment]
Anyone interested in this issue should head to [thread one](https://forum.nengo.ai/t/training-multiple-connections-at-the-same-time/253) and [thread two](https://forum.nengo.ai/t/how-to-reduce-the-dimensionality-of-a-vector/254) which discusses how to do this with the new nengo_dl project.
