### ISSUE TITLE
The build progress bar can take a long time to appear.

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1314]
No progress bar is shown, but the total time will be printed after completion.

**Comment by jgosmann** [comment]
Hm, the simulation progress is shown ... maybe this is just because the initial build step takes long and the progress bar will not be printed before completion of this first step?

**Comment by tbekolay** [comment]
Yeah this tends to happen with the build, I find that only specific types of models tend to get any progress shown. But actually this reminds me, it would be great to have the optimization process hooked into the builder progress if possible, as that will now take a significant portion of the build time.

**Comment by jgosmann** [comment]
Part of the reason is probably that we only start showing the progress bar if the ETA exceeds one second. If the first build step takes very long it won't be shown for quite a while.

> it would be great to have the optimization process hooked into the builder progress if possible

Indeed. Would you prefer to have it as an additional stage (so that you get three progress bars for building, optimizing, and simulating) or should it be included in the build progress bar?

I think the difficulty is mostly that we don't know in advance how many passes will run. Also, the question is how fine grained should the updating of the progress bar be done?

**Comment by tcstewar** [comment]
> Would you prefer to have it as an additional stage (so that you get three progress bars for building, optimizing, and simulating) or should it be included in the build progress bar?

Definitely part of the build progress bar.  The build bar should be everything done to set up the simulation, and the simulating bar should be everything done to run the simulation.

**Comment by jgosmann** [comment]
It could be useful to know how long the optimizer takes, but I suppose one could activate logging to get that information.

**Comment by tcstewar** [comment]
> It could be useful to know how long the optimizer takes, but I suppose one could activate logging to get that information.

It could be useful to know that, but it could also be useful to know the total amount of time taken solving for decoders, or generating A matrices, or any number of other sub-steps in the build process.  I don't think of the progress bar as a way to get fine-grained information like that -- it's more of a high-level "hey, stuff is going on; don't worry, your computer hasn't crashed; and we're about this proportion of the way through" indicator.  :)

**Comment by arvoelke** [comment]
> know the total amount of time taken solving for decoders

FYI this helper might be handy to keep in the back pocket (disclaimer: not thoroughly tested):

```
def solver_time(sim, model):
    return sum(sim.data[conn].solver_info.get('time', 0)
               for conn in model.all_connections
               if sim.data[conn].solver_info is not None)
```

**Comment by jgosmann** [comment]
Given that I'm finished with #1375  (#1087), I though a bit more about further improvements to the progress bar(s).

> Would you prefer to have it as an additional stage (so that you get three progress bars for building, optimizing, and simulating) or should it be included in the build progress bar?
> 
> Definitely part of the build progress bar. The build bar should be everything done to set up the simulation, and the simulating bar should be everything done to run the simulation.

I haven't looked into this issue in a while and in my mind I was thinking that the optimization step should have its own progress bar. (Though, probably none that goes from 0% to 100%, but just one indicating that something is happening like a bar moving back and forth.) Reasons for me to think that the optimization step should be separate:

* It is currently not included in the build progress bar and from the structure of the code it would not be very natural to do. That means after the build is finished we sort of “hang” for a while without output before the simulation starts.
* We can give a rough estimate about how much work is done in the build process and how much longer it will take, but we cannot easily do that for the optimization step. If we include the optimization step into the build progress bar it becomes less informative.
* Maybe time spend on build vs. optimization is too fine grained information, but it seems to be much less fine-grained and to be more high-level than times spend in individual decoder solving steps.
* The optimizer can be turned off with a single flag, which is not possible for decoder solvers.
* There is currently no interface to get the time spend on optimization (opposed to decoder solvers, see @arvoelke's example).

**Comment by jgosmann** [comment]
Dev meeting discussion: Single build + optmization progress bar, but have the label change according to current task.

**Comment by jgosmann** [comment]
I think this issue is pretty much fixed.
