### ISSUE TITLE
Documentation "Module Index" 404 Not Found

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1316]
Steps to reproduce:
 - Open [documentation](https://pythonhosted.org/nengo/)
 - Scroll to the bottom
 - Click [Module Index](https://pythonhosted.org/nengo/py-modindex.html) => 404 Not Found

**Comment by Seanny123** [comment]
Note that the "[Search](https://pythonhosted.org/nengo/search.html)" link also just gives a blank page.
