### ISSUE TITLE
Misleading error when a function returns None

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo#1318]
When forgetting to return a value from a function (e.g., omitting `return` or `return None`), a misleading `ValueError` message is returned:
```
ValueError: array must not contain infs or NaNs
```

Minimal working example to reproduce the error:
```python
import nengo

model = nengo.Network()
with model:
    a = nengo.Ensemble(n_neurons=50, dimensions=1)
    b = nengo.Ensemble(n_neurons=50, dimensions=1)
    
    def f(x):
        x

    nengo.Connection(a, b, function=f)
```

Possible better error (or warning) message would be to inform the user that `None` is returned.

**Comment by tbekolay** [comment]
Can confirm this happens! It occurs during the decoder solving process (i.e., the error is raised by Scipy, not Nengo itself). I'll make a PR to raise a better error.
