### ISSUE TITLE
Memoize on circular convolution transform can have unintended side effects

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1321]
I was changing the transforms on the connections of `CircularConvolution` in place. This had the effect of not only changing a single instance, but messing with all `CircularConvolution` instances (including future ones). It took me quite a while to figure out what was going on: [The `memoize` property on the input transform](https://github.com/nengo/nengo/blob/master/nengo/networks/circularconvolution.py#L23) caches the matrix to be reused by all circluar convolutions (of given dimension).

I'm not sure whether this should be considered an actual bug/problem because it is only relevant in very specific cases, but the cause is also not obvious when you run into it.

Potential ways to fix this:
1. Remove the `memoize` property from the input transform.
2. Have `memoize` return a copy of the cached array/object.

**Comment by tbekolay** [comment]
I wonder also if the memoizing there is premature optimization... we should profile that and see how long we spend in those functions.
