### ISSUE TITLE
Add pytest seed command line argument

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1328]
If I'm not overlooking something, the only way to change the seed used in tests is to change it in `conftest.py`. This is pretty inconvenient when using the `seed` fixture in tests of other packages (like `nengo_spa`) and also somewhat prohibitve to quickly go through a number of seeds to make sure that tests will not randomly fail for some seeds. I think a custom pytest command line argument should be added to allow to set the seed.

**Comment by tbekolay** [comment]
Personally I've not had the need to modifying the seed -- if I want to try a bunch of different seeds I usually remove the seed from the test temporarily (which effectively generates a new seed each time), but I can see that that would get tiresome if you have a lot of tests you want to run with different seed. Additionally, it is true that most of the other parts of `TestConfig` can be modified through command line arguments so it's not unreasonable to do it with this one.

As a temporary workaround, I think you can do something like

```python
import nengo.conftest
nengo.conftest.TestConfig.test_seed = 10
```

in your package's `conftest.py` to change it.

Aside: in case anyone misunderstands the original issue, it is not the case that all tests get the same seed. The seed for each test is different, and is based on hashing the name of the test function. However, the seed for each function is the same every time you run it, hence the issue.

**Comment by jgosmann** [comment]
That was easier to add than I expected ... :)

A lot of the old SPA tests are very seed dependent and they often pass on my local system, but then fail on Travis-CI where different seeds are generated. So it could save me some time, when I can test different seeds locally. It also allows me to get a feel for appropriate error bounds when writing new tests.
