### ISSUE TITLE
Permission Error in saving not prompted by the Nengo Editor

### ISSUE THREAD

**Issue by sneheshs** [nengo/nengo#1331]
After editing example file, running the 2nd consecutive time UI does not update. The issue seems like Nengo editor is trying to save the example file -- permissions denied. Noticed in the command line but it would be nice if this was prompted by the browser.

**Comment by tcstewar** [comment]
Oops, I gave the wrong URL when I told sneheshs where to file the bug report....   This should be in https://github.com/nengo/nengo_gui/issues
