### ISSUE TITLE
Document how to build documentation

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1332]
For someone who doesn't know Sphinx (me), it's not at all obvious how to go about building the documentation for myself (i.e. the command ``sphinx-build -b html docs docs-built``). This could be especially frustrating if you don't have internet access.

In the README documentation section, can we put a brief blurb about how to build it? If the instructions need to be more lengthy, we could perhaps make a docs/README file that goes into more detail.

One problem I encountered once I figured out how to build was the warning ``UserWarning: Node.js 0.9.12 or later wasn't found`` followed by the exception ``PandocMissing: Pandoc wasn't found``. I assumed ``pip install -r requirements-docs.txt`` would get me good to go, instead I also had to ``apt-get install nodejs`` (or ``apt-get install pandoc``). We should probably document this additional requirement somewhere.

Also, is it possible to build everything but the examples? They take a long time.

**Comment by jgosmann** [comment]
[There's already some documentation on how to build the documentation.](https://pythonhosted.org/nengo/contributing.html#how-to-build-the-documentation) But without internet access you might need to build the documentation first to read in another formant the the raw RST. And maybe not the easiest place to find?

**Comment by hunse** [comment]
> first to read in another formant the the raw RST. And maybe not the easiest place to find?

Exactly. I didn't realize that was there, because without built documentation, it's not easy to find. Maybe those same instructions should live in a text README file in the `docs/` folder, and then the main README can point there?
