### ISSUE TITLE
Pruning dangling objects

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1348]
In some cases Nengo models will contain objects that have no direct or indirect "side-effects" _during simulation_. For now (thinking purely about the reference simulator), I will define a "side-effect" as anything that _writes_ to `sim`, disk, or stdout/stderr (and not necessarily things that affect CPU time or memory usage). I will then define a "dangling" object as one that does not eventually "reach" anything with side-effects. 

For instance, one might call `add_output` on a `nengo.networks.EnsembleArray` and not use the default output node / connection that was created by the network. In fact, `nengo.networks.Product` ignores the default `output` created by its two ensemble arrays, as does `nengo.networks.CircularConvolution` by virtue of using the product network. Unless the user connects from these objects to produce side-effects in simulation, they will become dangling.

Likewise, I will often design my own sub-networks to create multiple outputs, only some of which are eventually read out by the user of the sub-network (often this depends on what experiment I want to run on the same instantiation of the sub-network). More generally, a sub-network might afford many different functions, only some of which are relevant for the task / model at hand. And from the point of view of producing good abstractions, I've found that it is not always reasonable to ask the user to specify exactly what is needed at the time of creation, especially in nested scenarios.

In #1040, I mentioned that this is an opportunity for the build optimizer. In particular, any objects in the operator graph that don't reach some object with side-effects may be pruned. I believe the set of objects with potential side-effects has a well-defined scope: `Probe`, `Node` with non-default `output`, custom `neuron_type`, or custom `synapse`. Dangling objects can then be found in linear time and space with a simple algorithm (spoiler: traverse backwards from each potential side-effect to mark all objects as "good", and stop each traversal whenever a good object is reached).

@jgosmann suggested that "it's probably best to do it before the build to avoid computing unused decoders". But, for sake of discussion, we would want to allow for the fact that custom decoder solvers may also have side-effects. For example, one might create a solver that dumps the weights into a file or embeds them elsewhere in the model via some node. In this case, the connection with this decoder solver could be dangling, but the user would still expect it to be invoked. The same also applies to custom (registered) builder methods, which might have side-effects that the user expects to see during build or simulation. But the examples I have in mind here are admittedly more contrived...

More critically, the user may still expect to see all of the "build artifacts" within `sim.data` such as the decoders, tuning curves, etc., even when said data comes from a dangling object. For instance, @psipeter creates networks with a single dangling fixed-seed-LIF population in order to find its gains and encoders.

On the other hand, pruning in the final operator graph would only need to be concerned with the set of operators that have side-effects during simulation, and the ways in which operators may be causally connected. In theory, this pruning should be invisible to the user (aside from changes in CPU/memory usage).

Questions:
 - Is this worth having? (Is this premature optimization?)
 - Can we ensure this is invisible to the user? (Is there some contrived way for a default ensemble to affect a custom node without actually connecting to that node?)
 - Is there a nice way to tell the user what was pruned (this may be helpful in itself for debugging other problems)?
 - Are there other side-effects during simulation that I'm not thinking about?
 - All of the above is thinking about the reference backend. How does the definition of "side-effect" change with the backend?

**Comment by tbekolay** [comment]
My thoughts:

- Probably this will not have a significant affect on sim speed, but I still feel like it's a worthwhile thing to do.
- Your set of objects with potential side-effects seems correct to me at first glance, so I think it could be made to be invisible to the user.
- Probably there are several ways; off the top of my head, we could add a `pruned` attribute to the built objects (`BuiltConnection` etc) that is set to `True` by the pruning optimizer.
- There could be side-effects if the pruning is done before building, but if we do it after build and are conservative with what we prune, I don't think there would be any side effects. Anyway, it's a somewhat straightforward thing to test, so it isn't a reason not to move forward with trying it out IMO.
- Not sure about other backends. More and more, I think that backend considerations shouldn't constrain the development of the reference simulator, unless there are strong arguments otherwise. This feels like one of those cases where if other backends can't do this, there's no harm.

**Comment by jgosmann** [comment]
> Is this worth having? (Is this premature optimization?)

The only way to know for sure is probably to implement and test it. My intuition is that it won't make a huge difference for the run time in most models, but my intuitions on these sort of things are often wrong. I would expect that the decoder solving might have a bigger impact (with very large ensembles), but would require the optimization before the builder runs.

> In particular, any objects in the operator graph that don't reach some object with side-effects may be pruned. I believe the set of objects with potential side-effects has a well-defined scope: Probe, Node with non-default output, custom neuron_type, or custom synapse.

If we do this after building, I think we have to define the set of side-effect free operators.

> There could be side-effects if the pruning is done before building

One potential side-effect is the assignment of seeds. So seeds, should be assigned before pruning.

**Comment by jgosmann** [comment]
> But, for sake of discussion, we would want to allow for the fact that custom decoder solvers may also have side-effects.

Custom operators can also have side-effects. I think either way we have to define a conservative set of side-effect free classes (i.e. a set that does not include user classes by default).

**Comment by drasmuss** [comment]
After some internal discussion, our thoughts are that this kind of optimization is beyond the scope of nengo core.  But it would make sense as part of a larger future project we have in mind to help point out common errors or opportunities for improvement in Nengo models (and I've added a link to this issue to that proposal).  So I'll close this for now, and we can track these ideas in that new project if/when it materializes.
