### ISSUE TITLE
Have an option to force the simulator to run in real time

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo#135]
For any real time control, the simulator should not run faster than real time. If for whatever reason it cannot run fast enough to be real time, it should try to be as close as possible.
Any thoughts/ideas on this? Discuss!

**Comment by tbekolay** [comment]
The consensus from the meeting yesterday was that this is a useful thing, as evidenced by the fact that [Nengo GUI now does this](https://github.com/nengo/nengo_gui/pull/661). However, it's likely not something that we would want to put directly into the reference simulator. It could go in `nengo/utilities`, but to keep things simple I'm going to put the Nengo GUI implementation in `nengo_extras` for now, and if it sees a lot of use we can migrate it to this repo in the future.

**Comment by hunse** [comment]
Done in https://github.com/nengo/nengo-extras/pull/85
