### ISSUE TITLE
Fix warnings in tests

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1378]
pytest 3.2 captures warnings in tests and displays them add the end. We should go through the list that is produced by the Nengo tests, fix relevant warnings and silence non-relevant warnings.

**Comment by tbekolay** [comment]
One difficulty here is that we capture warnings with our own things, rather than using `pytest.warns`. If we want to fix all these we'll have to switch to `pytest.warns`, but then I'm worried we'll get random test failures like we used to. Any sense of whether the new `pytest.warns` is more robust than the old one?

**Comment by drasmuss** [comment]
I've been using `pytest.warns` with `filterwarnings=always` in `nengo_dl`, and it's been robust so far ¯\_(ツ)_/¯

**Comment by tbekolay** [comment]
If anyone's looking into this, #1011 is the discussion we had about it previously (includes the test that we got random failures with). I looked into the current implementation of pytest.warns, and it doesn't look like it monkeypatches `warnings`, so I'm not confident it has fixed those issues, but we could always try it and revert if necessary...

**Comment by jgosmann** [comment]
I just did a bunch of tests with [the code posted in this comment](https://github.com/nengo/nengo/issues/1011#issuecomment-238004758). It fails for pytest 2.8.7 (reliably), but works reliably for pytest >=2.9.2. So the problem might be fixed. I'm also not sure whether our warnings catcher actually interferes with the list of warnings produced by pytest.

**Comment by jgosmann** [comment]
> I just did a bunch of tests with the code posted in this comment. It fails for pytest 2.8.7 (reliably), but works reliably for pytest >=2.9.2.

Well ... I just found out that the code works for pytest >= 2.9.2 && Python >= 3.4.6 (haven't tested earlier Python's on the 3 branch), but not if either pytest < 2.9.2 or Python <= 2.7.13. 😭 

I suppose dropping Python 2 support is not an option yet ...

**Comment by jgosmann** [comment]
fyi: I submitted a bug report upstream (pytest-dev/pytest#2917).

**Comment by jgosmann** [comment]
It seems the problem with Python 2 is solved by adding `warnings.simplefilter('always')` to `pytest_configure` in `conftest.py`.

**Comment by tbekolay** [comment]
My recollection is that we had issues even after we did that, possibly because we use `pytest-xdist` and run tests in two threads.

**Comment by tbekolay** [comment]
Yeah as long as this reliably solves the problem it sounds good to me.

**Comment by drasmuss** [comment]
When I was doing this for `nengo_dl`, setting `warnings.filterwarnings('always')` didn't work, but setting `filterwarnings = always` in the `pytest` config did.  They should in theory do the same thing, but perhaps they have some extra magic in the pytest config that handles this better.

**Comment by jgosmann** [comment]
> When I was doing this for nengo_dl, setting warnings.filterwarnings('always') didn't work, but setting filterwarnings = always in the pytest config did.

Strange, because `filterwarnings` in pytest config [seems to be set in the warnings catcher](https://github.com/pytest-dev/pytest/blob/master/_pytest/warnings.py#L61) and not globally at startup.

**Comment by jgosmann** [comment]
Bad news: The problem still persists, here is [failed Travis job for reference](https://travis-ci.org/nengo/nengo/jobs/303212857). But I'm also pretty annoyed by the warnings output and would really like to get rid of it (and it is useful to some degree as I highlighted a few potential problems).

One potential solution would be to turn off xdist on Travis-CI for Python 2.7 (Python 3 instances don't seem to be affected by the problem). Does anyone already know if this affects build times on Travis significantly? Otherwise I'll just try it out.

**Comment by tbekolay** [comment]
> Does anyone already know if this affects build times on Travis significantly?

I tested it before making the switch. I forget how much faster it was, but it was faster enough that I enabled it. Feel free to test again though, lots has changed since.

**Comment by tbekolay** [comment]
Also, if it's just a matter of long build logs, we can [disable the warning capture](https://docs.pytest.org/en/latest/warnings.html#disabling-warning-capture).

**Comment by jgosmann** [comment]
Seems like xdist does not make any difference (it seems faster without if anything):
* [with xdist](https://travis-ci.org/nengo/nengo/builds/303212838?utm_source=github_status&utm_medium=notification)
* [without xdist](https://travis-ci.org/nengo/nengo/builds/303223634?utm_source=github_status&utm_medium=notification)
