### ISSUE TITLE
Dropping support for Numpy 1.8

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1399]
Supporting Numpy 1.8 has gotten a little bit annoying recently:

- In #1398 it didn't support outer product properly.
- In #1395 it raised a ValueError when everything else raised an IndexError.

Numpy 1.8 is about a year old. The most recent version is 1.14. Is it time to drop this version? How do we usually make this decision?

**Comment by tcstewar** [comment]
A year doesn't seem enough to me -- especially when we're in the midst of running things on obscure hardware that doesn't have the latest version of things.....

**Comment by tbekolay** [comment]
I think we should keep NumPy 1.8 support for the time being, but if we run into more issues like the above we can definitely revisit.
