### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isupper'

### ISSUE THREAD

**Issue by assadRasheed** [nengo/nengo#1407]
i want to run ciphar-10 dataset but got the following error .
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-13208064d34a> in <module>()
     54     vocab = nengo.spa.Vocabulary(len(vocab_names))
     55     for name, vector in zip(vocab_names, vocab_vectors):
---> 56         vocab.add(name, vector)
     57 
     58     config = nengo.Config(nengo.Ensemble)



~\Anaconda3.0\lib\site-packages\nengo\spa\vocab.py in add(self, key, p)
    157                                     "read-only vocabulary." % key)
    158 
--> 159         if not key[0].isupper():
    160             raise SpaParseError(
    161                 "Semantic pointers must begin with a capital letter.")

AttributeError: 'int' object has no attribute 'isupper'
```

**Comment by drasmuss** [comment]
The items in your `vocab_names` list need to be strings, it looks like you have ints in there.

**Comment by jgosmann** [comment]
@assadRasheed, if you want to add further information to an issue, you can just comment on it. You don't have to open a new issue. I'm closing this one, as #1408 has more information. Also, please encode blocks of code within lines of three backticks (```` ``` ````), so they get formatted correctly. That makes it easier for us to separate out the code from other text to help out. You can even get syntax highlighting by putting the name of a programming language after the opening backticks (e.g. ```` ```python ````). [Github's markdown guide gives a good overview of all the formatting options.](https://guides.github.com/features/mastering-markdown/)
