### ISSUE TITLE
vocab.add() does not work as expected with randomize=False

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo#1412]
When setting `randomize=False` on a vocab, you would expect any new generated pointers to be orthogonal and axis aligned. This works as expected with `vocab.parse()` but not `vocab.add()`

```
import nengo.spa as spa
D=32
vocab = spa.Vocabulary(D, randomize=False)

vocab.parse('A')
vocab.add('B', D)
```

In this case `A` is the correct vector ([1,0,0...]), but 'B' is a random vector.

**Comment by jgosmann** [comment]
I think `vocab.add` should only be used to add given vectors to the vocabulary. That it works at all with a single integer seems to me to be an unintended side effect (not sure if this is worth fixing though ...). The correct way would be:
```python
vocab.add('B', vocab.create_pointer())
```

**Comment by Seanny123** [comment]
I agree with @jgosmann that doing `vocab.add('B', D)` isn't a proper use, given the documentation string:

> The pointer value can be a `.SemanticPointer` or a vector.

Consequently, it would probably be a good idea to add some type checking as is done in `nengo_spa`:
```
if not isinstance(p, pointer.SemanticPointer):
    p = pointer.SemanticPointer(p, vocab=self)
```

**Comment by jgosmann** [comment]
I'm inclined to close this issue or does anyone want to implement this in legacy SPA and wants this issue as a reminder?

**Comment by Seanny123** [comment]
I think closing it is fine. We're slowly moving away from legacy SPA anyways.
