### ISSUE TITLE
memor errors

### ISSUE THREAD

**Issue by assadRasheed** [nengo/nengo#1414]
i am trying to running one of the repository form hunse repo in which keras and nengo are used for image classification. i am using my own dataset which is composed to test and train images of jpg type and 227X227 size .the code snippets is given below. but i get the memory out of run error even i have 7 test images and 21 train images along with 6GB RAM . suggest me solution  to this problem.

```
def get_data(is_test=False):
	data_path = "train"
	if is_test:
		data_path = "test"
	return pd.read_csv('dataset,,.csv', encoding="ISO-8859-1",
				names=[','])


def loadImages(fnames,is_test=False):
	path = os.getcwd() + "/dataset/train_images/"
	if is_test:
		path = os.getcwd() + "/dataset/test_images/"
	loadedImages = []
	for image in fnames:
		tmp = Image.open(path + image)
		img = tmp.copy()
		loadedImages.append(img)
		tmp.close()
	return loadedImages


def get_pixels(fnames,is_test):
	imgs = loadImages(fnames, is_test)
	pixel_list = []
	for img in imgs:
		img = img.resize((227, 227), Image.ANTIALIAS)
		arr = np.array(img, dtype="float32")
		pixel_list.append(list(arr))
	return np.array(pixel_list)


def label_from_category(category_id=None):
	label_list = np.zeros(7)
	label_list[category_id] = 1
	return list(label_list)


def features_from_data(data, is_test=False):
	pixels = get_pixels(data.FILENAME, is_test)
	labels = np.array(data["CID"].apply(label_from_category).tolist())
	return pixels, labels



test_data = get_data(is_test=False)
X_train, Y_train = features_from_data(test_data, is_test=False)
iX_test, iY_test = features_from_data(test_data, is_test=True)

img_rows, img_cols = 227, 227

np.random.seed(5)


#X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
#X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
#(X_train, y_train), (X_test, y_test) = mnist.load_data()
#X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
#X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)

(X_train, y_train), (X_test, y_test), label_names = ((X_train, iy_train),(X_test, y_test),class_names)

X_train = X_train.reshape(X_train.shape[0], 3, img_rows, img_cols)

X_test = X_test.reshape(X_test.shape[0], 3, img_rows, img_cols)
#X_train = X_train.astype('float32')/255 - 1
#X_test = X_test.astype('float32')/255 - 1

nb_classes = len(label_names)

# --- Train model
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

nb_epoch = 2

    # number of convolutional filters to use
nb_filters = 32
    # size of pooling area for max pooling
nb_pool = 2
    # convolution kernel size
nb_conv = 3
kmodel = Sequential()
softlif_params = dict(
    sigma=0.002, amplitude=0.063, tau_rc=0.022, tau_ref=0.002)
kmodel.add(GaussianNoise(0.1, input_shape=(3,227,227)))
kmodel.add(Conv2D(32, (3, 3), input_shape=(3,227, 227), padding='valid'))
kmodel.add(Conv2D(nb_filters, (nb_conv, nb_conv), padding='valid'))
kmodel.add(SoftLIF(**softlif_params))
kmodel.add(Conv2D(nb_filters, (nb_conv, nb_conv)))
kmodel.add(SoftLIF(**softlif_params))
kmodel.add(AveragePooling2D(pool_size=(nb_pool, nb_pool)))
kmodel.add(Dropout(0.25))

kmodel.add(Flatten())
kmodel.add(Dense(128))
kmodel.add(SoftLIF(**softlif_params))
kmodel.add(Dropout(0.5))
kmodel.add(Dense(nb_classes))
kmodel.add(Activation('softmax'))

kmodel.compile(loss='categorical_crossentropy',
                   optimizer='Adam',
                   metrics=['accuracy'])



kmodel.fit(X_train, iy_train, validation_data=(X_test, y_test), epochs=3, batch_size=21)
# Final evaluation of the model
scores = kmodel.evaluate(X_test, y_test, verbose=2)
print("Accuracy: %.2f%%" % (scores[1]*100))

#kmodel.fit(X_train, y_train, epochs=nb_epoch,
               #verbose=1, validation_data=(X_test,y_test))
score = kmodel.evaluate(X_test, y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

save_model_pair(kmodel, filename, overwrite=True)
```
this is the error trace

MemoryError                               Traceback (most recent call last)
<ipython-input-12-df5ba7a082a7> in <module>()
     24 
     25 
---> 26 kmodel.fit(X_train, iy_train, validation_data=(X_test, y_test), epochs=3, batch_size=21)
     27 # Final evaluation of the model
     28 scores = kmodel.evaluate(X_test, y_test, verbose=2)

~\Anaconda3.0\lib\site-packages\keras\models.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    963                               initial_epoch=initial_epoch,
    964                               steps_per_epoch=steps_per_epoch,
--> 965                               validation_steps=validation_steps)
    966 
    967     def evaluate(self, x=None, y=None,

~\Anaconda3.0\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1644         else:
   1645             ins = x + y + sample_weights
-> 1646         self._make_train_function()
   1647         f = self.train_function
   1648 

~\Anaconda3.0\lib\site-packages\keras\engine\training.py in _make_train_function(self)
    968                     training_updates = self.optimizer.get_updates(
    969                         params=self._collected_trainable_weights,
--> 970                         loss=self.total_loss)
    971                 updates = self.updates + training_updates
    972                 # Gets loss and metrics. Updates weights at each call.

~\Anaconda3.0\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\Anaconda3.0\lib\site-packages\keras\optimizers.py in get_updates(self, loss, params)
    445 
    446         ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
--> 447         vs = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
    448         if self.amsgrad:
    449             vhats = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]

~\Anaconda3.0\lib\site-packages\keras\optimizers.py in <listcomp>(.0)
    445 
    446         ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
--> 447         vs = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
    448         if self.amsgrad:
    449             vhats = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]

~\Anaconda3.0\lib\site-packages\keras\backend\theano_backend.py in zeros(shape, dtype, name)
    300     if dtype is None:
    301         dtype = floatx()
--> 302     return variable(np.zeros(shape), dtype, name)
    303 
    304 

~\Anaconda3.0\lib\site-packages\keras\backend\theano_backend.py in variable(value, dtype, name, constraint)
    152         variable = theano.shared(value=value,
    153                                  name=_prepare_name(name, 'variable'),
--> 154                                  strict=False)
    155     variable._keras_shape = value.shape
    156     variable._uses_learning_phase = False

~\Anaconda3.0\lib\site-packages\theano\compile\sharedvalue.py in shared(value, name, strict, allow_downcast, **kwargs)
    266             try:
    267                 var = ctor(value, name=name, strict=strict,
--> 268                            allow_downcast=allow_downcast, **kwargs)
    269                 utils.add_tag_trace(var)
    270                 return var

~\Anaconda3.0\lib\site-packages\theano\tensor\sharedvar.py in tensor_constructor(value, name, strict, allow_downcast, borrow, broadcastable, target)
     52     type = TensorType(value.dtype, broadcastable=broadcastable)
     53     return TensorSharedVariable(type=type,
---> 54                                 value=np.array(value, copy=(not borrow)),
     55                                 name=name,
     56                                 strict=strict,

MemoryError: you might consider using 'theano.shared(..., borrow=True)'

**Comment by Seanny123** [comment]
This isn't a Nengo issue, but a Nengo DL question. So I'm closing this issue given you're already seeking help on the forum. (:
