### ISSUE TITLE
Correction to NeuronType.current method docstring

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1419]
Currently the `NeuronType.current` method has the docstring:

```
        Parameters
        ----------
        x : (n_neurons,) array_like
            Vector-space input.
        gain : (n_neurons,) array_like
            Gains associated with each neuron.
        bias : (n_neurons,) array_like
            Bias current associated with each neuron.
```

But the `x` parameter does not need to have the shape `(n_neurons,)`. It can be shaped as `(m, 1)`. This is how it is used by `nengo.builder.ensemble.get_activities(...)`. Not sure if there are other ways it can also be shaped.

The docstring is also missing a `Returns` section. In the case where `x.shape == (m, 1)`, the shape of the returned array is `(m, n_neurons)`.

**Comment by hunse** [comment]
Closed by #1437.
