### ISSUE TITLE
Docs are outdated?

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1446]
The latest release is 2.7, but the [documentation online](https://www.nengo.ai/nengo/index.html) still says 2.6. Not sure, if the deployment of the documentation failed or some version number hasn't been updated.

**Comment by jgosmann** [comment]
I found the build job on Travis. Apparently the notebooks are taking too long to execute?
https://travis-ci.org/nengo/nengo/jobs/350350669

In Nengo SPA I had to [explicitly install `mkl`](https://github.com/nengo/nengo-spa/commit/8ac628d2a636c75920870cf57049207e8408df49) to keep the build times low on Travis with Python 3.6. But the failed build job seems to be using MKL already (implicitly installed).

**Comment by tbekolay** [comment]
I fixed this in #1434 by adding the `-v` flag so that the docs print output more frequently. Not the best solution, but good enough for now. I'll manually build and push the docs now though, forgot to do that.

**Comment by jgosmann** [comment]
How about doing another release? That would also fix the docs and it seems we've got a decent amount of improvements.

**Comment by tbekolay** [comment]
Sold! Will do that now.
