### ISSUE TITLE
Decoder cache benchmarks results regression

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1447]
I'm not sure at which point this started, but I was going through the plots for a release and noticed that the cache benchmarks are showing that the decoder cache does not improve build times:

![d](https://user-images.githubusercontent.com/203709/41195980-3d844a5c-6c05-11e8-8a52-462bd6c0fe98.png)

![m](https://user-images.githubusercontent.com/203709/41195982-3f5192d6-6c05-11e8-88ee-f166b08f62a3.png)

![n](https://user-images.githubusercontent.com/203709/41195984-412b8350-6c05-11e8-8f07-ae3470ab05f2.png)

These plots definitely used to look different, in that they showed that the cache lowered build times significantly. I get similar (but not identical) results in both my Python 2 and Python 3 environments, so I am inclined to think that this is not due to some quirk of my environment, though it's possible.

**Comment by jgosmann** [comment]
I will investigate ... (but might not get to it before Monday)

**Comment by jgosmann** [comment]
Will this block the release? (I suppose it doesn't make a difference if this degradation wasn't introduced since the last release which is unlikely.)

**Comment by tbekolay** [comment]
Nope, not blocking the release, just noticed it during the release and didn't want to forget about it.

**Comment by jgosmann** [comment]
Did a git bisect, the first offending commit is apparently 5cdf4a7b2835a0a34a2eacab32ee63b4de031364. Though, that seems weird. Potentially I marked some commit as good/bad by mistake. I will verify this.

**Comment by jgosmann** [comment]
I verified it, it is indeed the first commit leading to the cache slow down.

**Comment by tbekolay** [comment]
That's ... surprising to say the least
