### ISSUE TITLE
Nengo node unhelpful size error message

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1452]
When you run the code:
```
import nengo

class TestNode(nengo.Node):
    def __init__(self):
        super().__init__(
            self.update,
            size_in=0,
            size_out=0)

    def update(self, t, x):
        return t / x

with nengo.Network() as model:
    nd = TestNode()

with nengo.Simulator(model) as sim:
    sim.run(sim.dt)
```

I get the following confusing error:
```
Traceback (most recent call last):
  File "nd_size.py", line 17, in <module>
    sim.run(sim.dt)
  File "/home/saubin/git/nengo/nengo/simulator.py", line 321, in run
    self.run_steps(steps, progress_bar=progress_bar)
  File "/home/saubin/git/nengo/nengo/simulator.py", line 345, in run_steps
    self.step()
  File "/home/saubin/git/nengo/nengo/simulator.py", line 356, in step
    step_fn()
  File "/home/saubin/git/nengo/nengo/builder/operator.py", line 766, in step_simpyfunc
    y = fn(t.item(), *args) if t is not None else fn(*args)
TypeError: update() missing 1 required positional argument: 'x'
```

The problem does not occur if:

1. The `super` call is replaced with `super().__init__(self.update, size_in=0)
2. If the network is not simulated

Any ideas on how we could give a better error?

**Comment by tbekolay** [comment]
Hm... I never intended Nengo objects (`Node`, `Ensemble`, `Connection`, `Probe`) to be subclassed, and I am resistant to adding anything that would make subclassing Nengo objects easier. What is the use case for subclassing the node? I would rather make that use case accessible through other means...

**Comment by Seanny123** [comment]
It was weird code from @psipeter . He was told by @tcstewar to use sub-classing.  HOWEVER, it appears to also occur without sub-classing.

```
import nengo

class TestNode(object):

    def __init__(self, bias=0):
        self.bias = bias

    def update(self, t, x):
        return t / x * self.bias

with nengo.Network() as model:
    tst_nd = TestNode()
    nd = nengo.Node(tst_nd.update, size_in=0, size_out=0)

with nengo.Simulator(model) as sim:
    sim.run(sim.dt)
```

**Comment by tbekolay** [comment]
Cool cool, thanks for the snippet :smile:  In case it's not clear, the problem is that when `size_in` is 0, the node does not receive an `x` input, so we do not pass `x` when calling the node function. It would be possible to give a better error by inspecting the node function during build time and giving a build error if the wrong arguments are expected, which seems worth doing.

If anyone's running into this right now, the fix is to give a positive `size_in`. If you have a function that can optionally accept input, write it like this:

```python
    def update(self, t, x=None):
        if x is None:
            # do stuff with x
        else:
            # do stuff without x
```

**Comment by Seanny123** [comment]
@tbekolay I was trying to check this at build time, but I'm not sure I'm doing it correctly. My plan was to [check the signature of the function](https://stackoverflow.com/q/847936/1079075) in `def coerce`. If the function takes more than one argument, but `size_in=0`, then throw an error. Is there a better way to do this?

**Comment by tbekolay** [comment]
Yeah I would definitely use `inspect.getargspec`. The case above (`def update(self, t, x=None)`) is a kind of edge case, so I'd add a test to make sure that works as it should. I was thinking of a build error, but it it works in `coerce` then that's probably better (and we already have several issues if someone were to change `size_in` after setting a bunch of other stuff on the node). So yeah, seems good :)

**Comment by jgosmann** [comment]
Note: [Use `getfullargspec` as `getargspec` is deprecated in Python 3.](https://docs.python.org/3/library/inspect.html#inspect.getargspec)
