### ISSUE TITLE
If nengo can manage infinite input data?

### ISSUE THREAD

**Issue by dongniu0927** [nengo/nengo#1455]
Hello, I'm using `nengo` to do some work with SNN. And I meet a puzzle of if `nengo` can manage infinite input data?  What I want to do is as follows:
```python
class Test():
    def run_step(self, inputs):
        spikes_probe = []
        with self._network:  # defined in class __init__
            for i, _ in enumerate(inputs):
                _input = nengo.Node(_)
                nengo.Connection(_input, self._neurons[i])  # defined in class __init__
                spikes_probe.append(nengo.Probe(self._neurons[i].neurons))
        # self._sim = nengo.Simulator(self._network)
        self._sim.run_steps(1)   # defined in class __init__
        spikes = []
        for i in range(self._neurons_num):
            probe = spikes_probe[i]
            spikes.append(self._sim.data[probe])
        return spikes
test = Test()
# every time i call the following function, hope nengo to foward a step
test. run_step([1, 2, 3, 4])
```
But i find it didn't work if i don't rebuild `self._sim`, but i hope to continuously call `run_step` and not rebuild network.
Hope to find a solution, thanks!

**Comment by dongniu0927** [comment]
Or say if i can use external input in lambda part? Every step, a new external input will send to the lambda part, and run a `sim.run_steps(1)`, then get probe response.
```python
u = nengo.Node(lambda t: np.sin(2 * np.pi * t))
ens = nengo.Ensemble(10, dimensions=1, neuron_type=nengo.Izhikevich())
nengo.Connection(u, ens)
```

**Comment by Seanny123** [comment]
Hello! This might be more on-topic for the forum. Additionally, there appears to be [a prior question](https://forum.nengo.ai/t/using-nengo-in-agent-based-modeling/266/9?u=seanny123) which might be of interest with to you.

**Comment by dongniu0927** [comment]
@Seanny123 Thanks that really helps me!
