### ISSUE TITLE
Windows cache permission error

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1456]
I keep getting this cache error on Windows 10. I don't know if this has been addressed before and if this would be resolved by deleting the cache files.

```
Traceback (most recent call last):
  File ".\experiments\run_conf.py", line 180, in <module>
    integ_res = run_integ(list(c_res)[10:125], init_seed, pos_adjust=min_foil_comp - .05)
  File ".\experiments\run_conf.py", line 106, in run_integ
    with nengo.Simulator(model, progress_bar=False) as sim:
  File "c:\users\mr_bo\git\nengo\nengo\simulator.py", line 160, in __init__
    progress=pt.next_stage("Building", "Build"))
  File "c:\users\mr_bo\git\nengo\nengo\builder\builder.py", line 123, in build
    built = self.builder.build(self, obj, *args, **kwargs)
  File "c:\users\mr_bo\git\nengo\nengo\builder\builder.py", line 218, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "c:\users\mr_bo\git\nengo\nengo\builder\network.py", line 120, in build_network
    model.decoder_cache.shrink()
  File "c:\users\mr_bo\git\nengo\nengo\cache.py", line 619, in shrink
    self.remove_file(path)
  File "c:\users\mr_bo\git\nengo\nengo\cache.py", line 369, in __exit__
    self.sync()
  File "c:\users\mr_bo\git\nengo\nengo\cache.py", line 444, in sync
    self._write_index()
  File "c:\users\mr_bo\git\nengo\nengo\cache.py", line 401, in _write_index
    replace(self.index_path + '.part', self.index_path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\mr_bo\\.nengo\\cache\\decoders\\index.part' -> 'C:\\Users\\mr_bo\\.nengo\\cache\\decoders\\index'
```

**Comment by jgosmann** [comment]
Does `'C:\\Users\\mr_bo\\.nengo\\cache\\decoders\\index'` exist?

**Comment by jgosmann** [comment]
Are you running multiple simulations (or builds to be precise) concurrently?

**Comment by Seanny123** [comment]
Yes, `'C:\\Users\\mr_bo\\.nengo\\cache\\decoders\\index'` exists, but I'm not running multiple simulations concurrently. I am running a bunch of tiny simulations in series, however.

**Comment by jgosmann** [comment]
I assume after you closed all Nengo processes, the same file with the `.part` extension also still exists? Can you manually do the move on the command line (I believe `move` is the command on Windows?)?

I think you are using Python 3?

Does either deleting the index or index.part or both files fix it?

**Comment by jgosmann** [comment]
Are you having an antivirus running?

**Comment by arvoelke** [comment]
> Are you having an antivirus running?

Linking #1200 for sake of information. Those were fun times.

**Comment by jgosmann** [comment]
@Seanny123 I noticed I'm still assigned to this ticket and was wondering whether it can be closed?

**Comment by Seanny123** [comment]
Gimme some time to test this on my computer again. It's been awhile since I've used Nengo.

**Comment by jgosmann** [comment]
@Seanny123 ping

**Comment by Seanny123** [comment]
Closing this issue, since I haven't been able to reproduce it.
