### ISSUE TITLE
Notice: Purging old branches January 1st

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo#1485]
On January 1st 2019 we will be deleting any branches that don't have an open PR and haven't been updated since January 1st 2017.

You can see a list of old branches [here](https://github.com/nengo/nengo/branches/stale).

If you have an old branch that you would like to be preserved, either 1) open a PR for that branch or 2) push an update to that branch.

**Comment by hunse** [comment]
I cleaned up (i.e. deleted) a few, but still have some more to do. Can we have a reminder a few weeks before we do this? Also, maybe not on Jan 1st, but rather Jan 14 or something so I have some time after Christmas holidays to deal with this.

**Comment by drasmuss** [comment]
Sure, we can do it on January 14th.

**Comment by arvoelke** [comment]
Could we fork the repo right beforehand to have all the old branches still be accessible somewhere (just in case)? If not I'll be doing that at https://github.com/arvoelke/nengo for my own historical records / etc.

**Comment by tbekolay** [comment]
Our goal in removing them is to prune away things we're not using and would be confusing for someone to happen upon (since it will be a bit of work to get these old branches rebased to more recent versions of Nengo), so making another repo (in the Nengo organization) would go against that goal. You're free to have a fork of the repo with those old branches if you like.

**Comment by arvoelke** [comment]
Yeah that makes sense. I just realized I have some (very) old reports and such that rely on these branches, and like you said, some of them would be hard to get working with the most recent version of Nengo, so it's ideal to have them sync'd up with the point they worked. It's partly my bad for using that as storage and assuming it would be there forever, but branches are cheap, and so are forks -- so no problem-o!

**Comment by tbekolay** [comment]
We ... got a bit sidetracked. This will now actually be happening this coming Monday, September 30, 2019.

**Comment by tbekolay** [comment]
This is now done :+1:
