### ISSUE TITLE
Progress_bar Error when running nengo.Simulator in jupyter lab with Chrome

### ISSUE THREAD

**Issue by fmirus** [nengo/nengo#1499]
whenever I instantiate a simulator with 
```
sim = nengo.Simulator(model)
```
or run a simulation with
```
sim.run(T)
```
from within a jupyter-notebook in chrome instead of getting the progress-bar, I get the following error message:
```
Javascript Error: Cannot read property 'getElementsByClassName' of null
```
The simulation runs fine, there just is no progress-bar. I don't get this error message, when I disable the progress-bar via
```
sim = nengo.Simulator(model, progress_bar=False)
```
I'm using nengo version '2.8.1.dev0' (current master-branch), Google Chrome version 71.0.3578.98, jupyter veriosn 4.3.0 and openjdk version "1.8.0_191" on Ubuntu 16.04.

**Comment by jgosmann** [comment]
I currently cannot reproduce the problem.

What is the output of `jupyter notebook --version`?

Are any additional errors or more detailed error information printed in the console when you open the Developer Tools in Chrome?

**Comment by fmirus** [comment]
oops, sorry. I mixed that up. I meant jupyter lab. For jupyter-notebook, I just noticed that I do not get this error neither. My jupyter lab version is 0.35.4

**Comment by jgosmann** [comment]
I could verify the problem. A workaround for now (despite disabling the progress bar) would be:
```python
from nengo.utils.progress import VdomProgressBar
with nengo.Simulator(model, progress_bar=VdomProgressBar()) as sim:
    # ...
```

### Further details on problem

There are two implementations of the progress bar for Jupyter: `HtmlProgressBar` and `VdomProgressBar`. `VdomProgressBar` is the preferred implementation. Unfortunately, Jupyter Notebook does not yet support the virtual DOM and thus cannot use `VdomProgressBar`, instead an alternative implementation (the `HtmlProgressBar`) has to be used. This alternative implementation requires to run JavaScript for updating, but the notebook runner Jupyter Lab disallows the execution of JavaScript. Thus we end up with the following situation:

Implementation | Notebook | Lab
---------------|-----------|-----
`HtmlProgressBar` | + | -
`VdomProgressBar` | - | +

Furthermore, there is no reliable way to detect whether the notebook is executed in Jupyter Lab or Jupyter Notebook (actually the code runs in a kernel that could be accessed by Lab and Notebook at the same time). Thus, the current implementation uses `IPython5ProgressBar` which sends the data for both progress bar implementations to the frontend with the idea the frontend will pick the preferred version (notebook uses HTML as it does not know vDOM, lab should prefer vDOM). Unfortunately, it seems that in some recent Jupyter lab version things were changed to prefer HTML over vDOM.

The notebook runner of Jupyter Lab disallows JavaScript. However, the `HtmlProgressBar

**Comment by jgosmann** [comment]
Actually, it turns out that Jupyter Lab is now allowing JavaScript execution. That should make it possible to fix this relatively straight-forward.
