### ISSUE TITLE
Add Python versions badge to pypi/readme?

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1516]
Following [what pytest-xdist does](https://pypi.org/project/pytest-xdist/) I think it would look nice to include a badge of Python versions. This is what ours looks like at the moment, and would appear both on PyPi and on the GitHub README:

https://img.shields.io/pypi/pyversions/nengo.svg
![https://pypi.python.org/pypi/nengo](https://img.shields.io/pypi/pyversions/nengo.svg)

Reference:
 - https://raw.githubusercontent.com/pytest-dev/pytest-xdist/master/README.rst

**Comment by hunse** [comment]
One downside to this is that it's based on the latest released version, not the development version. So even though we support Python 3.8, it doesn't show yet. We'll be doing a release soon enough, though.
