### ISSUE TITLE
ValidationError: State.dimensions: Dimensions (28) must be divisible by subdimensions (16)

### ISSUE THREAD

**Issue by assadRasheed** [nengo/nengo#1528]
i have dataset which is 32 x32 x1 and 28 classes . error trace is shown below . i tried differnet values for subdimension from 1 to 28 but not work . dont know why this is appearing. need your suggestions 
```
<ipython-input-46-3ff14949bbb4> in <module>
     29     with config:
     30         output = nengo.spa.State(
---> 31             len(vocab_names), vocab=vocab)
     32     nengo.Connection(knet.output, output.input)
     33 

~\Anaconda2\lib\site-packages\nengo\spa\state.py in __init__(self, dimensions, subdimensions, neurons_per_dimension, feedback, feedback_synapse, vocab, label, seed, add_to_container)
     66             raise ValidationError(
     67                 "Dimensions (%d) must be divisible by subdimensions (%d)"
---> 68                 % (dimensions, subdimensions), attr='dimensions', obj=self)
     69 
     70         with self:

ValidationError: State.dimensions: Dimensions (28) must be divisible by subdimensions (16)

```
and by change different values 

ValidationError: Connection.function: function output size is incorrect; should return a vector of size 28

**Comment by tcstewar** [comment]
Hmm, that should work with subdimensions=28.  What error do you get when you try that?

**Comment by assadRasheed** [comment]
ValidationError: Connection.function: function output size is incorrect; should return a vector of size 28

**Comment by assadRasheed** [comment]
i changes the class numbers  and take start from 0 instead of 1

**Comment by drasmuss** [comment]
Sorry for the delay @assadRasheed, it looks like this issue got lost in the shuffle (@tcstewar has been working on other projects lately). Are you still having this issue, or did you resolve it?
