### ISSUE TITLE
Some solvers compute only a single RMSE

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1539]
**Describe the bug**

Every solver returns a `solver_info['rmses']` (note: plural) which is expected to be the RMSE for each target (the number of post neurons for `weights=True`, or the number of dimensions for `weights=False`). However, some solvers (notably the most common ones) only return a single overall RMSE, and this can differ depending on whether `weights=True` or `weights=False`.

**To reproduce**

```python
import nengo
import numpy as np

def trial(solver, seed=0, n_pre=50, n_post=100, dim_post=1):

    with nengo.Network(seed=seed) as model:
        x = nengo.Ensemble(n_pre, 1)
        y = nengo.Ensemble(n_post, dim_post)
        conn = nengo.Connection(x, y[0], solver=solver)

    with nengo.Simulator(model, progress_bar=None) as sim:
        pass
    
    return(sim.data[conn].solver_info['rmses'].shape)

for cls in (nengo.solvers.Lstsq,
            nengo.solvers.LstsqNoise,
            nengo.solvers.LstsqMultNoise,
            nengo.solvers.LstsqL2,
            nengo.solvers.LstsqL2nz,
            nengo.solvers.LstsqL1,
            nengo.solvers.LstsqDrop,
            nengo.solvers.Nnls,
            nengo.solvers.NnlsL2,
            nengo.solvers.NnlsL2nz):
    print(cls.__name__, "W", trial(cls(weights=True)))
    print(cls.__name__, "D", trial(cls(weights=False), dim_post=2))
```

```
Lstsq W (1,)
Lstsq D (1,)
LstsqNoise W (1,)
LstsqNoise D (1,)
LstsqMultNoise W (1,)
LstsqMultNoise D (1,)
LstsqL2 W (1,)
LstsqL2 D (1,)
LstsqL2nz W (1,)
LstsqL2nz D (1,)
LstsqL1 W (100,)
LstsqL1 D (1,)
LstsqDrop W (100,)
LstsqDrop D (1,)
Nnls W (100,)
Nnls D (1,)
NnlsL2 W (100,)
NnlsL2 D (1,)
NnlsL2nz W (100,)
NnlsL2nz D (1,)
```

**Expected behavior**

Two ways this could be made consistent. 

1. The `rmses` are always across flattened arrays, in which case all of the shapes should be `(1,)`, and `rmses` (plural) should be renamed to `rmse` (singular).

2. Report the RMSE for each target, in which case the expected output is:
```
Lstsq W (100,)
Lstsq D (2,)
LstsqNoise W (100,)
LstsqNoise D (2,)
LstsqMultNoise W (100,)
LstsqMultNoise D (2,)
LstsqL2 W (100,)
LstsqL2 D (2,)
LstsqL2nz W (100,)
LstsqL2nz D (2,)
LstsqL1 W (100,)
LstsqL1 D (2,)
LstsqDrop W (100,)
LstsqDrop D (2,)
Nnls W (100,)
Nnls D (2,)
NnlsL2 W (100,)
NnlsL2 D (2,)
NnlsL2nz W (100,)
NnlsL2nz D (2,)
``` 

**Error message and logs**

NA

**Versions**

 - OS: NA
 - Python: NA
 - Nengo: latest master
 - Other: NA

**Additional context**

NA

**Comment by hunse** [comment]
I think it's not that they're returning a single RMSE, it's that some of the weight solvers are returning RMSEs in the number of post dimensions, instead of the number of post neurons. (Note that in your code above, you're connecting to `y[0]` which is always 1-D, which is why you get 1-D RMSEs even when you switch `dim_post` to 2.)

This problem with weight solvers is an artifact of how we do many weight solvers. For solvers like `LstsqL2`, the weights are actually just the decoders times the encoders, so when `weights=True` we compute the decoders as usual and multiply by the encoders. We're obviously computing the RMSEs before we multiply by encoders, when we should be doing it after.

**Comment by arvoelke** [comment]
> so when `weights=True` we compute the decoders as usual and multiply by the encoders. 

I thought this changed in #1507, so that the encoders are applied to the targets before calling out to the solver? The script in this issue actually produces different results prior to that PR (e.g., `v2.8.0`) versus master. On 2.8.0 the `Lstsq` solver has `rmses` with a shape of `(100,)` for `weights=True`. The rest is the same.

As an aside: the change is good IMO because it means solvers like `LstsqL2` will now actually use the extra degrees of freedom and produce a weight matrix that isn't necessarily low-rank. For reference, @astoeckel showed in [a recent paper](https://arxiv.org/abs/1710.07659), and in [nengo-bio](https://pypi.org/project/nengo-bio/), that it gets even better if you relax the optimization problem to avoid needing to fit the magnitude of the negative currents (i.e., so long as the neuron doesn't spike, it's the same effect).

**Comment by arvoelke** [comment]
Right, so I wasn't properly up-to-date with the `compositional` versus `non-compositional` solvers added recently in #1507. With this, I think the output is actually as expected, because the `compositional` solvers are always solving for one target, which has the encoders or transform applied to it to become either `100` or `2` dimensional. In this way it makes sense for the solvers to be reporting the RMSEs that they do. I pushed #1540 which I think fixes a changelog entry that fuelled some misunderstanding on my part.
