### ISSUE TITLE
Why was the all_solvers extra removed silently?

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1544]
**Describe the bug**

The `all_solvers` extra was removed silently in 0c0166ad75edc667e6244fd6be366929065f192b.

ctn-archive/cue-model relies on it to ensure the dependencies SciPy and scikit-learn are installed.

**Comment by tbekolay** [comment]
The `"optional"` option is used instead to be consistent with other Nengo projects.

I would recommend that papers like ctn-archive/cue-model install a specific version of Nengo core to ensure that the option will always exist (e.g. `pip install "nengo==2.8.0[all_solvers]"`)

**Comment by jgosmann** [comment]
Ok, seems reasonable, but another reason to me why https://www.nengo.ai/governance.html shouldn't advertise that Semantic Versioning is used.

**Comment by tbekolay** [comment]
> another reason to me why https://www.nengo.ai/governance.html shouldn't advertise that Semantic Versioning is used.

You consider an optional installation flag to be part of the public API?

**Comment by jgosmann** [comment]
At least part of the API that is relevant to Semantic Versioning. The whole point is that things should not break if the version range of a dependency is limited to a fixed major version and minimum minor version.
