### ISSUE TITLE
Consider making parameter system a separate package

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1558]
The `param` system is pretty big/complex and not really "Nengo code" if you know what I mean. We could split it off into a separate package, and in that package implement some tools to document parameters that are also attributes, automatically adding them to the attribute and parameter lists of the docstring.

We should also consider looking at similar projects out there, most notably https://github.com/ipython/traitlets, which does something very similar, to see where the important differences are and whether those differences are important enough to warrant continuing to write our own parameter system.

**Comment by drasmuss** [comment]
Conclusion from discussion: we're not averse to doing this, but we probably wouldn't do it unless we have some motivating work in the future that was touching the param system.
