### ISSUE TITLE
Allow transform=None on Connections to indicate no weights

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo#1580]
**Is your feature request related to a problem? Please describe.**

Often in models we want to transfer information from one component to another without applying any transformation (e.g., connecting an input `Node` up to something else, or using passthrough nodes on Networks, or when using a connection Probe). Right now those connections all get built with `transform=1`, which adds an unnecessary weight multiplication to all those connections. Even though the multiplication itself is trivial, depending on the backend there can be a certain amount of overhead associated with any operation like that, which can add up.

This also makes a difference in NengoDL, where all those `transform=1` connections are actually trainable parameters. This is often unexpected for users, since they haven't explicitly opted in to creating a transform on the Connection.

**Describe the solution you'd like**

Allow Connections to be created with `transform=None`. This would be functionally the same as `transform=1`, but it wouldn't create the weights or add the weight multiplication operations to the graph.

A further consideration would be whether we want to change the default from `transform=1` to `transform=None`. I think that'd make sense (it seems like a straightforward improvement, with no functional change). The only case where it would make a difference is in something like NengoDL, where we'd be removing trainable parameters as mentioned above. But in my experience, we don't want those trainable parameters most of the time (in fact I often have to work around them by setting those parameters to be non-trainable), so I think that would be an improvement.

**Describe alternatives you've considered**

We could also have a special `transform=nengo.Null()` transform type (in the style of `Dense` or `Convolution`). But since `transform=None` isn't being used for anything else, it seems like a natural syntax for what we want here.

**Comment by tbekolay** [comment]
This sounds great to me, and I like changing the default to `None` as well. :+1:

**Comment by tbekolay** [comment]
Done in #1591.
