### ISSUE TITLE
Nengo and  OpenMP

### ISSUE THREAD

**Issue by Ad-An** [nengo/nengo#1586]
I am reading a comparison of spiking neural networks simulation libraries in order to choose the one to use and one of the criteria that this comparison mentions is OpenMP.

I am trying to decide between Nengo, PyNEST and BindsNET and althought the last two fully support it, Nengo only partially does.

From my research I have taking a liking to Nengo both due to its community and to its features but I have to ask. Given that this feature is one of the main points of the comparison, what are the consequences of Nengo only partially supporting OpenMP? Also why the support is only partial? 

[Source](https://www.frontiersin.org/articles/10.3389/fninf.2018.00089/full), page 4

**Comment by drasmuss** [comment]
> Given that this feature is one of the main points of the comparison, what are the consequences of Nengo only partially supporting OpenMP?

To be honest, I'm not sure why that table includes support for OpenMP as a main comparison point.  OpenMP is just one tool that can be used to write efficient, parallelized neural simulators.  There are all kinds of other options out there for writing efficient neural simulators (e.g. OpenCL, CUDA, OpenMPI).  What the user probably cares about is whether their neural simulator runs quickly; how that is implemented under the hood won't matter to most people. The only situation where it would matter is if you had a computing platform that _only_ supported OpenMP (not OpenCL or CUDA or any of the other options).  In that case, you would want to make sure that the neural simulator supported OpenMP.  But I am not aware of any computing platforms that exclusively support OpenMP.

> Also why the support is only partial?

We're not the authors of that paper, so we can't say for sure, but I'm not sure what they mean by saying that Nengo has partial support for OpenMP.  Perhaps they are referring to the [nengo-mpi project](https://github.com/nengo/nengo-mpi)? Although OpenMPI is not the same as OpenMP.  But Nengo has lots of support for fast, efficient neural simulation (see [nengo-dl](https://github.com/nengo/nengo-dl), which uses TensorFlow/CUDA, or [nengo-ocl](https://github.com/nengo/nengo-ocl), which uses OpenCL). Assuming that you don't require OpenMP in particular, we'd encourage you to compare different SNN architectures in terms of their user-facing performance (e.g. speed on some common benchmark); whether or not they use OpenMP under the hood will probably not make any difference to you. And we're pretty sure that Nengo will be fastest in that comparison 😄.

**Comment by Ad-An** [comment]
Thank you very much for the detailed answer.
