### ISSUE TITLE
Nengo 3.0.0 incompatibility with deprecated time.clock() in Python 3.8

### ISSUE THREAD

**Issue by dw2wrigh** [nengo/nengo#1593]
**Describe the bug**

Running Nengo works in Python 3.7 but fails with Python 3.8

>    File
> "d:\users\dw2wrigh\gitlocal\snn\venv\lib\site-packages\nengo\utils\stdlib.py", line 283, in Timer
> 
>      TIMER = time.clock if sys.platform == "win32" else time.time
> 

Some searching reveals:

> The function |time.clock()| has been removed, after having been deprecated since Python 3.3: use 
>  |time.perf_counter()| or
>  |time.process_time()| instead, depending on your requirements, to have well-defined behavior. > (Contributed by Matthias Bussonnier in bpo-36895 <https://bugs.python.org/issue36895>.)

**To reproduce**

Try running Nengo with Python 3.8

**Versions**

 - OS: Windows 10
 - Python: Python 3.8
 - Nengo: 3.0.0

**Additional context**

I had this same problem with PyQt5

**Comment by drasmuss** [comment]
This was fixed in https://github.com/nengo/nengo/pull/1628
