### ISSUE TITLE
Run nengo

### ISSUE THREAD

**Issue by mickahell** [nengo/nengo#1595]
After installing nengo on Ubuntu 18 (bionic) follow the basic [documentation](https://www.nengo.ai/getting-started/).
The nengo comand stay not found.

**Comment by tbekolay** [comment]
Can you copy/paste the terminal output that resulted from your `pip install` command? Just to be sure that the installation completed successfully.

If it did complete successfully, then the most likely issue is that the path in which pip installs scripts is not in your path. I believe that usually that path should be `$HOME/.local/bin`. Can you copy/paste the results of `echo $PATH` in the terminal?

If `$HOME/.local/bin` isn't in there you can add it with `PATH="$HOME/.local/bin:$PATH"`. To make that change permanent, add

```
export PATH="$HOME/.local/bin:$PATH"
```

in your `.bashrc` or `.profile`.

**Comment by mickahell** [comment]
Hi @tbekolay indeed i don't know why I didn't think about that thanks ;)

**Comment by tbekolay** [comment]
I'm hoping that means you got it working, in which case I'll close this issue. If not, please reopen. I'd also encourage you to check out the [Nengo forum](https://forum.nengo.ai/) and post any questions you might have there!
