### ISSUE TITLE
Decoder cache gives deprecation warning

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1624]
**Describe the bug**

Having the decoder cache enabled results in a senseless deprecation warning. This is because `check_attrs` in `cache.py` loops over all the attributes of an object; when it touches `step_math` (a property) on `NeuronType`, this results in the warning.

I think the easiest solution is to revert  `step_math` back to being a function with the same signature of `step`, that just calls out to `step`. 

**To reproduce**

A minimal code snippet to reproduce the behavior:

```python
import nengo
nengo.rc.set("decoder_cache", "enabled", "True")

with nengo.Network(seed=0) as net:
    a = nengo.Ensemble(100, 1)
    ap = nengo.Probe(a)

with nengo.Simulator(net, progress_bar=False) as sim:
    sim.run(1.0)
```

**Expected behavior**

No warning

**Error message and logs**

```
/data/eric/workspace/nengo/nengo/neurons.py:101: UserWarning: 'step_math' has been renamed to 'step'. This alias will be removed in Nengo 4.0
```

**Versions**

 - Nengo: latest master

**Comment by tbekolay** [comment]
> I think the easiest solution is to revert `step_math` back to being a function with the same signature of `step`, that just calls out to `step`.

I'd rather manually skip `step_math` in `check_attrs`, as the point of the user warning is so that users will get the message if they manually call `step_math` and have time to switch before we remove it. We already skip attributes that start with `_` so it'd just be another case in that list comprehension statement.
