### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock' on Windows

### ISSUE THREAD

**Issue by KevlarTheGreat** [nengo/nengo#1647]
**Describe the bug**

Cannot launch "nengo"
This bug is only on Windows and is due to trying to use the deprecated time.clock on python 3.8.3
Run "nango" in a conda virtual environment and you get  this error.  AttributeError: module 'time' has no attribute 'clock'
This is caused by this line:
File "c:\users\brian\appdata\local\continuum\anaconda3\envs\nengo\lib\site-packages\nengo\utils\stdlib.py", line 283, in Timer
    TIMER = time.clock if sys.platform == "win32" else time.time
Changing this line to the following appears to fix the problem, but I'm not 100% certain if perf_counter gives the correct functionality or not.
    TIMER = time.perf_counter if sys.platform == "win32" else time.time

**To reproduce**

1. Install the latest Anaconda and conda update.
2.  Create a new virtual environment and activate it
3. Install nengo and nengo gui using PIP
4. Attempt to launch by typing "nengo"
5. The error above appears in the console and nengo gui never launches

**Expected behavior**

nengo gui should launch in browser but instead an error occurs

**Versions**

 - OS: Windows 10
 - Browser: chrome
 - Nengo GUI: 0.4.6
 - Nengo:  3.0.0
 - Other: Python 3.8.3

**Additional context**
Running in conda virtual env, but I don't think it matters.

**Comment by tbekolay** [comment]
Hi @KevlarTheGreat! We implemented Python 3.8 support in #1628. It is currently part of the master branch, so you can do a [developer installation](https://www.nengo.ai/nengo/contributing.html#developer-installation) to use Nengo with Python 3.8 right now. We will be making a release relatively soon (within a few weeks) if you prefer to wait.

Thanks for the bug report!
