### ISSUE TITLE
Dualism module

### ISSUE THREAD

**Issue by atait** [nengo/nengo#1674]
**Concise problem:** 
Backend creation is reactive; there is always a lag between new hardware and Nengo support. A dualism module would be a more generalized API for accommodating backends posited by some researchers.

**Context:**
Neural simulation has progressed from CPUs to post-von Neumann (i.e. GPUs) to post-digital to post-CMOS hardware, and Nengo has backends for each of these. The rise of post-classical, quantum hardware poses a question to Nengo as a unifier of backends, "does the strategy generalize to hardware governed by other physical theories?" I think there is potential for Nengo to generalize this trend to post-classical hardware and perhaps to [post-Hobbes architectures](https://xstack.sandia.gov/hobbes/about.html), [post-quantum coding](https://pqsoc.com/faq/), and post-physics hardware that has not been fully worked out yet. 

**Detailed description:**
A dualism module would essentially consist of API changes that interface with arbitrary, non-introspectable plugins (i.e. backend drivers for new hardware). These backends might be proprietary, and they might not exist yet; however, this hardware is imaginable and therefore possible. Right now, it seems to make sense to future-proof Nengo by opening up an API for them. Basically, Nengo would run exactly the same way, but, at the same time, depend entirely on the non-introspectable codebase.

**Further impacts:**
A dualism module has particular bearing on SPAUN. [SPAUN 2.0](https://github.com/xchoo/spaun2.0) is clearly holding "propositional states" (e.g. the character being presented is “4”); however, it can’t really point to a bit 1/0 or python object that corresponds to having that propositional state. SPAUN’s objective as a hypothesis testing tool is limited in this regard because it must depend on the experimenter’s intuitive interpretation/theoretical framework that the floating point values underlying SPAUN somehow represent that state. One of the major possibilities enabled by a dualism module would be a SPAUN 3.0 capable of holding these states as first-class (post-python) objects independent of interpretation and theory.

**Estimated time:**
- lengthy

**Comment by atait** [comment]
To clarify this feature, dualism is an idea asserting that the mind in not entirely physical, that you need some kind of metaphysically distinct, non-physical substance to have conscious experience. This is definitely not supportable by Nengo, engineering, or any kind of computer rooted in our observable universe.

Happy April Fools

This philosophical feature had some reason and some nonsense. It probably wasted some time – I apologize for that! I hope this post-mortem will clear up the lines between reason and nonsense and perhaps inspire some google searches. 

**“This hardware is imaginable and therefore possible”**
The first complete proposal of dualism is credited to René Descartes. This statement is something you might see from Descartes (He’s the one known for, “Je pense, donc je suis.”). It is a true statement; however, it is ambiguous about which type of possible we’re talking about. Things like werewolves can both exist in logic and not exist in the physical world. 

Computers employing a non-physical substance cannot exist in the natural, physical world, almost by definition. Even dualists who believed this supernatural substance exists generally give some special status to human brains over any mechanistic process that we could build. That means the notion that “some researchers” have actually postulated dualistic hardware backends is nonsense.

**"post-Hobbes architectures"**
Thomas Hobbes did crucial groundwork for some more recent theories of mind, conceiving of mental states as processes, rather than just substances. He even drew parallels between mental processes and mechanistic processes. From *Leviathan*: “For what is the heart but a spring; and the nerves but so many strings, and the joints but so many wheels…” Springs were the cutting-edge hardware of Hobbes’ time, *Leviathan* predating Hookes’ Law by 20 years.

Coincidentally, the Dept. of Energy decided to name one of their computing projects “Hobbes” (the link). I have no idea what “post-Hobbes” computing would be besides deeply contradictory.

**“non-introspectable”** 
Introspection in coding means examining classes, variable names, and sometimes the source. To protect intellectual property, some proprietary code does not allow introspection, “closed-source.” Interfaces between closed-source software and open-source software, such as Nengo, can be complicated technically and legally. These are real questions, but it’s pretty ridiculous to propose a major strategic shift (general support of closed-source backends) in a simple feature request.

For dualism modules, “non-introspectable” would have a much stronger meaning. Introspection is observation. It would be inconsistent to observe “code” existing outside of observable reality.

**“Nengo would run exactly the same way, but, at the same time, depend entirely on the non-introspectable codebase”**
Determinism is a conundrum for dualism, which can lead to paradoxes like this one. In other words, if physical events are caused entirely by preceding physical causes – including the execution of machine code – then there’s no room for the metaphysical to affect the physical. Then again, if a being with dualistic consciousness has a physically identical counterpart without consciousness, it seems like they should behave differently.

Aside: Some have thought that quantum randomness opens up this path for something metaphysical to exert effect on the physical; we just don’t understand how yet. Perhaps quantum computing is relevant after all… Amazingly, that idea is testable, and it has been refuted by three independent experiments in 2015 (see papers with key words “loophole-free” and “local realism”). 

**“the experimenter’s theoretical framework”**
Materialism, in opposition to dualism, rejects an unfathomable, non-physical mind substance, so it must explain the relation between mental states and physical states (voltages, chemical concentrations, bit values, etc.). Of course, neuroscience is very far away from a theory encompassing those relations. It should exist, perhaps as a reduction mapping metal states to physical states, or perhaps as an elimination of mental states as illusion that exist only upon interpretation.

Propositional attitudes, such as “that character is ‘4’,” are examples of mental states, convenient because there is a binary of whether a brain holds them as true or false. One hypothesis is 1-to-1 neuron-to-attitude mapping (or bit-to-attitude mapping in my case). Even with 80 billion+ neurons, there are far too many concepts for there to be a, “that character is ‘4’”-neuron and a “Jane used to take a class on ancient history, and she was usually more prepared than John was”-neuron. 

That 1-to-1 mapping can be hypothesized and can be – like any good hypothesis – tested and refuted. I just made an anatomy/reason argument (80 billion neurons) against it. You can also use experiments: poking and prodding brains, timing mice in mazes, biologically realistic simulation, or functionally abstracted simulations like SPAUN.

** “SPAUN’s objective” **
I want to be really careful to not misrepresent the objectives SPAUN research, especially because it is not my work. First off, I’m almost certain it is not meant to be a tester for theories of mind. It can test hypotheses about many other kinds of brain function, and it has an advantage of being embedded in a simulated environment. While an experimenter can try to interpret their higher-level network states, embedded simulations do not require any of this interpretation to give behavioral data. In that regard, I will say that, SPAUN is intriguingly compatible with eliminativist materialism. My claim that SPAUN is limited by not first-classing mental states is pure nonsense by any account of materialism.

Also, post-python is nonsense. That would probably just be called python 4 or quantum python.

**Comment by drasmuss** [comment]
I'll admit I was thoroughly bamboozled 😂

**Comment by tbekolay** [comment]
I originally read this issue as "dualsim" and was like "two simulators, what is Alex up to this time, better wait until Monday to read this in detail" :joy:

**Comment by atait** [comment]
Alright then I think this can be closed on account of dependency conflict with the laws of nature 😁
