### ISSUE TITLE
How to sign in in forum.nengo.ai ?

### ISSUE THREAD

**Issue by giamp66** [nengo/nengo#1695]
I'm sorry but I'm unable how to sign in Nengo forum. It's seems that the forum had been massively spam. Is it functioning? Thank you very much.

**Comment by tbekolay** [comment]
Hi @giamp66, yes there's been a huge influx of spam to the forum so I've locked new user signups for now while I clean up the spam. If you already have an account on the forum you should be able to login and use it; if not, please let me or @tcstewar know your email address and we can manually invite you to the forum.

**Comment by tbekolay** [comment]
All the spam on the forum should be gone now. If anyone else needs to sign up, please let me know and I can invite you.
