### ISSUE TITLE
Clean up notebooks

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#171]
Clean up the ipython notebooks.

- [x] Pick a standard for inlining matplotlib, as discussed in #167, and make sure all notebooks follow this standard.
- [x] Remove unnecessary output in notebooks, especially objects that are returned from creation routines (e.g. `<Node at @42890f23>` and stuff like that). These can be suppressed by either ensuring that the object is assigned to a value, or putting a semicolon after the last line of the block (which is the line that is outputting something).
- [x] Decide on a standard for strings versus objects. I know this is controversial, so maybe all notebooks don't need to be the same, but it's especially annoying when 1) the same notebook uses strings and objects, and not out of necessity, and 2) a notebook creates objects at the beginning of the notebook, but then never uses them and just uses strings. I personally think it would be best to use objects throughout all the notebooks, but barring that, fixing the two annoyances I just mentioned would be a good start, so at least each notebook is consistent in and of itself.
- [x] Hide large blocks of code that are pedagogically distracting. This could include large blocks of plotting code, particularly when the focus of the notebook is not on how to use nengo, but is teaching an NEF concept. It could also include setup code, again especially when the focus is on something other than using nengo. Code related to model creation should NOT be hidden (though there may be exceptions, perhaps probes sometimes). To hide things, import `nengo.ipython` and call `nengo.ipython.hide_input()` at the end of every input block you wish to hide.
- [ ] Standardize all plots to have proper (standard) labels on all axes, ensure that the time axis is in seconds (and not steps), and overall just make the plots consistent. It might help to add some plotting routines to `nengo/matplotlib.py` that standardize this.
- [x] When you're finished with a notebook and ready to save, make sure that you restart the kernel, do `Cell -> Run all`, save the notebook, and don't do anything else. This will make sure that the input cell numbers start at 1.
- [x] Clean up the examples folder, removing empty notebooks and unnecessary .py files. There are some empty notebooks that we meant to fill in, but haven't yet. We copied a lot of the .py files straight from old Nengo. Rather than having all these files around, we should just refer to issue #53, which lists all the finished and unfinished notebooks. The .py files from old Nengo don't need to live here; people can just refer back to old Nengo if they need to when writing examples.
- [x] Add links to compiled notebooks on nbviewer.ipython.org from the README
- [x] Make semantic pointers use ALL CAPS. For example, `vocab.parse('DOG * CAT')` rather than `vocab.parse('Dog * Cat')` (this seemed to be the consensus, right?). Also, make sure the term "semantic pointer" is always written in lower case (i.e. not "Semantic Pointer").
- [x] Anything else people can think of.

**Comment by jgosmann** [comment]
I noticed that at least one example uses all caps for semantic pointers, whereas I only capitalized the first letter in PR #605. Should we standardize this to one variant?

**Comment by hunse** [comment]
Which example?

The book does all lowercase ("semantic pointer"), which is what seems most natural to me, as well. While it is a special term, I don't think it needs capitals (we're not German, after all :wink:).

**Comment by tcstewar** [comment]
> I noticed that at least one example uses all caps for semantic pointers, whereas I only capitalized the first letter in PR #605. Should we standardize this to one variant?

Hmm, good question.  In papers, I always do all caps (DOG*SUBJ+CHASE*VERB+CAT*OBJ).  Implementation-wise, the current spa.Vocabulary system requires semantic pointers to be a) valid python identifiers (basically, no spaces or punctuation and they can't start with a number) and b) to start with a capital letter.  I didn't set it up to enforce that they have to be all-caps, because that seemed overkill.  The intent was to make it very easy to distinguish semantic pointers from references to buffers (so in ```DOG+visual``` we know that DOG is a semantic pointer and visual is whatever semantic pointer is currently being stored in the visual buffer).  Those buffers are lowercase by convention (since they are python variable names), and I'd been doing all-caps for semantic pointers in papers, and I'm used to all-caps for constants, so that felt right to me.

In anycase, I'd vote for standardizing to allcaps in examples.  :)

**Comment by jgosmann** [comment]
Compare `question_control.ipynb` and `question_memory.ipynb`.

I'd vote for only capitalizing the first letter as it is more readable.

**Comment by tcstewar** [comment]
> Compare question_control.ipynb and question_memory.ipynb.
> 
> I'd vote for only capitalizing the first letter as it is more readable.

I'm totally the wrong person to judge on that one -- looking at those examples I find the allcaps one to be hugely more readable.  :)

**Comment by hunse** [comment]
Haha, I totally misunderstood the question. I thought you meant the term "semantic pointer", which is currently sometimes written "Semantic Pointer" and sometimes "semantic pointer". I prefer the latter, and that's what's in the book.

As for the actual variables, how do we (or others) typically do this in papers? I'm more used to seeing all capitals I think, but that's probably because that's what @tcstewar prefers.

**Comment by pblouw** [comment]
I'd vote for all caps, mostly because it makes it easier distinguish
references to modules from SP labels.

**Comment by jgosmann** [comment]
Another reason why I do not prefer all caps: It's annoying to type.

**Comment by tcstewar** [comment]
> As for the actual variables, how do we (or others) typically do this in papers?

All the examples I can find are either all-caps or using a bold font (sometimes with a horizontal line above the word, indicating it's a vector).  I haven't found any examples with a single capital at the beginning.

> Another reason why I do not prefer all caps: It's annoying to type.

Hmm, never found it that way myself...  then again, I'm used to it.

**Comment by jgosmann** [comment]
I think, the examples I wrote are not merged into master yet. See PR #605.

>> Another reason why I do not prefer all caps: It's annoying to type.

> Hmm, never found it that way myself... then again, I'm used to it.

But you have to either hold shift all the time (and often switch between both shift keys with touch typing) or activate/deactivate caps lock before and after each SP.

**Comment by tcstewar** [comment]
Sorry, I wasn't clear.  When I said "All the examples I can find are either all-caps or using a bold font (sometimes with a horizontal line above the word, indicating it's a vector). I haven't found any examples with a single capital at the beginning." I was responding to @hunse 's comment asking "As for the actual variables, how do we (or others) typically do this in papers?".  So I meant that all the examples of talking about semantic pointers I can find in our papers and in other people's papers are in all-caps.  I'm pretty sure it's also that way in Chris' book.

**Comment by Seanny123** [comment]
In terms of matplotlib built-in functions, I would be inclined  `similarity` plot function for SPA plots as the current syntax is a little clunky. I could even stretch my belief to accept that a function that only needs a probe name and a simulator to be passed in (time range is assumed to be the full range, label of data is assumed to be probe label) might be useful. So something like: `nengo_plot(sim, probe_name, time_range=None, label=None)` This would save having to type `sim.trange()` and `sim.data[]` all the time.

Do people think this is too much hand-holding?

**Comment by studywolf** [comment]
hmm, what i like about forcing people to use ```sim.trange()``` and ```sim.data[]``` is that now they have access to everything they need to go off and make their own crazy complex plots and we're not responsible for it.

**Comment by Seanny123** [comment]
Yeah I wouldn't include it in the tutorials or any sort of introduction, if anything `nengo_plot` would cause learned helplessness with the noobs. I was thinking for quick debugging, but even then you really just end up using the Nengo GUI. I think I've convinced myself that the programming and support required for that idea isn't worth the trouble.

**Comment by tbekolay** [comment]
We discussed this issue at the dev meeting; in general, I think the notebooks are pretty good at this point... and I'm pretty opposed to adding too much to `nengo.utils.matplotlib` as I also like forcing people to use `trange` and `data` and doing the plotting however they like it. @hunse is there anything remaining for this issue that we should still be aware of? If not, please close it; if there are some additional things can you briefly summarize? Thanks!

**Comment by hunse** [comment]
I think this is okay.

The one thing that remains unchecked is fixing up the axes. For the most part they're okay. Quite a few are missing a label for the x-axis (typically time), but I think it's usually fairly clear that this is time in seconds. Anyway, not a big deal.
