### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#175]
To do:

- [ ] Issues in [2.0.0 milestone](https://github.com/ctn-waterloo/nengo-temp/issues?milestone=4&state=open) -- fix issues, merge pull requests, or add comment to the issue / PR that it will happen after release
- [x] Refactor builder into submodule

----

#### Notes

- http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/
- http://docs.openstack.org/developer/pbr/
- http://zestreleaser.readthedocs.org/en/latest/
- http://opensourcehacker.com/2012/08/14/high-quality-automated-package-releases-for-python-with-zest-releaser/
- http://blog.ziade.org/2013/04/13/declaring-dependencies-in-python/
- http://blog.ionelmc.ro/2014/05/25/python-packaging/

**Comment by tbekolay** [comment]
Done!

**Comment by hunse** [comment]
:fireworks:

**Comment by tcstewar** [comment]
Wow.  Huge congrats, everyone.  That is absolutely amazing.  :)

**Comment by jgosmann** [comment]
:cake: :cake: :fork_and_knife: :yum:
