### ISSUE TITLE
Nengo style guide? 

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo#231]
So, PEP8 is cool, and I spend way too much time thinking about the prettiest way to build my scripts and I was wondering if anyone had any specific ways of organizing theirs that worked particularly well. 

There's a bunch of aspects; one is where to define inputs, ensembles, connections, probes, etc, I've tried defining all ensembles and then all connections or connections as soon as the relevant ensembles are created and have found functional grouping more clear than strict separation into Nodes, Ensembles, Connections, Probes. 

Other things like I've played around with spacing connection calls 
```
nengo.Connect(pre_ensemble,
              post_ensemble,
              parameters)
```
before and I found that to help with readability.

Anyways it's kind of a silly topic and I'm not suggesting that we try to enforce anything, I was more just curious if anyone had any things like the connect layout above that they found really helped with readability. Maybe something could be developed from discussion that would suggest a clean way for people to build scripts.

**Comment by tbekolay** [comment]
We discussed this at the dev meeting; there is now a [style guide](http://pythonhosted.org/nengo/contributing.html#code-style) in the docs, and it would be great if people added some Nengo-specific things there!

For long lines, here are a few rough guidelines that I find I ahere to, which anyone can feel free to steal if they want to (but probably aren't important enough to codify or check for):

1.   Line break at the first open bracket.

     ```python
     # too long
     nengo.Connection(pre, post, function=lambda x: (x[0] * x[1] + x[2] * x[3]) ** x[4])
     # OK!
     nengo.Connection(
         pre, post, function=lambda x: (x[0] * x[1] + x[2] * x[3]) ** x[4])
     ```

2.   Line break before each *keyword* argument.

     ```python
     # too long
     nengo.Connection(pre, post, synapse=nengo.Lowpass(0.02), function=lambda x: (x[0] * x[1] + x[2] * x[3]) ** x[4])
     # still too long
     nengo.Connection(
         pre, post, synapse=nengo.Lowpass(0.02), function=lambda x: (x[0] * x[1] + x[2] * x[3]) ** x[4])
     # OK!
     nengo.Connection(pre, post,
                      synapse=nengo.Lowpass(0.02),
                      function=lambda x: (x[0] * x[1] + x[2] * x[3]) ** x[4])
     ```

     This one's especially nice for connections, as then pre and post stay on the same line.

3.   Line breaks *everywhere*, and use keyword arguments even if you don't need to.

     ```python
     # too long
     nengo.Ensemble(10, dimensions=1, max_rates=nengo.dists.Uniform(100, 200), intercepts=nengo.dists.Uniform(-0.5, 0.5), n_eval_points=5000)
     # not too long, but looks kind of bad to me (unbalanced?)
     nengo.Ensemble(10,
                    dimensions=1,
                    max_rates=nengo.dists.Uniform(100, 200),
                    intercepts=nengo.dists.Uniform(-0.5, 0.5),
                    n_eval_points=5000)
     # OK!
     nengo.Ensemble(
         n_neurons=10,
         dimensions=1,
         max_rates=nengo.dists.Uniform(100, 200),
         intercepts=nengo.dists.Uniform(-0.5, 0.5),
         n_eval_points=5000
     )
     ```

     This preference might be too much exposure to JavaScript, but I like how this is explicit and spread out, which makes it easy to read and easy to edit.

     I'm not a fan of the following:

     ```python
     nengo.Ensemble(
         n_neurons=10,
         dimensions=1,
         max_rates=nengo.dists.Uniform(100, 200),
         intercepts=nengo.dists.Uniform(-0.5, 0.5),
         n_eval_points=5000)
     ```

     Probably just me, but yeah, having that closing bracket on a new line makes me happy.

I can't think of situations other than when lines go longer than 80 characters that PEP8 is insufficient... but if anyone else comes up with any, feel free to comment on this post (even though it's closed) and we can workshop opinions ;)
