### ISSUE TITLE
probes & timing

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo#234]
I'm trying to get NengoOCL working again, and running into some time-related troubles, which has happened a few times before. Rather than simply follow nengo's lead once again, I'd like to ask if there is a "right answer" for how to handle times, and probes. Here is a proposal:

1. `sim.trange` returns a sequence of numbers like `np.arange`, in that it starts at 0, and steps by dt.
2. If you call sim.trange before sim.step(), you get a sequence of length 1, namely [0].
3. If you ask for probe data before the first call to sim.step(), you get the initial conditions (matching t==0) of your simulation. This will be true for all probes, regardless of `sample_every` because the semantics of sample_every is to take a sample whenever the time matches some multiple (here 0) of the sampling period.
4. If you call `step()` N times, then `trange` returns a sequence `[0, dt, 2 * dt, 3 * dt, ..., N * dt]` of length N + 1, and correspondingly, you get N + 1 samples from the probes if you ask for probe data.
5. `sim.signals['__time__']` should match the last element of trange. At first it is 0, and after calling step N times, then it has value `N * dt`.
6. So far this has all been about the Simulator's interface to the modeler: trange, signals, probe data. There is also the related questions of what time's should the simulator pass to Python Nodes. A Node should expect to see, on step `t`, a value for time which equals `trange[t]`.  So on the first call, t==0, on the second one, t==dt, and so on.
7. When a Node has input other than t, what value does it get? I propose that it gets the same value for other inputs as would be recorded by a probe of those other inputs with `filter = None`.
8. What value should Probes actually see on the t'th step? They should record the "read"-phase Signal value. (See justification in [1] below).

To further explain points 6 and 7, here's what I mean in the context of a small model:
```python
m = Model()
with m:
    a = Node(lambda t: t)
    b = Node(lambda t, t1: (t, t1), dimensions=1)
    Connection(a, b, filter=None)
    pa = Probe(a, 'output', filter=None)
    pb = Probe(b, 'output', filter=None)
sim = Simulator(m)
sim.run_steps(3)
```

After this code runs, we should have:

* `sim.trange() == [0, 0.001, 0.002, 0.003]` because of points 1, 2, and 4.
* `sim.probe(pa) == [0, 0, 0.001, 0.002] `. Why? Although Node `a` computed `0, .001, .002, .003` as per point 7, Nodes currently "update" their outputs so they write their outputs *after* probes have read them (as per point 8) on a given time-step. The sequence [0, 0, .001, .002] is what is seen by node b.
* `sim.probe(pb) == [(0,0), (0, 0), (.001, 0), (.002, .001)]` Because without filtering it should take one time-step for a signal to get from `a` to `b`.

Relative to this I think Nengo currently drops the last trange element, and drops the first probe element. The `__time__` is one step ahead of `trange()[-1]`. I suspect the handling of timing between nodes and probes is also slightly different in off-by-one-or-two sorts of ways.

I would like for there to be a Right Answer in this because there are a few tests where it looks like dts are added somewhat arbitrarily here and there to check for a match between what the reference simulator produces and what numpy produces. It would be nice for both modeling and implementing a backend to have a clear idea of the number of time-steps of lag between e.g. one node's output and another node's input, or a probe.

[1] Re: probes reading "read"-phase values, this is pretty arbitrary, and I can see various backends making different choices here, but for expediency's sake I suggest going with the "read" value for the Signal in the simulator. Another option would be the value of the buffer after the step() call, but I think that is less useful. Technically that can be implemented via the `sim.signals` API but more importantly, storing the "read"-phase value of each Signal helps debugging by telling you what all of the other operators "read" for that Signal on a time-step.

**Comment by hunse** [comment]
In my experience, these issues are resolved, and we've implemented most if not all of the suggestions here.

**Comment by tbekolay** [comment]
Except for documenting a lot of this, but we have that listed in #625.
