### ISSUE TITLE
NEF/SPA  Tips, Tricks, Deep Magic

### ISSUE THREAD

**Issue by e2crawfo** [nengo/nengo#340]
In lab meeting today we talked about creating some kind of repository of miscellaneous tricks / deep magic related to the NEF, to avoid the situation where person Y has a great solution to some problem person X is struggling with, only X has no way of knowing that. Eg setting radii for sub-ensembles of an Ensemble Array appropriately.

Not a pressing issue, can probably wait till after the sprint, but it'd be pretty handy. One  question is whether it should go in the Nengo docs, the CNRG website, or maybe just in the CNRG Google Docs folder?

**Comment by Seanny123** [comment]
Do the [`nengo_examples`](https://github.com/nengo/nengo_examples) and [`nengo_extras`](https://github.com/nengo/nengo_extras) repositories resolve this issue?

**Comment by Seanny123** [comment]
We concluded during the meeting today that this desire is now satisfied by `nengo_extras`, `nengo_examples` and the tech report repository.
