### ISSUE TITLE
Connect to a connection instead of modulatory=True

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#366]
@hunse suggested this in the learning PR:

> `error_conn = nengo.Connection(error, A_squared, modulatory=True)`
> 
> Could we instead write `error_conn = nengo.Connection(error, conn)`?

Since connections weren't an object in Nengo 1.4, it never occurred to me that this could be possible, but it is possible and perhaps is better syntax for what we do now with `modulatory=True`. I think so far we've never used a modulatory connection for anything but learning; are there other use cases for this?

**Comment by hunse** [comment]
This is changed in #642. Error signals now connect into the learning rule, for example

    conn = nengo.Connection(pre, post, learning_rule_type=nengo.PES())
    nengo.Connection(error, conn.learning_rule)
