### ISSUE TITLE
Access to probe data without finishing simulation 

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo#384]
So any time I'm doing learning stuff (all the time) I basically run my simulation for some time and then when it does something weird I stop it. The probes are pretty much useless for this situation and so I'm writing my own nodes that record data to a list or a file and then analysing it. It would be cool for this to be a situation that Nengo has a way to help out with.
 
----

@tbekolay commented on May 21:

In what way would you want Nengo to help out?

One thing you can do that Nengo already lets you do is control the simulation yourself:

```python
while sim_not_weird(sim):
    sim.run(1.0)

def sim_not_weird(sim):
    return np.all(sim.data[some_probe] < 20)
```

----

@hunse commented on May 21:

You could use the visualizer...

----

@hunse commented on May 21:

To me, this is a node-like function, so I think we should continue doing it with nodes. We could add some helper functions for creating such nodes, if there are common tasks. For example, we could have a function that makes a node record and plot its inputs and call `plt.draw()`, so that you can get an actively updating plot without using the visualizer.

That said, such a plot would be almost exactly like what the visualizer does, so it might make sense to take the visualizer code for each different type of plot and put it in utils somewhere, so that this code can be used for both nodes and for the visualizer.

----

@tcstewar commented on May 21:

For a quick thing doing this with nodes, here's a miniature gui I tossed together for the neurogrid people

https://github.com/ctn-waterloo/nef-chip-hardware/blob/master/examples/minigui.py

you use it like this:

```python
model = nengo.Network()
with model:
    input = nengo.Node(lambda t: np.sin(6*t)*0.5)
    a = nengo.Ensemble(neurons=100, dimensions=1, label='a')
    b = nengo.Ensemble(neurons=99, dimensions=1, label='b')
    nengo.Connection(input, a, synapse=0.01)
    nengo.Connection(a, b, synapse=0.01)

import minigui
gui = minigui.GUI(model)
gui.show(a)
gui.show(b)
gui.start()   # starts a separate thread that runs an updating matplotlib display

sim = nengo.Simulator(model)
sim.run(100)
```
It's pretty barebones, but something like this might be useful...

**Comment by tbekolay** [comment]
Now that we have a full GUI, I think this issue can be closed. For reference, #737 and https://github.com/nengo/enhancement_proposals/pull/5 track other related issues.
