### ISSUE TITLE
being able to output matrices instead of only vectors

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo#388]
It would be nice to be able to have my python function outputs be matrices, instead of having to flatten the output and then reshape it at the beginning of the next function. I remember trevor talking about this earlier, I think.

tbekolay commented on May 7
I've totes talked about this. I think it's a good idea. One discussion point: does this apply to nodes and ensembles? The changes, I think, would be:

```
Ensemble.dimensions -> Ensemble.shape
Node.size_in -> Node.shape_in
Node.size_out -> Node.shape_out
```

My main concern is: how much of a mess does this make the transform? Is it even possible for a human to specify a transform if we're dealing with ndarrays everywhere?

drasmuss commented on May 7
I can see how this works with Node, but this seems like it would be a bit complicated if you apply it to Ensembles. What would your encoders/decoders look like? I guess you would just use vectors and handle the flattening on input/output internally within the Ensemble? It seems like it will be hard to make that transparent to the user. I guess we won't know until we try, but my guess would be that the user is always going to have to keep in mind that that flattening is going on, in which case all we're really doing is saving them one numpy command. But it would be cool if you could get it to work transparently somehow.

tcstewar commented on May 7
Hmm... I think the simplicity of everything just being vectors is worth the overhead of forcing people to manually reshape things.

**Comment by tbekolay** [comment]
We discussed this at the last dev meeting and decided it's not something we're going to do in the foreseeable future. I formalized that decision at https://github.com/nengo/enhancement_proposals/pull/7. Feel free to discuss more there if this makes you sad! We will do our best to make you less sad.
