### ISSUE TITLE
connection size with transform indexing and function doesn't work

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo#389]
```python
import numpy as np
import nengo
nengo.log()

m = nengo.Network(seed=10)

with m: 

    input1 = nengo.Node(output=[1, 1])  
    a1 = nengo.Ensemble(100, dimensions=2)

    nengo.Connection(input1[0], a1,
                     function=lambda x: [np.cos(x), np.cos(x)])    

sim = nengo.Simulator(m)
sim.run(.1)
```

gives the error

```
ValueError: Node output size (1) not equal to Ensemble input size (2)
```

Thought it might be a node thing, but this also gives the error:

```python
import numpy as np
import nengo
nengo.log()

m = nengo.Network(seed=10)

with m: 

    a1 = nengo.Ensemble(100, dimensions=2)
    b1 = nengo.Ensemble(100, dimensions=3)

    nengo.Connection(b1[0], a1,
                     function=lambda x: [np.cos(x), np.cos(x)])    

sim = nengo.Simulator(m)
sim.run(.1)
```

looks like there's some interplay between slicing and functions that's not playing nice. The `in_dims` for the pre pop says it's 6d in `required_transform_shape`.

----

@hunse commented on May 6:

For some reason, the slice is assumed to happen after the function calculation. I think this is just a mistake.

----

@arvoelke commented on May 6:

Well this is because the slicing semantics only affect the transform, which happens after the function. To handle this case, I think we'd have to either rewrite the given function automatically, or change the evaluation points, which is different semantically.

We could just make this clearer by giving good documentation of what slicing does, since users will need a good understanding of the function-before-transform concept.

Edit: After a bit of thought, I think the current semantics are a bit wrong, in the sense that the function's output dimension is assumed to equal the input dimension. It will take some thought to get this right though. We should probably have the pre slice be before the function, but implementing this is non-trivial (see second sentence).

----

@hunse commented on May 6:

Yeah, that's true, it is non-trivial. I hadn't thought about what it would mean (in the builder) to have slicing before the function, but I agree that that's the way it should be.

I suggest that this issue be moved to the main nengo repo as a wishlist issue. In the mean time, to improve the error message, I think that we should disallow pre-slices on connections with functions.

----

@arvoelke commented on May 6: 

I agree. :+1:

----
 
@arvoelke commented on May 13:

So I've been thinking about this a bit more. It seems to open the can of worms: should we also make the given encoders and eval_points be in terms of the sliced dimensions? I would think so.

I'm also thinking that in order to address this accurately, the unsliced dimensions of the generated pre encoders should be automatically set to zero. Otherwise, it will be difficult to get it accurate if you, say, slice one dimension out of 500. But this is problematic in that Connections shouldn't be affecting any pre ensemble attributes... So do we just have to rely on the eval points being well distributed about the unsliced dimensions?

---- 

@arvoelke commented on May 13:

Okay, talking with @studywolf again helped clear things up. We're thinking it would be most sensible to:

Leave the encoders unchanged and promote awareness that slicing doesn't magically ignore the encoding done by the pre-ensemble on the unwanted dimensions.
If eval points are given in the ensemble, then the unneeded components are thrown away before invoking the given function, but used to solve for the decoders.
If eval points are given in the connection, then randomly distribute the unsliced components and do the above (**).
If no eval points are given, then randomly distribute them in the full dimension and do the above.
In effect, all this does is treat the given function as one which ignores the unwanted components. I'll give a go at this.

(**) Is maybe debatable. Because perhaps the user knows something about the distribution of the unsliced components. But maybe then they should be specifying them in the Ensemble...?

**Comment by jgosmann** [comment]
Original example works for me now.
