### ISSUE TITLE
Document Built* named tuples

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#491]
The builder stores some information about the built model `sim` in `sim.model.params` with named tuples like `BuiltEnsemble`. I think, it should be documented that this information can be queried and what the tuple attributes store. In most cases it is pretty clear from the name (e.g. `encoders`), but some attributes might need some precise explenation (I'm adding such an attribute in my `spaopt-v2` branch).

I'm creating this ticket also because I'm not sure how to add documentation for named tuples.

**Comment by tbekolay** [comment]
Part of this issue depends on a more general builder refactoring, which is in the works, but these `Built*` classes are now [documented](https://github.com/nengo/nengo/blob/master/nengo/builder/ensemble.py#L23), as of 2.1.0 perhaps? I did it at some point!
