### ISSUE TITLE
Numpy dependency install fails if not already installed

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#508]
I tried to install Nengo in a virtualenv without installing NumPy beforehand. The Nengo seemed to try to install NumPy, but failed with some compile error. Installing NumPy with pip first and then Nengo worked.

I have to look further into what exactly the error was etc. but don't have time right now. So this ticket is for now just a reminder for me.

**Comment by swedishhh** [comment]
tbekolay commented on 29 Nov 2014

Thank you!
