### ISSUE TITLE
Make the SPA unit tests reliable

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#512]
Currently, a lot of the SPA unit tests break easily (e.g. [working memory](https://github.com/ctn-waterloo/nengo-temp/pull/511#issuecomment-60163535), [thalamus](https://github.com/ctn-waterloo/nengo-temp/issues/432#issuecomment-48526038)) from changes which should improve the network. This defeats the purpose of the unit tests as they do not tell whether the code is working or not and one needs quite some background knowledge to evaluate whether they fail because something is not working or because the tests need an adjustment.

Each test should define somehow a bound on the permitted error and any improvement in accuracy should leave the tests passing. I assume figuring out how to determine that error in each case is the major difficulty.

It would be cool if those error values would be saved for every commit, so that we can track improvements and regressions.

**Comment by tbekolay** [comment]
Closing this as new SPA development is happening in https://github.com/nengo/nengo_spa.
