### ISSUE TITLE
Implement fast Poisson disc sampling

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#519]
I just stumbled over an alternate algorithm for generating eval_points (or any of our other uniform sampling values).  It's a way of generating random sample points while guaranteeing a minimum distance between them.  This gets rid of the "clumpy-ness" that we see in uniform sampling.
- Info: http://www.jasondavies.com/poisson-disc/
- Paper with algorithm doing this in n-dimensions:  http://www.cs.ubc.ca/~rbridson/docs/bridson-siggraph07-poissondisk.pdf
- Pretty visualizations and comparisons:   http://bost.ocks.org/mike/algorithms/

**Comment by tbekolay** [comment]
Since an implementation of this will likely live in `nengo_extras` until it's been benchmarked and used for a while, I've moved this discussion to https://github.com/nengo/nengo_extras/issues/30.
