### ISSUE TITLE
ErrorLearningFunction (Plasticity Rules)

### ISSUE THREAD

**Issue by Vafa-Andalibi** [nengo/nengo#538]
Hello, 

In the document entitled "Using and extending plasticity rules in Nengo", it is written that the only non-abstract real learning function implemented so far is "ErrorLearningFunction (ca.nengo.plasticity.impl.ErrorLearningFunction)". However, I cannot find neither the corresponding file nor the "AbstractRealLearningFunction" file in nengo folder. Are these files, by any chance, available somewhere to download? 

With Best Regards, 

Edit: Same goes for InSpikeErrorFunction, OutSpikeErrorFunction and AbstractSpikeLearningFunction

**Comment by tbekolay** [comment]
This issue's a few years old now, so I'm going to close it. The learning examples I linked above can now be found at http://pythonhosted.org/nengo/examples.html#learning. Hopefully they're straightforward, but if now, we now have a forum at https://forum.nengo.ai/ where we would be happy to answer any other questions you have @Vafa-Andalibi!
