### ISSUE TITLE
Make connections determine `synapse` based off of `pre` and `post`

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#546]
As discussed during the meeting when I talked about using pass-through nodes as a way to replace `addDecodedTermination()` from Nengo 1.4.

Apparently, if I don't specify `synapse=None` there will actually be a filter applied to the signal. This surprised me and it was determined during the meeting that this "surprise" was not necessary nor desirable.

Suggested behaviour during the meeting:
- If node to node connection or if a node to ensemble connection default to `synapse=None`
- If ensemble to node connection, keep the default behaviour

I'm not totally clear on what `synapse` does, so I'd like some people to clarify for me what behaviour we should code in. Once the spec is written up, I have no problems implementing it since the `connection` code seems pretty straight-forward.

**Comment by tbekolay** [comment]
At yesterday's dev meeting we decided not to have pre/post-dependent synapse defaults. A few reasons were discussed, which are now summarized (and formally documented) at https://github.com/nengo/enhancement_proposals/pull/8.
