### ISSUE TITLE
Add Nengo paper benchmarks

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#551]
Back when we wrote the Nengo/Nengo OCL paper, we had a number of nice benchmarks to test backends on (there was circular convolution, a Lorenz attractor, a communication channel, and maybe some others). Now that we have a `benchmarks` folder, we should find these, tidy them up, and put them there.

**Comment by jgosmann** [comment]
> Now that we have a benchmarks folder, we should find these, tidy them up, and put them there.

I don't think we have that folder anymore, do we?

I'll have to implement some of those benchmarks soon, so I could as well resolve this issue if I know where to put that stuff.

**Comment by tbekolay** [comment]
> I don't think we have that folder anymore, do we?

We do not, as the `analytics` and `compare` fixtures kind of obsoleted it... So I suppose benchmarks could go in whatever file makes sense, or a `test_benchmarks.py` if they're general. Or they could be in a separate `nengo_benchmarks` repo, not sure I have a strong preference right now...

**Comment by jgosmann** [comment]
Do we actually want to have these in core Nengo? Or might `ctn_benchmarks` be a better place (given that @tcstewar wants to split it into a pure benchmark package and a “PyTry” package for running trials)?

**Comment by tbekolay** [comment]
According to @tcstewar, these benchmarks are already implemented in PyTry / ctn_benchmarks (or are easy to implement), so the plan is to add them to this new repo: https://github.com/nengo/nengo_benchmarks
