### ISSUE TITLE
Passing in a list to add_output of network arrays

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo#562]
It would be cool to be able to pass in a list of functions to the network array, so that a bunch of different signals could be calculated and accessed from the same output connection. 

This came up because I wanted something like `output = (x[0] + constant_i) * x[1])` where `constant_i` is different for each population `i`, but I could also see doing things like `output = [x[0]*x[1], x[0]**2*x[1],...]` or whatever. Might be nice!

**Comment by tbekolay** [comment]
Done in #580.
