### ISSUE TITLE
Scaling of evaluation points

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#564]
(not sure if this has been discussed before)

It would be convenient to be able to pass a distribution to the `eval_points` argument of `Ensemble` and `Connection`. But it would make the Nengo code a bit more complicated (but also the user's code less complicated).

My use case right now is to improve the accuracy of a multiplication with a specifically manufactured distribution of evaluation points. But it should be noted that the improvements are not enormous. At most I get an improvement of the RMSE of 16% (all other parameters except radius with their defaults), but with diagonal encoders it's just 3%. Changing the distribution of evaluation points might also improve the approximation of other non-linear functions. But so far I don't have data on that.

**Comment by tbekolay** [comment]
Everything in this thread is addressed now, I think, except for @jgosmann's third suggestion: "Implement boolean parameter to disable scaling." It would be an easy thing to implement, but it would add another parameter to both Ensemble and Connection. Is this heavily sought after, or can it wait?

**Comment by jgosmann** [comment]
I think, it can wait. Maybe we should think about a way to cut down constructor parameters at some point ...

**Comment by jgosmann** [comment]
Just came across this issue again and I don't think we need a parameter to disable scaling. It is a pretty rare use case and there are viable workarounds. So I'm closing this and if we can create a new issue if this should come up again.
