### ISSUE TITLE
Ensemble eval_points vs n_eval_points docstring

### ISSUE THREAD

**Issue by fragapanagos** [nengo/nengo#573]
The current docstring for Ensemble's `eval_points` is incorrect with respect to passing in an int.

    eval_points : ndarray (n_eval_points, `dimensions`) or int, optional
        The evaluation points used for decoder solving, spanning the interval
        (-radius, radius) in each dimension. If an int is provided, this
        sets the number of evaluation points to be drawn from a hypersphere.
        If None, then a heuristic is used to determine the number of
        evaluation points.

Attempting to pass in an int for `eval_points` raises a validation error (says a 2D ndarray is expected). To specify the number of evaluation points, the user passes in an int for the `n_eval_points` parameter. The docstring does not mention `n_eval_points` as a parameter and looks like it just needs updating.

**Comment by tbekolay** [comment]
Done in #371.
