### ISSUE TITLE
Potential cache performance regression

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#576]
I'm under the impression that the build performance suffered with PR #558. This might depend on the number of items in the cache. It might only be a problem on traditional HDD.

Maybe it's just my computer that has issues.

**Comment by jgosmann** [comment]
The faster cache has been merged, should we close this issue?

**Comment by Seanny123** [comment]
Did you end up addressing @drasmuss's concerns in your cache heuristic? If not, maybe close this issue and open a different one?

**Comment by jgosmann** [comment]
We're not using a heuristic ... it's difficult to find a good one because it is quite system dependent. It's also difficult to come up with a universal benchmark.
I've run a few benchmarking trials with the improved cache and it seems the situations where cache hits are slower than no cache seem to be quite rare now. The only combination I've found is around 150 neurons and 5 dimensions in one ensemble. But feel free to run your own benchmarks (you can use `test_cache.py` as a template).

Cache misses are more expensive than no cache, but this will always be the case and that's the trade off you pay for faster repeated builds.

**Comment by Seanny123** [comment]
If we've decided to not use a heuristic, then I would say you could close the issue. If someone creates a more critical benchmark, they can open up a new issue.

**Comment by jgosmann** [comment]
I suppose, that's what I decided for now. Also this issue was about something else originally.
