### ISSUE TITLE
Generate Poisson or regular spikes from a rate model

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#579]
This was briefly discussed in #533. The basic idea is to make a neuron model that takes in a rate based neuron model, and produces a spiking approximation of that firing rate by generating spikes at regular intervals, or from a Poisson process.

**Comment by tcstewar** [comment]
I took a stab at doing this with Nodes in the past, so these functions might be useful:

Regular spiking (i.e. given a constant rate, this will produce regularly spaced spikes):

```python
class RegularSpiking(object):
    def __init__(self, size, dt=0.001):
        self.state = np.zeros(size)
        self.threshold = 1.0 / dt
        self.output = np.zeros(size)
    def __call__(self, t, x):
        self.output[:] = 0
        self.state += x
        spikes = np.where(self.state > self.threshold)
        self.output[spikes] = self.threshold
        self.state -= self.output
        return self.output
```

Poisson spiking:

```python
class PoissonSpiking(object):
    def __init__(self, size, seed, dt=0.001):
        self.rng = np.random.RandomState(seed=seed)
        self.dt = dt
        self.value = 1.0 / dt
        self.size = size
        self.output = np.zeros(size)
    def __call__(self, t, x):
        self.output[:] = 0
        p = 1.0 - np.exp(-x*self.dt)
        self.output[p>self.rng.rand(self.size)] = self.value
        return self.output
```

Neither of these do any sanity-checking on their inputs.  Negative inputs will do weird things to RegularSpiking (it should probably not allow ```state``` to go below zero).

I've got a notebook where I use these to convert rates into spikes:

https://github.com/tcstewar/testing_notebooks/blob/master/spike%20trains%20-%20poisson%20and%20regular.ipynb

![image](https://cloud.githubusercontent.com/assets/2380772/20292040/6eb0f0d6-aab8-11e6-83fe-557f5f05ef39.png)

**Comment by tcstewar** [comment]
Here's a much more accurate poisson spike generator

```python
class PoissonSpikingExact(object):
    def __init__(self, size, seed, dt=0.001):
        self.rng = np.random.RandomState(seed=seed)
        self.dt = dt
        self.value = 1.0 / dt
        self.size = size
        self.output = np.zeros(size)
    def next_spike_times(self, rate):        
        return -np.log(1.0-self.rng.rand(len(rate))) / rate
    def __call__(self, t, x):
        self.output[:] = 0
        
        next_spikes = self.next_spike_times(x)
        s = np.where(next_spikes<self.dt)[0]
        count = len(s)
        self.output[s] += self.value
        while count > 0:
            next_spikes[s] += self.next_spike_times(x[s])
            s2 = np.where(next_spikes[s]<self.dt)[0]
            count = len(s2)
            s = s[s2]
            self.output[s] += self.value
                
        return self.output
```

How much more accurate is it, you ask?

![image](https://cloud.githubusercontent.com/assets/2380772/20294483/741be2d8-aacc-11e6-92dc-cd04573d3c6d.png)
