### ISSUE TITLE
Specifying Probe outputs for high-speed export of data from a simulation

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#613]
While the default Probe system stores data in ```sim.data[probe]```, it would be useful to have a variety of options of where to send Probe data.  Backends would be free to implement this in a backend-specific manner, but the reference Nengo backend should provide useful functions that other backends might use in their implementations.  Importantly, the implementation should be focused of high-speed export of data from a running simulation (unlike the Node system, which is meant for generic input and output).

The following types of outputs are desired (all subclasses of ProbeOutput):
 - ProbeFile (data is appended to a .csv or .hdf5 file)
 - ProbeTexture (data is sent to an OpenGL texture)
 - ProbeUDP (data is sent over the network via UDP)

The suggested API is that Probes gain a new attribute ```output``` which can be set to a ProbeOutput.  The default value of "None" indicates the current ```sim.data[probe]``` approach should be used.  Multiple Probes might have the same ```output``` value, indicating this data should be merged as appropriate.  The ```label``` on a Probe can be used as an identifier for this merging (for example, the header of a ```.csv``` file).

Minimal example:

```python
model = nengo.Network(label='Minimal Example')
with model:
    a = nengo.Ensemble(100, 1, label='a')
    b = nengo.Ensemble(100, 1, label='b')

    file = nengo.ProbeFile()  # filename defaults to '%(model_name)s-%(timestamp)s.csv'
    nengo.Probe(a, output=file) # label defaults to a.label
    nengo.Probe(b, output=file) # label defaults to b.label
```

You should also be able to use the Config system:
```python
model = nengo.Network(label='Minimal Example')
model.config[Probe].output = nengo.ProbeFile()
with model:
    a = nengo.Ensemble(100, 1, label='a')
    b = nengo.Ensemble(100, 1, label='b')

    nengo.Probe(a)
    nengo.Probe(b)
```

It should be noted that the Node system is fairly flexible and initially seems like it could be used to implement this sort of functionality in a way that is completely independent of the backend.  One reason not to do this with Nodes is speed, as it should be possible to optimize this data output.  However, one other difference between the Node approach to getting data out of a simulation and this Probe approach is that the Probes should work in situations where the same model is built several times.  With a Node-based implementation, values would all be sent to to the same Node output function, regardless of which nengo.Simulator instance is run, necessitating some complex logic to separate out where the data should go.  With Probes, a new output may be created during the build phase.  For example, a ProbeFile might make a file name that indicates the moment the builder started, and two different running simulations for send data to different files, even though they have the same ProbeFile objects.  For this reason, I think it is worthwhile to add this extra Probe complexity to the Builder, even though it means that each backend will need to implement it independently.  That said, I think it would be useful to do the first implementation of this via Nodes (for instance, by having the Builder create some custom Nodes at the beginning of the build phase), both to simplify life and to give alternate nengo backends a basic implementation they can make use of.

Suggested attributes (and defaults) for the ProbeObjects:
 - ProbeFile
   - type (default='csv'; changes file format used)
   - filename (default='%(model_name)s-%(timestamp)s.%(type)s'; evaluated at build-time)
   - period (default=1.0; amount of time (in seconds) between file flushes
 - ProbeTexture
   - texture (OpenGL texture handle)
   - program (OpenGL program handle to be used when writing data)
 - ProbeUDP
   - address 
   - port

**Comment by hunse** [comment]
See #207 for some related discussion surrounding files. I'd like to explicitly raise some of those questions again here: Is it necessary to probe to a single file? Will that be difficult with CSV files? How will we load that data later? 

Could some of this be done at the simulator level (i.e. specify a Simulator output file, and then load and access that data later using the same `sim.data` interface)? It might be nice to have the same interface for dealing with simulated data currently in memory (from a fresh simulation) as with simulated data stored to file and accessed later.

**Comment by tcstewar** [comment]
> Is it necessary to probe to a single file?

Hmm, I hadn't really thought about that -- I'd just sort of assumed that was simplest.  I think I'd also be fine with Probing to a directory, and each Probe is a separate file in that directory (with some name munging because we can't just use the label as the file name, since it's not guaranteed to be a valid file name).  Oh, and we'd need a separate file for the times for each row in the files (unless we want to replicate that data in each file).

> Will that be difficult with CSV files?

The only place this seems complicated to me is if different probes have different ```probe_every``` values.  I'd be tempted to add a restriction that all Probes to the same ProbeFile have to have the same ```probe_every``` value.  If we have different values then it'd be simpler to implement if each Probe is in a separate file, each with its own set of times.

> How will we load that data later?

Lots of options, but I like the suggestion of providing a helper function that turns it in to the ```sim.data[]``` format.  It'd have to rely on correctly setting the labels, though (since we don't have unique identifiers for each probe target).  I also wouldn't require that you have to index it via probes, but could use the labels instead.  So you should be able to do:

```python
reader = nengo.utils.ProbeFileReader(filename)
plot(reader.trange(), reader.data['a'])
plot(reader.trange(), reader.data['b'])
```

Note that if labels weren't set in the original simulation, then you'd probably have to fall back on indexing into data:

```python
reader = nengo.utils.ProbeFileReader(filename)
plot(reader.trange(), reader.data[0])
plot(reader.trange(), reader.data[1])
```

**Comment by tcstewar** [comment]
Oh, and one other thing for reading data from one of these:  It'd be useful to have the same functionality as Nengo 1.4 where you could just specify the beginning of the file name, and it'd load the most recently created file that starts with that filename.  (I'm not sure if people knew you could do this in nengo 1.4, but that was part of the ```stats/reader.py``` code).

**Comment by drasmuss** [comment]
The OpenGL probe seems kind of niche, relative to the other two.  Do we really want to force all backends to support that?  I imagine you have a use case in mind though, is this to help with GUI design, or exporting figures for publication?

I can definitely see the uses for ProbeUDP, but for that one I wonder if it doesn't make more sense conceptually as a Node.  The main use case is for communicating data back and forth between different platforms in real time, as the simulation is running, right?  I've always thought of Probes as being used for dumping out information at the end of a simulation.  For example, in the ProbeFile case, if we want to optimize speed, we would probably save all the data for some number of timesteps and then write it all out to file at once, rather than writing every timestep.  So if we want ProbeUDP and ProbeFile to both be useful, we would need to have different specifications for different ProbeObjects, which seems kind of awkward.  

Or is the idea that this would be for end-of-simulation dumping, rather than real time communication?  Like sending results off the SpiNNaker board?  I could see that.   Although what we would really want then is ProbeTCP (since we wouldn't want to be losing results in the transfer); but then that isn't supported by SpiNNaker, which kind of defeats the purpose.

**Comment by tbekolay** [comment]
A few thought on the original post:

> The default value of "None" indicates the current sim.data[probe] approach should be used.

I'd recommend that the default be something like `ProbeMemory` or `ProbeList` or something like that, as we should avoid using `None` to mean something. With the current defaults / config system, it's trivial to implement something like this.

> The only place this seems complicated to me is if different probes have different probe_every values.

From what I know from reading through `pandas` documentation, missing data is pretty common in huge CSV files, which apparently describes the format of a lot of economics data. So, if we just have empty cells when samples weren't taken, I think we're following what most people do. Analysis packages like `pandas` (which we can recommend to people, and write some example code using) are designed to handle these things well.

----

In general, though, I'm not sure that I want to have a whole lot of code in Nengo itself for loading and analysing data ... feels like we should be relying on other libraries for that. I can see implementing something for loading whatever custom CSV format we implement (even for that we might want to defer to pandas), but for HDF5 we should save in [python-neo](https://pythonhosted.org/neo)'s HDF5 format, and use their libraries for loading / analysing. If their libraries are inadequate, improving them would be preferable to rolling our own, as there's a desperate need for well-tested and usable analysis packages in the Python neuroscience space.

**Comment by tcstewar** [comment]
> The OpenGL probe seems kind of niche, relative to the other two. Do we really want to force all backends to support that? I imagine you have a use case in mind though, is this to help with GUI design, or exporting figures for publication?

I don't think backends should be forced to support any of the ProbeOutputs.  Hopefully there's a nice Node-based fallback that they can easily implement if they want to, but I think all of the ProbeOutput stuff should be optional.

The main reason for listing the OpenGL ProbeTexture is to try to give a few different examples of ProbeOutputs so we don't end up designing this system to be only suitable for output to files.  My initial thoughts are that these three ProbeOutputs share the following features:
 - purely about outputting data from the model
 - data does not have to come out immediately on the exact time step, but can be sent in batches as the model is running (although it'd be nice for those batches to be as small as feasible)

The ProbeTexture itself came up just because the Stanford folks had something like it for Neurogrid and it'd be kinda nice to have something similar for their new chip which will be Nengo-based.  I've got code that shows it's pretty easy to do https://github.com/tcstewar/opengl_texture_rendering and it's a kind of interesting bizarre use case that seems similar enough to ProbeFiles that I think it's worth taking a stab at supporting both, and hopefully being suitable for other output methods as well.  The use case I had in mind for the ProbeTextures is just about GUI design (live raster-plots and activity-plots from large million-node hardware networks like SpiNNaker or Neurogrid).

> I can definitely see the uses for ProbeUDP, but for that one I wonder if it doesn't make more sense conceptually as a Node.

That's a very good point, and I could see an argument for just doing that as a Node.  In particular, a ProbeUDP doesn't have a natural thing to do when you build the model twice -- both of those Simulators would send data to the same UDP port (unlike ProbeTexture and ProbeFile, which could have different textures/files to go to).  That said, my intent with ProbeUDP is that it would also save the data for some number of timesteps and then send the data out all at once, for exactly the speed reasons you mentioned.  The amount of real time between sending out data might be small (10s of milliseconds, I'd say), but it wouldn't be based around trying to send a UDP packet every simulation time step.

> Or is the idea that this would be for end-of-simulation dumping, rather than real time communication? Like sending results off the SpiNNaker board?

It's more for during-simulation dumping.  These ProbeOutputs would expect to do something with the data periodically during the simulation.  For ProbeFiles, it might end up flushing to file every second or two.  For ProbeUDP and ProbeTextures, it might be every 10 milliseconds or so.  In all cases the time between dumps isn't locked to a simulation time step, which gives me hope that there's similarities in the underlying implementation.

**Comment by tcstewar** [comment]
> I'd recommend that the default be something like ProbeMemory or ProbeList or something like that, as we should avoid using None to mean something. With the current defaults / config system, it's trivial to implement something like this.

Very good point.  :)

> From what I know from reading through pandas documentation, missing data is pretty common in huge CSV files, which apparently describes the format of a lot of economics data. So, if we just have empty cells when samples weren't taken, I think we're following what most people do.

Yup, that doesn't seem too bad.

> In general, though, I'm not sure that I want to have a whole lot of code in Nengo itself for loading and analysing data ... feels like we should be relying on other libraries for that.

+1.  A quick little loader seems reasonable, but let's defer to existing software as much as possible.

**Comment by drasmuss** [comment]
>That said, my intent with ProbeUDP is that it would also save the data for some number of timesteps and then send the data out all at once, for exactly the speed reasons you mentioned.

Yeah that makes sense.  I think it's fine making it a Probe even if it feels more "Nodeish", a) as a demo of non-file Probe outputs and b) to match up with the rest of the Probe syntax.

>I don't think backends should be forced to support any of the ProbeOutputs.

Ah OK, I was thinking of this as an API proposal, but that makes sense I think.  Although we probably want to include at least `ProbeMemory` in the official API (and perhaps `ProbeFile` as well?)

**Comment by tcstewar** [comment]
> Ah OK, I was thinking of this as an API proposal, but that makes sense I think. Although we probably want to include at least ProbeMemory in the official API (and perhaps ProbeFile as well?)

I'd say that they (and ProbeTexture and ProbeUDP) part of the API, but optional for backends to support (sort of like how learning rules are optional for backends to support).  At some point we should have an official indication of what aspects of the API must be supported by all backends, but I've been holding off on that until we have a few more robust backends.

**Comment by drasmuss** [comment]
>At some point we should have an official indication of what aspects of the API must be supported by all backends, but I've been holding off on that until we have a few more robust backends.

I was just thinking the same thing (#614).  We're like an old married couple :two_men_holding_hands:.

**Comment by tbekolay** [comment]
Quick thought I'm putting here while I haven't forgotten it yet: a naming scheme like `ProbeToMemory`, `ProbeToFile`, `ProbeToUDP` seems preferable to me, over `ProbeMemory` etc. Perhaps even `ToMemory`, `ToFile`, `ToUDP`? E.g.:

```python
model = nengo.Network(label='Minimal Example')
with model:
    a = nengo.Ensemble(100, 1, label='a')
    b = nengo.Ensemble(100, 1, label='b')

    nengo.Probe(a, output=nengo.ToFile())
    nengo.Probe(b, output=nengo.ToFile())
```

**Comment by tcstewar** [comment]
> Quick thought I'm putting here while I haven't forgotten it yet: a naming scheme like ProbeToMemory, ProbeToFile, ProbeToUDP seems preferable to me, over ProbeMemory etc. Perhaps even ToMemory, ToFile, ToUDP?

Interesting..  Yeah, I could see ```ProbeToFile```.  Something about ```ToFile``` seems wrong, but mostly in that it's weird to see a class named by a prepositional phrase rather than a noun.  If we were to go that way, though, I think I'd prefer ```nengo.probe.ToFile()``` rather than ```nengo.ToFile()```.

**Comment by hunse** [comment]
I agree. If we name things like `ToFile` and just put them in the root namespace, I would expect them to work everywhere (e.g. `nengo.Node(output=nengo.ToFile())`).

**Comment by jgosmann** [comment]
Two remarks from my side:
1. It might be useful to also support the Numpy .npy/.npz output format. It requires less boilerplate code to load than HDF5 with pytables, but is more efficient than .csv space-wise.
2. I'm not sure whether a time interval is the best choice for the `period` argument to `ProbeFile`. Maybe it is better to give a size (in bytes) how much data should be buffered in memory before writing it to the disk or the number of simulation steps?

**Comment by tcstewar** [comment]
> It might be useful to also support the Numpy .npy/.npz output format. It requires less boilerplate code to load than HDF5 with pytables, but is more efficient than .csv space-wise.

Ooo..  good idea.  I'd missed that format.

> 2. I'm not sure whether a time interval is the best choice for the period argument to ProbeFile. Maybe it is better to give a size (in bytes) how much data should be buffered in memory before writing it to the disk or the number of simulation steps?

Possibly.  My worry with a memory limit is that it's a bit too easy to accidentally set that too small or too large (since it's hard to have an intuitive feel for how much data is being spooled).  A similar worry comes up with a fixed number of simulation time steps (is it a good idea to spool every time step? or every 1000 time steps?  It depends on the model....).  My reason for going with realtime-based period is that it has a nice intuitive interpretation in terms of "well, if your software crashes, at worst you'll lose this much CPU-time of data".  As the model gets larger and runs slower, we don't end up accidentally not flushing data for an hour because the period was set back when it was a small, fast model.  But mostly, this is just how I've generally written periodic caching stuff in the past, so I might just be stuck in a rut.

**Comment by drasmuss** [comment]
Specifying it in terms of simulation time makes the most sense to me, but again that's just the way I've always done it so may be biased.

**Comment by hunse** [comment]
One concern with file types is that I think we want it to be easily appendable. If we have to re-write the whole file each time, that could be a problem. I think that `.npy` files are stored this way, but we may have to add some helper functions to assist with the actual appending. Check out [the .npy formatter](https://github.com/numpy/numpy/blob/master/numpy/lib/format.py) and `ndarray.tofile`.

**Comment by jgosmann** [comment]
I don't think the standard NumPy functions support appending. But it would be possible to write our own solution for that. [The `.npy` format is documented here.](https://github.com/numpy/numpy/blob/master/doc/neps/npy-format.rst)

Turns out, I have some code lying around doing exactly that:
```python
import cPickle
import numpy.lib.format as npfmt
import os

class GrowingArrayFile(object):

    def __init__(self, filename, elementShape, dtype=float):
        self.fp = open(filename, 'wb')
        self.elementShape = elementShape
        self.numElements = 0
        self.dtype = dtype
        self.__writeHeader()


    def __writeHeader(self):
        self.fp.write(npfmt.magic(1, 0))
        npfmt.write_array_header_1_0(self.fp, {
            'shape': (self.numElements,) + self.elementShape,
            'fortran_order': False,
            'descr': npfmt.dtype_to_descr(self.dtype) })


    def __updateHeader(self):
        self.fp.seek(0)
        self.__writeHeader()
        self.fp.seek(0, os.SEEK_END)


    def write(self, array):
        assert array.shape[1:] == self.elementShape
        assert array.dtype == self.dtype

        # See for reference:
        # https://github.com/numpy/numpy/blob/maintenance/1.7.x/numpy/lib/format.py#L398
        if array.dtype.hasobject:
            # We contain Python objects so we cannot write out the data
            # directly. Instead, we will pickle it out with version 2 of the
            # pickle protocol.
            cPickle.dump(array, self.fp, protocol=2)
        else:
            array.tofile(self.fp)

        self.numElements += 1


    def __del__(self):
        self.__updateHeader()
```

**Comment by tbekolay** [comment]
https://github.com/nengo/enhancement_proposals/pull/5 now tracks this proposal. I tried to summarize everything on this thread there, but please feel free to comment on the proposal or make fixup commits if I missed anything.
