### ISSUE TITLE
Config system doesn't work as I expected

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#615]
I just realized that the config system doesn't work like I thought, though when I think about the architecture this isn't surprising. My mental model had been that if a parameter had not been set in a network's config, it would look to its parent network's config, until it either found a value or got past the top level network, in which case it would fall back on the parameter's default. But this isn't what happens, as evidenced by this example:

``` python
with nengo.Network() as model:
    model.config[nengo.Ensemble].radius = 2.0
    subnet = nengo.Network()

with subnet:
    a = nengo.Ensemble(10, 1)
    print a.radius  # prints 1.0
```

Since we're actively storing a context stack, and that's what we use to determine the defaults, when I make the ensemble in `subnet` the default set in model is actually off the stack, so there's no way to get at it anymore.

To do something different, though, we would have to have networks be able to figure out their parent network somehow. Maybe not something we want to worry about right now, but as a user with basic knowledge of the config system I would expect the ensemble in the above example to have a radius of 2.

**Comment by hunse** [comment]
I realized this when I was trying to fix up the strings in #529. I wanted to be able to print the actual defaults in the string (i.e. taking context into account), and then realized that in general this can't be done (or at least not in the way I thought it should be).

**Comment by tbekolay** [comment]
Ah, sorry, I'm already fixing up the strings in #529! You can do it taking the *current* context into account, but not all possible contexts...

**Comment by hunse** [comment]
> Ah, sorry, I'm already fixing up the strings in #529!

That's fine, I gave up when I realized that I couldn't do this.

**Comment by hunse** [comment]
> Ah, sorry, I'm already fixing up the strings in #529!

That's fine, I gave up when I realized that I couldn't do this.

**Comment by tbekolay** [comment]
> I gave up when I realized that I couldn't do this.

Silver lining!

**Comment by tbekolay** [comment]
Documented in #1224.
