### ISSUE TITLE
radius breaks target_function

### ISSUE THREAD

**Issue by fragapanagos** [nengo/nengo#623]
Setting the radius to something other than 1.0 breaks target_function.

    import nengo
    from nengo.utils.connection import target_function
    import numpy as np

    x = np.linspace(-1, 1, 10)
    model = nengo.Network()
    with model:
        # a = nengo.Ensemble(10, 1, radius=1.0)  # will work
        a = nengo.Ensemble(10, 1, radius=2.0)  # will break
        b = nengo.Ensemble(10, 1)
        nengo.Connection(a, b, **target_function(x, x))

    sim = nengo.Simulator(model)

produces

    KeyError: (-2.0,)

because the eval_points passed into the connection are scaled by the radius [here](https://github.com/nengo/nengo/blob/master/nengo/builder/ensemble.py#L40). When the scaled eval_points are passed to the function generated by target_function, they are not necessarily in its func_dict.

**Comment by tcstewar** [comment]
Yikes!  That's a pretty major bug to find.  Thank you for posting it!

**Comment by tcstewar** [comment]
Any ideas what to do about this?  This is an unexpected sideeffect of scaling the radius...  for now we might need to just pass in the radius to ```target_function(x, x, radius=2.0)``` but that's rather awkward-looking.  I don't see any other way of dealing with it though.

**Comment by tcstewar** [comment]
Here's another option: we add the scale_eval_point_by_radius parameter that was discussed in #564 and have that be one of the things returned from target_function (along with eval_points and function).

Note that passing in the radius the way I suggested above is problematic for floating point rounding reasons:  we can't just divide by the radius in target_function and allow the builder to multiply by the radius and expect that we'll get exactly the same result.

**Comment by tcstewar** [comment]
I just tried a minimal fix for this by adding a scale_eval_points parameter to Connection.  Not sure at all that this is the right way to go, but I don't see any other options.

**Comment by tcstewar** [comment]
(Btw, @fragapanagos , if you want to try out the fixed version, switch to the ```scaling_taget_function``` branch.  Let me know if that doesn't work for you!)

**Comment by fragapanagos** [comment]
@tcstewar The fixed version seems to be working.

**Comment by tcstewar** [comment]
> The fixed version seems to be working.

Cool.  No idea whether that'll be the eventual fix, but it should let you work with things for now...
