### ISSUE TITLE
probing neuron output vs neuron spikes

### ISSUE THREAD

**Issue by fragapanagos** [nengo/nengo#635]
What is the difference between probing an Ensemble's neurons' "output" vs "spikes"? Probing either seems to return the same data.

    import nengo
    import numpy as np
    net = nengo.Network()
    with net:
        ens = nengo.Ensemble(100,1)  # using default LIF neuron
        print ens.neurons.probeable  # includes 'output' and 'spikes'
        poutput = nengo.Probe(ens.neurons, 'output')
        pspikes = nengo.Probe(ens.neurons, 'spikes')
    sim = nengo.Simulator(net)
    sim.run(.1, progress_bar=False)
    print np.all(sim.data[poutput]==sim.data[pspikes])  # True

**Comment by tbekolay** [comment]
No difference; they're essentially aliases for the same thing. The reason for this, generally, is that for rate-based neurons, the name `'spikes'` doesn't make sense, but in general when people are probing spiking neurons, they want the spikes, and so we tried to minimize confusion by making `'spikes'` a thing you can probe.

Note that this is the default; if you just do `nengo.Probe(ens.neurons)`, you'll get `'output'` by default, so there are actually 3 ways to get the same data :laughing:

**Comment by fragapanagos** [comment]
Ah that makes sense now. Thanks.
