### ISSUE TITLE
Subclassing network, missing label.

### ISSUE THREAD

**Issue by e2crawfo** [nengo/nengo#638]
Not sure if this has been brought up before, but if you subclass Network, you can end up with a network that doesn't have a label attribute, and the label attribute is assumed to exist in __repr__ and __str__. Should we change __repr__ and __str__ to use hasattr?

**Comment by tcstewar** [comment]
Shouldn't that only happen if the person who subclasses Network forgets to call the base class' constructor?  If they forget to call that, then much worse things will happen than just not having ```label```.

**Comment by e2crawfo** [comment]
Oh yep I think you're right. That probably accounts for some of the other weird behaviour I was seeing as well. Thanks!
