### ISSUE TITLE
Unsupervised learning without initial transform breaks

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#639]
```python
import nengo

with nengo.Network() as model:
    a = nengo.Ensemble(100, 1)
    b = nengo.Ensemble(100, 1)
    conn = nengo.Connection(a.neurons, b.neurons)
    conn.learning_rule_type = nengo.BCM()

sim = nengo.Simulator(model)
```
This breaks at build time because we try to cheat with the transform, since in the case of a normal connection we would just leave the transform as `np.array(1)` and take advantage of Numpy's broadcasting to apply it properly. In the case of a learned connection, though, the transform ends up too small, and the builder can't apply the learning rule update.

**Comment by tbekolay** [comment]
Summary of discussion in dev meeting:

- The transform param should error in this case, and force the user to give a full `(post.n_neurons, pre.n_neurons)` transform. Make sure we have an example in which we do this.
- It should also be possible to pass in a distribution to the transform. That can be done in a separate issue though.
