### ISSUE TITLE
When creating SPA node inputs, automatically convert to array

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#661]
At this point, when you want to use SPA as an input to a network, you have to call the somewhat awkward `.v` attribute as demonstrated in the code below.

```
import nengo

model = nengo.Network()
with model:
    a = nengo.networks.EnsembleArray(n_neurons=100, n_ensembles=16, ens_dimensions=1)
    def my_input(t):
        if t < 0.1:
            return vocab.parse('HELLO').v
        else:
            return vocab.parse('BYE').v

    nengo.Connection(nengo.Node(my_input), a.input)
```

Is there any way to automatically convert to a vector so this doesn't need to be called? The reason I believe this is possible is that numpy seems to transparently convert between arrays and python lists all the time.

**Comment by jgosmann** [comment]
Moved to nengo/nengo_spa#12.
