### ISSUE TITLE
Use of __import__ is discouraged

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#664]
While looking at PR #663 I noticed the use of `__import__`. [The Python docs say:](https://docs.python.org/3/library/functions.html#__import__)

> Direct use of **import**() is also discouraged in favor of importlib.import_module().

I propose:
1. Change `nengo.utils.testing.find_modules` to use `pkgutil.iter_modules` instead of traversing the filesystem ourselves.
2. Use (preferrably) the module loader returned by `iter_modules` or `importlib.import_module` to import the module in `nengo.utils.testing.load_modules`.

Alternatively, it seems to that writing something like a py.test collector plugin might be even better and maybe could solve some of the todos (like test functions in classes).

I'm not sure how exacty these functions are used and what could break, so I am putting this out for discussion first. Maybe someone can also provide a usage example?

**Comment by hunse** [comment]
I'm working on getting NengoOCL up to date right now, and it has an example.

**Comment by tbekolay** [comment]
The NengoOCL example: https://github.com/nengo/nengo_ocl/blob/master/nengo_ocl/test/test_sim_ocl.py

One note is that `importlib` was introduced in Python 3.1. `import_module` was backported to 2.7, but we'd have to retire 2.6 before making the change (we were planning to do this for Nengo 2.1 anyhow, though).

Writing a py.test collector was what I originally set out to do (as it's what we did with `unittest` previously), but unfortunately it's not a straightforward thing. I made [this SO question](http://stackoverflow.com/questions/21030987/running-pytest-tests-in-another-python-package) to find out how to do it in py.test, and it seems as thought it's just not possible right now. I tried to modify py.test to make it possible, but didn't get very far.

**Comment by jgosmann** [comment]
We're doing a lot of non-classical testing stuff ...
I might spend some thought on it as I've been hacking quite some py.test stuff together recently.

What would you think about a `--simulator` argument to py.test for setting the simulator under test (e.g., `--simulator nengo_ocl.sim_ocl.OclSimulator`). That might actually be pretty easy to achieve. Of course that would require that the simulator module is in the import search path.

**Comment by hunse** [comment]
So the way Nengo OCL is set up right now, it has a number of test files, many of which have OCL-specific tests, and one of which loads all the Nengo tests so that they can be run. It's nice to be able to do `py.test nengo_ocl` (in the Nengo OCL repo) to be able to run all the OCL tests. It would be annoying to have to switch to the Nengo repo to run the OCL tests, which I think is what would have to happen if you wanted to have a `--simulator nengo_ocl.sim_ocl.OclSimulator` option. Also, this would only run the Nengo tests on OCL, and not the OCL-specific tests.

**Comment by jgosmann** [comment]
As Nengo has to be installed, you do `py.test --simulator nengo_ocl.sim_ocl.OclSimulator --pyargs nengo` from anywhere. But yes, you would have to run two commands to get all tests. Though, you could write a little shell script.

**Comment by jgosmann** [comment]
Actually, pytest allows to specify multiple modules: `py.test --simulator nengo_ocl.sim_ocl.OclSimulator --pyargs nengo nengo_ocl` Annoying to type everytime, but you can specify default arguments in a `pytest.ini` file.

**Comment by jgosmann** [comment]
What I don't like about it, is that you can't undo the `--pyargs` flag in case you want to specify a directory.

**Comment by hunse** [comment]
I also just found that I need to overwrite one of the fixtures (so that I'm not testing with RectifiedLinear and Sigmoid neurons, just LIF and LIFRate). I'm not sure if this is doable with your solution.

**Comment by jgosmann** [comment]
If we add a function to ask the simulator about supported neuron types it should be possible.

**Comment by jgosmann** [comment]
I think, I came up with a reasonably nice solution. But I cannot fully test it at the moment as nengo_ocl is not up to date.

**Comment by jgosmann** [comment]
The functions in question would become obsolete with PR #709.
