### ISSUE TITLE
Probing decoders on a non-decoded connection

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo#665]
Here's a simple script to illustrate the problem:
```python
import nengo

with nengo.Network() as net:
    a = nengo.Node([0])
    b = nengo.Ensemble(100, 1)
    c = nengo.Ensemble(100, 1)

    conn1 = nengo.Connection(b, c)
    conn2 = nengo.Connection(a, b)
    conn3 = nengo.Connection(b.neurons, c.neurons)

    nengo.Probe(conn1, "decoders")
    nengo.Probe(conn1, "notprobeable")
    nengo.Probe(conn2, "decoders")
    nengo.Probe(conn3, "decoders")


sim = nengo.Simulator(net)
```

The first probe works fine, as it should.  The second probe is caught by our validation and gives a good error, as it should.  The third/fourth probe just fail at build time with `KeyError: 'decoders'`.  

The problem is that `Connection` says that you can probe `decoders`, by putting that in its `probeable` list, but that's actually only conditionally true.  So anything that relies on the `probeable` list doesn't work in that case (I figured this out because I was using `nengo.utils.probe.probe_all`, which looks though `probeable`).

Possible solutions
1) Just throw some patch fixes on the places where this is a problem (perhaps add some special case validation, fix `probe_all`).  I actually think this is probably the best idea.  It's clearly an error to probe the decoders on a non-decoded connection, so I don't think we should bend over backwards to accommodate the fact that users might do that.
2) Rework the `probeable` system to allow conditional probeables.  This only seems worth doing if we think there are other cases where this might be a problem, but since we haven't run into any yet, I'd be inclined to avoid this.

**Comment by tbekolay** [comment]
Fixed in #671.
