### ISSUE TITLE
Add `plt.show()` to static example scripts

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo#670]
Our notebook examples don't include `plt.show()`, since it isn't needed.  But it is needed in the static *.py files that are generated from the notebooks.  Right now, users run the example scripts and it seems like nothing happens, which is confusing (just had a new user ask me about this).

The easiest solution might just be to add it to the notebooks, assuming that doesn't cause any problems for ipython.  Or we could do some extra magic when the scripts are generated.

**Comment by drasmuss** [comment]
We also need to strip out the ipython commands (e.g., `%matplotlib inline`), otherwise they cause errors when the script isn't run through ipython (another user reported error).

**Comment by tbekolay** [comment]
We already strip out `%matplotlib inline`; see [this example](https://pythonhosted.org/nengo/examples/single_neuron.html)'s associated [Python script](https://pythonhosted.org/nengo/examples/single_neuron.py). For reference, this is done [here in `utils/ipython.py`](https://github.com/nengo/nengo/blob/master/nengo/utils/ipython.py#L192).

This could be improved to remove any line with `get_ipython` in it, though!

**Comment by drasmuss** [comment]
Ah ok, the user was probably just copy-pasting from the online examples.

**Comment by mgserafi** [comment]
How do you generate the static *.py files?

**Comment by tbekolay** [comment]
> How do you generate the static *.py files?

The function that does this is [`export_py`](https://github.com/nengo/nengo/blob/master/nengo/utils/ipython.py#L171), which is called by the [Notebook directive](https://github.com/nengo/nengo/blob/master/nengo/utils/docutils.py#L50), which is what is used when

```rst
.. notebook::
```

is encountered in our documentation.
