### ISSUE TITLE
organize the examples

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo#684]
the list of examples is long and the titles aren't descriptive enough to know what they're good for... some subfolders with categories like:
basics
SPA examples
dynamics
tutorials (or feature demos) -- ones where you learn about using nengo directly, e.g. configs
NEF concepts?

maybe others... would make it way easier to navigate all the riches of information in that folder.

**Comment by jgosmann** [comment]
I think, older IPython versions do not support subdirectories.

**Comment by hunse** [comment]
Directories were annoying in old IPython. You basically had to start the notebook server in the directory you wanted, so I always had to `cd examples/` before starting the server. So it wouldn't be any harder to `cd examples/basic/`, but if I started the server there, I wouldn't be able to switch to other examples in the other subdirectories.

**Comment by jgosmann** [comment]
This was resolved with #698.
