### ISSUE TITLE
Add utils for logging git info

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#685]
The `analytics` and `logger` fixtures track things that change over time, but 'time' isn't necessarily the most salient thing in most cases. It'd be good to have a utility to query the repository for current information. Things like: what `git` branch am I on, what's the current commit hash (perhaps not actually that helpful), are there modified files, that kind of thing.

There's two options for how to do this. The first is to just open subprocesses, call git commands, and parse stdout. The second is to use a Python module like [GitPython](https://github.com/gitpython-developers/GitPython). My guess is that the first will be easier.

**Comment by jgosmann** [comment]
[I've got some very basic code lying around to interact with git.](https://github.com/jgosmann/fridge/blob/legacy/fridge/vcs.py) Not sure if it is helpful at all.
[Sumatra is another Python project interacting with git.](https://github.com/open-research/sumatra/blob/master/sumatra/versioncontrol/_git.py)

**Comment by jgosmann** [comment]
Example command line to achieve something like that without changes to Nengo:
```bash
py.test --plots=nengo.`git rev-parse HEAD`.plots
```

**Comment by jgosmann** [comment]
Or with branch name:
```bash
py.test --plots=nengo.`git rev-parse --abbrev-ref HEAD`.plots
```

**Comment by tbekolay** [comment]
Lately I've been opting for the

```
$(command)
``` 

syntax instead of

```
`command`
```

but those are great snippets :) Closing with the `document this` label in case anyone wants to expand those into documentation or an example.
