### ISSUE TITLE
Change spa.Buffer name

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo#690]
Terry and I have been discussing this in an email... Here's a summary so far.

Chris:

>> it's occurred
>> to me that maybe we should rename spa.Buffer to something else?  Buffer is
>> an odd word that we don't generally use in the SPA, especially since
>> WorkingMemory is it's own spa element.  Do you think just spa.Ensemble would
>> make sense? (Since that's usually what it is...)  or perhaps you have
>> another idea...

Terry:

> Hmm...  yup, I'd totally be onboard with changing that name.  The
> intent with the name Buffer is to indicate that it's transient storage
> -- if something isn't actively sending stuff into it, it won't store
> the value (that's the difference between a Buffer and a Memory). But
> the word "Buffer" really doesn't communicate that well.  I'm not sure
> I like spa.Ensemble, as I think that'd be prone to confusion.   But
> I'm not sure what's better.
>
> Another possibility would be to combine Buffer and Memory into one
> thing called Memory, and do something like:
>
> model.a = spa.Memory()                          # this is a Buffer
> model.b = spa.Memory(maintain=True)     # this is a Memory

Chris: 

As for the name thing, I also worried about Ensemble being confusing -- then I thought a) maybe the 'spa.' would help alleviate confusion enough and b) aren't these really extremely functionally similar to regular ensembles (and more so ensemble arrays).  So it seemed like the best option... given:

- I also thought about the 'memory' thing, but worried that they're really not like memories in any typical sense  (i.e. only last a couple ms is 'remembered')... any more than regular ensembles are I suppose. 

- I've been trying to come up with other designations, but none really strike me as good: representation (too generic); pointer (don't have to be compressed); network (don't really have internal structure); group/population (just synonyms for ensemble); neurons/vector (nope); CorticalEnsemble or other things longer than one word (too long ;) )

Anyway, that's where my thinking is at the moment... no resolution yet, but still feeling 'buffer' isn't quite right.

**Comment by tbekolay** [comment]
The main problem with `spa.Ensemble` is that people could/would do `from nengo.spa import Ensemble` and then the resulting model code would be super confusing. `SPAEnsemble` would be better (though `spa.SPAEnsemble` is redundant, so probably no better then `Buffer`).

I'm just spitballing from the perspective of someone who doesn't use / understand the SPA stuff that well, but one possibility is to try to use this as a way to reinforce the idea of Modules... I'm not sure what the mental model of a "module" is supposed to be, but I feel like this name should reflect what that mental model is. E.g., looking through the `spa` hierarchy, every network is a "module" that manipulates a semantic pointer in some way.. the `Memory` module uses recurrent connections to store that pointer, for example. The `Buffer` module essentially does nothing to the pointer. So maybe a name that reflects that would be good. `Passthrough` (as we used for Nodes previously) might work, or `Identity`, or maybe something like `BaseModule` which is kind of the "default" module, which just represents a pointer unchanged.

**Comment by hunse** [comment]
I kind of like Vector; why did it get a "nope"? Too generic? "Vector" to me suggests an ensemble array, where each element is independent, whereas "Pointer" suggests an ensemble, where the whole thing is normalized/saturated so it can't be more than unit length.

The only other thing I can think of is Transient, though that probably over-emphasizes the temporary aspect and makes it sound like it's unimportant or undesired. I also thought of Scratch (like a scratch file), but that seems too computer-science-y and opaque.

**Comment by celiasmith** [comment]
Yes, good point about Ensemble. And SPAEnsemble is better than Buffer, 
because even if redundant, it's got less (or the right?) conceptual baggage.

I'm not a fan of 'module' talk when it comes to brain modeling. Fodor 
has effectively poisoned this word for many people... defining it as 
informationally encapsulated, and other non-brainy things. But maybe I 
should just get over that :)

I'd prefer Subsystem, maybe? If we feel the need to label that... though 
not sure we need to.

I don't think we want to suggest that buffers are passthrough, as you 
*can* do things (like with any ensemble) with them.

Trevor Bekolay wrote:

**Comment by tcstewar** [comment]
Hmm...  I could see ```spa.Vector()``` working...  that somehow implies to me that it's just a vector and nothing else.  ```spa.Pointer()``` is a bit loaded, I think, and ```spa.SemanticPointer()``` is too long.  But I could see giving ```spa.Vector()``` a try.

As for ```Module```, I'm willing to try to reclaim the word from Fodor...  :)  that said, really all it is is a subclass of Network that's got some bookkeeping info to allow the semantic pointer action-syntax to work.  So I could also see it being called ```spa.Network```......

**Comment by celiasmith** [comment]
Yeah, Vector seemed generic. Also, the ensemble array (and hence 
spa.Buffer) can have any amount of dimension interaction that you want, 
it's a parameter (the default is 16)... so it tends to normalize a fair 
amount.

Hmmm... yeah I agree with your comments on scratch and transient... 
SPEnsemble (sounds like spaun-semble :) ... i think SPAEnsemble might be 
better still)


Eric Hunsberger wrote:

**Comment by tcstewar** [comment]
Hmm...  I really don't like ```spa.SPAEnsemble```...  that doesn't look anything like anything else we've got.

**Comment by celiasmith** [comment]
I'd add that another concern with Vector is that most of the components 
are named after neural, functioning parts (i.e. vehicles or processes, 
not their contents)... Memory, BG, CleanUp... i strikes me that a Vector 
is what these neurons carry... but what they *are* is a semantic pointer 
or an ensemble (note that this is because I define SPs to be neural 
representations... so, not abstractions like vectors). This is a pretty 
fine/nit picky point though :)

tcstewar wrote:

**Comment by xchoo** [comment]
What about spa.Representation?

**Comment by xchoo** [comment]
Or something along those lines (i.e. it's the component that you can use to represent stuff?)

**Comment by celiasmith** [comment]
Same concerns as with Vector...

**Comment by celiasmith** [comment]
Of the things floating on the page, CorticalEnsemble and SPAEnsemble strike me as:
1. Vehicle names
2. Accurate reflections of what the component is/does (for those who've used Nengo)
3. Not confused with Ensemble

(I worry 'Network' suggests internal structure.)

**Comment by hunse** [comment]
> I'd add that another concern with Vector is that most of the components
are named after neural, functioning parts

I was actually thinking the opposite: it seemed to me that most SPA elements are named after their function or high-level role (e.g. Memory, Input, Actions, Vocabulary, Compare).

Looking at it, it seems that it's actually about half and half (BasalGanglia, Thalamus, Cortical vs. Compare, Input, Actions, Vocabulary), with some terms that can go either way (e.g. Memory).

> (i.e. vehicles or processes, not their contents)... Memory, BG, CleanUp... i strikes me that a Vector
is what these neurons carry

I think the other things are named after processes because they are. But the object-formerly-known-as-Buffer is a bit different, because it is less concerned with doing anything and more concerned with just representation. That's why I liked Vector. But I also see your point.

**Comment by jgosmann** [comment]
In digital systems a buffer is a gate that does nothing to the signal except a delay (and maybe an amplification) which matches what the `spa.Buffer` does.

* I don't like Vector which to me is the thing being stored.
* CorticalEnsemble makes me wonder if there is any additional stuff going on except for storing the SP.
* SPAEnsemble seems to me like a good name except for the somewhat redundant prefix (but I would prefer it over spa.Ensemble).
* spa.Representation seems also like a somewhat good name to me.

**Comment by celiasmith** [comment]
Hmm... I think that Actions, Vocab, and Input are not neural things, so yes, they are named abstractly.  But the other stuff is mostly neural stuff.  So you're right, there are two kinds of object, but all the neural stuff is named after it's vehicle/neural thing... except Compare.  the object-formerly-known-as-Buffer (I like that :) ) is a neural thing so shouldn't have an abstract name I think.

As I look through the code with this kind of view in mind, it makes me think we need a meeting to figure out naming/usage of SPA more.  Maybe Terry and I (and anyone else who cares) should talk more first or something... the complexities are piling up!

**Comment by Seanny123** [comment]
As mentioned in issue #761 I would like to change `spa.Buffer` and `spa.Memory` and take this opportunity consolidate them into a single object. I would like to do this, since the only different between them is a recurrent connection and `spa.Memory` is so general that it causes confusion with the other memory modules we have in Nengo.

Given this new criteria, I would like to put my vote behind `spa.Representation` and give the option of a boolean parameter called `decay` or `keep_last_input` to turn it into a memory. Can we discuss this further at the next meeting?

**Comment by tcstewar** [comment]
My only problem with ```spa.Representation``` is the length.  I'm tempted by ```spa.Represent``` but that might be a bit too cute.  

One other option is ```spa.State``` which is nice and short.  And since #761 will be getting rid of the ```state``` in ```model.vision.state.output``` we won't be using ```state``` for anything else.

I think my favourites right now are ```spa.State``` and ```spa.Vector```.

**Comment by pblouw** [comment]
Of those two, `spa.State` would by my preference.

**Comment by jgosmann** [comment]
Just had another idea: `spa.Relay`

But I think `spa.Representation` would be my favourite. We could also use the Python abbreviaton `spa.Repr`, but that seems a bit obscure.

**Comment by celiasmith** [comment]
ditto. the memory could be indicated by ``feedback`` and take a scalar 
that would let you control the rate of decay (decay would be a bit odd 
because high 'decay' would decay more slowly than low 'decay')

pblouw wrote:

**Comment by Seanny123** [comment]
My problem with `spa.State` is that implies to me a certain amount of permanence. Is that just me?

I like the idea of the `feedback` parameter abstracting away the actual time constant business.

**Comment by celiasmith** [comment]
i was liking 'State' because of the state space vs neuron space 
distinction that we rely on a lot.

Sean Aubin wrote:

**Comment by tbekolay** [comment]
+1 to `State` and `feedback`!

**Comment by Seanny123** [comment]
Okay Chris, you've won me over with State. I think it's a nice reminder of how SPA is this separate thing from neuron space. My only gripe is that we're going to have to explain the `feedback` thing in the tutorial somewhere (which always feels like a bad code smell to me), but I guess that's fine since everyone is going to need to look at a tutorial anyways if they want to use SPA. It's also going to require significantly less awkward explaining then Buffer and Memory.

How much consensus do we need before we go ahead on this?

**Comment by celiasmith** [comment]
seems like we're probably good, can always vote at the meeting tomorrow 
:smiley:

Sean Aubin wrote:

**Comment by hunse** [comment]
I like `Vector`, but that's only because I prefer the term "vector-space" to "state-space" (for Nengo models). I won't cry if we go with `State`.

**Comment by Seanny123** [comment]
As voted upon during the meeting on Friday, we're going with `state` which will not cause Eric to cry.

**Comment by hunse** [comment]
@Seanny123 : if you put e.g. "Fixes #690" in your commit message, then it GitHub closes the issue automatically when the PR is merged.

**Comment by tbekolay** [comment]
:+1: That line should be the last of the commit message (not in, e.g., the subject line). 2025f5517d71ddc44495247de99e6f8f378c15f9 is a good example.

**Comment by Seanny123** [comment]
Thanks guys! I didn't know that!
