### ISSUE TITLE
Specifying encoders to an EnsembleArray as a non-distribution may cause config error to occur.

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#691]
If the non-distribution encoders are provided to an EnsembleArray, there is a possibility that the following error will occur:

``` python
ValueError: n_neurons not yet initialized; cannot determine if shape is correct. Consider using a distribution instead.
```

This occurs when the config update line

``` python
self.config[nengo.Ensemble].update(ens_kwargs)
```

updates the `encoders` parameter in `kwargs` before it has done so for `n_neurons`.

**Comment by studywolf** [comment]
oh this came up for me the other day too. i wasn't using the config system but just trying to specify encoders not as a parameter but after.
