### ISSUE TITLE
Set up SPA to use config system

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo#695]
This is just a general wishlist item, but it would be nice if we could use the config system with SPA models (e.g., to set `neurons_per_dimension` for all `Buffers` at once).  I don't think this would require any changes to the existing setup if we did want to do it, it would just be a matter of refactoring `spa` objects to be `NengoObjects` and using `Parameters`.  Not urgent though.

**Comment by drasmuss** [comment]
I should also say, there's a reasonable case for not doing this at all (to preserve the distinction between core Nengo objects and the SPA system).

**Comment by drasmuss** [comment]
A sub-issue of this one: In some places SPA manually sets a parameter that is normally controlled by the config system (as opposed to adding new parameters that aren't in the config system like I was talking about above).  For example, `Buffer` has a separate `direct` parameter that controls the neuron type (by allowing it to be either `Direct` or `LIF`).  If we just didn't set the neuron type within `Buffer`, we could control it like this:
```python
with nengo.Network() as net:
    net.config[nengo.Ensemble].neuron_type = nengo.LIFRate()
    buff = spa.Buffer(...)
```
which would be more consistent with the rest of Nengo, and more flexible.  I suspect this is just because the `spa` code was written before we had the `config` system in place.  I could make this change myself, but I want to check if people like it first (since it would require small modifications to existing models that use the current parameter system).

**Comment by tcstewar** [comment]
I definitely agree this should happen.  Especially for things like the Direct option.  It's the way it currently is just because the config stuff wasn't in place when the spa stuff got written.  This change would make a lot of sense to me....

**Comment by Seanny123** [comment]
+1 for extending config to SPA

I think the distinction between core Nengo and SPA is important, but it's generally pretty obvious once you start making SPA-based models that you're not in Kansas anymore.

**Comment by jgosmann** [comment]
Basic classes to do:
- [x] Scalar
- [x] State
- [ ] Bind
- [ ] Compare
- [ ] Input

More complex classes:
- [ ] AssociativeMemory
- [ ] BasalGanglia
- [ ] Thalamus
- [ ] Cortical

Deprecated classes to delete:
- [ ] Buffer
- [ ] Memory
- [ ] SPA
