### ISSUE TITLE
Fix unit testing of warnings.

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#703]
We have some unit tests verifying that certain warnings are issued. However, these do not take into account that a warning might be configured to be only issued once. Under certain circumstances tests might run twice (see issue nengo/nengo_ocl#63) and thus failing in the second run.

[About unit testing warnings.](https://docs.python.org/2/library/warnings.html#testing-warnings)

Tests failing:
* test.nengo.tests.test_ensemble.test_eval_points_number_warning
* test.nengo.networks.tests.test_ensemblearray.test_neuronconnection[nl0]

**Comment by tbekolay** [comment]
Note that this is related to #636; both involve setting a different warning filter than the default `"once"`.
