### ISSUE TITLE
Query supported features of backend

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#705]
I'm working on making it easier to run the Nengo tests against different backends and it occurred to me that it might be useful if it were possible to query a backend for supported features in a standardized way. That would make it possible …
* … to write models in a backend agnostic way by checking for certain features and do some stuff to work around a missing feature.
* … to detect automatically which tests have to be passed by the backend.

**Comment by tbekolay** [comment]
+1! I think we could probably figure out a decent syntax for this.

The hard part is going to be actually enumerating out all of the possible features that could exist, and how they interact... it's probably possible, but that would definitely be a Big Job. We also need to make sure that this additional documentation requirement is beneficial for backend implementers, or else it will be seen as a hurdle they have to jump through for no reason.

**Comment by mundya** [comment]
As an external backend developer: +1

> The hard part is going to be actually enumerating out all of the possible features that could exist, and how they interact...

The problem I can see here is that the supported features can be quite specific/arcane.  For example, SpiNNaker currently doesn't support connections into neurons unless the connection is from some output/decoded output with a transform that delivers the same value to every neuron (this is for global inhibition support).  While I intend to support neuron->neuron connections soon it is very unlikely that we'll ever do x->neurons with anything but a global-inhibition-like transform.  I can't think of a pleasant way of expressing this.

**Comment by tcstewar** [comment]
> The problem I can see here is that the supported features can be quite specific/arcane. For example, SpiNNaker currently doesn't support connections into neurons unless the connection is from some output/decoded output with a transform that delivers the same value to every neuron (this is for global inhibition support). While I intend to support neuron->neuron connections soon it is very unlikely that we'll ever do x->neurons with anything but a global-inhibition-like transform. I can't think of a pleasant way of expressing this.

I wonder if it might make sense to directly base these queries on the backend in terms of just which nengo/tests it passes.  So you could do something like ask if a particular backend passes ```nengo/tests/test_connection/test_neurons_to_ensemble```.  Something like ```if nengo_spinnaker.supports(nengo.tests.test_connection.test_neuron_to_ensemble)```.

It might be possible to set that up such that a backend developer wouldn't have to do anything extra to support that.  That way, instead of coming up with a new way of describing all possible things a backend might support, we just directly use the test suite itself as that ontology.   (and if there are any backends which, like SpiNNaker, require a finer division in terms of supported features, then that just indicates new tests to add).

The main drawback I see to this is that it means that once a test exists, it really shouldn't be modified or renamed, since someone might have an if statement about it....

**Comment by hunse** [comment]
> I wonder if it might make sense to directly base these queries on the backend in terms of just which nengo/tests it passes.

This seems like a very natural way to do things to me.

**Comment by tbekolay** [comment]
>> I wonder if it might make sense to directly base these queries on the backend in terms of just which nengo/tests it passes.

> This seems like a very natural way to do things to me.

Agreed, I like it! It will have the nice side-effect of encouraging backend designers to submit additional tests to basically say "I can do this thing, which other backends may not be able to do". I think implementation-wise, we just have to determine where the burden is: the function that checks if a test is skipped, or the backend to put their list of skipped tests in a standardized or discoverable place.

As a sidenote, this might be something worth writing in the frontiers paper I'm working on (@mundya, I added you as a collaborator on that paper repo if you'd like to read it and/or be a coauthor!)

**Comment by mundya** [comment]
> I wonder if it might make sense to directly base these queries on the backend in terms of just which nengo/tests it passes.

+1

(@tbekolay, thank you, I shall have a look and get in touch :)

**Comment by jgosmann** [comment]
I like the idea of just using the tests. The difficult part will be how to run them outside of the pytest context.

**Comment by jgosmann** [comment]
Actually, it might not be that difficult ...

**Comment by tbekolay** [comment]
Summary of dev meeting discussion:

All in favour ;) @jgosmann has already started implementing it by running the test live when support is queried. We talked a bit about ways to do this not-live, by each backend specifying what tests they don't support, and inspecting that when support is queried. Possibly that will be stored in the backend's Simulator class somehow? If that's done, then the Nengo tests can skip those tests automatically (through some pytest hook).

-----

As an initial sense for what this might look like...

In `backend/simulator.py`:
```python
class Simulator(object):
    failing_tests = [
        ('test_ensemble.test_noise*', "Noise not supported."),
        ...
    ]
```
In `nengo/tests/conftest.py`
```python
@pytest.fixture
def Simulator(request):
    for test, reason in Simulator.failing_tests:
        if re.match(test, request.node.name):
            request.applymarker(pytest.mark.xfail(reason=reason))
            break
    return nengo.Simulator
```
That's mostly pseudocode, haven't run it, just scanned the pytest documentation a bit to find something that might work.

**Comment by jgosmann** [comment]
#711 has been merged, can we close this issue?

**Comment by tbekolay** [comment]
I think the only thing left is to document this for backend developers -- I've added a link in #625 pointing here for more info, so I think this can be closed.
