### ISSUE TITLE
Backend version numbers

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#715]
A few of our backends are nearing the point where they can be uploaded to PyPI, which means they need a version number. I'm going to propose a certain version numbering scheme below; feedback greatly appreciated from those implementing backends, even if it's just a +1 / -1 (/cc @mundya @hunse @tcstewar). Once we reach a consensus, I'll make a PR adding the info to the docs.

----

First, as a precondition, Nengo and all backends will use [semantic versioning](http://semver.org/). That means that the version number is of the form MAJOR.MINOR.PATCH. See the link for precise definitions of these.

I propose that the major and minor version numbers for backends should match the version of Nengo that they support. The patch number can freely vary in all projects, as the patch number should only be incremented when bugs are fixed.

The primary advantage of this type of numbering scheme is that it is clear what version of Nengo a backend supports. Nengo OCL 2.0.x should be able to run any supported model that runs in Nengo 2.0.y, for example. That means that upgrades within the minor versions (e.g., 2.0.1 -> 2.0.2) should be painless -- they should never break user code, so that we can operate under the assumption that it's always viable to update to the most recent patch version when bugs are reported.

The main disadvantage is that Nengo releases will have a large impact on backend development. With a new minor Nengo version, each backend has to decide whether to finish implementing features for the now-previous version, or update to the new version. Basically, it limits the flexibility of the backend's versioning scheme and release schedule.

**Comment by hunse** [comment]
So this also comes with the guarantee that Nengo patches will never break a backend? In some cases, it seems impossible for a backend to support all patches of a minor release. For example, between Nengo 2.0.0 and 2.0.1, Node functions were changed to receive `t` as a float instead of a Numpy scalar. If users built nodes that depended on `t` being one type or the other, then the backend could fail.

**Comment by tbekolay** [comment]
Yes, a Nengo patch should never break a backend, unless the backend was relying on a bug, essentially. The assumption should be that the most recent patch version is the only version that matters. As long as updating within the MAJOR.MINOR version is never difficult, then backends should be able to tell Nengo that it's doing something wrong (which we can patch), and vice versa.

**Comment by tcstewar** [comment]
Sounds like a good plan to me...  +1

**Comment by mundya** [comment]
This sounds like a good plan... it worries me maybe a little that the backend's (limited) API is frozen by Nengo release schedules.

What worries me more is that, particularly in the SpiNNaker case, the backend is tracking two+ APIs - either of which could necessitate making backwards incompatible changes.  That said, +1 and we'll see what happens?  I can't see this being a serious problem unless someone makes code that relies on the way nengo_spinnaker talks to SpiNNaker/how C is put together on SpiNNaker.

**Comment by tbekolay** [comment]
Actually one thought just occurred to me that might dissuade me from such a plan... There's no reason why a backend couldn't support multiple Nengo frontend versions. So, in the builder or simulator, either explicitly check `if nengo.version.version_info < (2, 1, 0)` or check for some new attribute in a new version of Nengo, or some such. This would also allow a backend to support more features in more versions of Nengo. Hopefully the Nengo frontend changes won't ever be too tough to keep up with anyhow!

As an alternative plan then, I think backends should (in `Simulator.__init__`) explicitly check the Nengo version info and raise an exception if that version isn't supported. I think it's worth adding an exception class in Nengo for this; backends can import it (or some helper function) and raise that in `__init__`.

**Comment by tbekolay** [comment]
Reminder to @tbekolay : make some backend docs and add this to that

**Comment by tbekolay** [comment]
Moved to https://github.com/nengo/nengo.github.io/issues/2
