### ISSUE TITLE
test_cache_performance fails

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#718]
`test_cache.py:test_cache_performance` fails on my machine, I think because it's too fast at computing decoders so the cache speedup is not great enough to pass the test! (Specifically, the final assert fails because my relative diff is 0.37 which is not > 0.4.)

Anyway, it would be better to do this test in a way that is more machine agnostic. I'm not quite sure what to compare, though. The alternative and easier solution would be to just relax the numbers a bit.

**Comment by jgosmann** [comment]
There's a whole bunch of reasons why that test isn't very well designed and the problem should be addressed with PR #677. Basically the test is removed and replaced with tests that just plot and store the benchmark data.
