### ISSUE TITLE
Consider making some of our objects immutable

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#719]
Mutable objects make life more difficult for Nengo, as they can't safely be used for things like default arguments, and make the parameters system more difficult to implement. We could simplify lots of things if we just made some objects immutable; this would have a very small impact on end-user code, as most objects are made once and never changed (or if they are changed, they're replaced rather than mutated). Basically, anything that isn't a subclass of `NengoObject` is a candidate for being made immutable.

Unfortunately it's not immediately obvious how to make a custom Python object immutable. A good place to start is [any of these hits](https://www.google.ca/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=making%20immutable%20python%20objects) and in particular [this SO question](http://stackoverflow.com/questions/4828080/how-to-make-an-immutable-object-in-python).

**Comment by hunse** [comment]
We've got our nice Parameter system, could we just use those everywhere and make them read-only?

**Comment by tbekolay** [comment]
Hm... maybe!

**Comment by hunse** [comment]
I've been trying to use Parameters more, anyway, since they do nice automatic type checking.

**Comment by tbekolay** [comment]
The infrastructure for doing this was done in #758 and at this point most things that should be immutable are. If there are any additional objects that mutable but should be immutable, please open a new issue for that object specifically!
