### ISSUE TITLE
Connection seed not being set in __init__

### ISSUE THREAD

**Issue by cjmpseth** [nengo/nengo#725]
If I set a seed when initializing a connection (ie conn = nengo.Connection(a,b,seed=5)) the seed is still left as default None. I think the line "self.seed = seed" is missing in connection.py

**Comment by tcstewar** [comment]
Hmm, I'm not actually sure what a seed should even do on a ```Connection```.  I would have thought that should be a syntax error.  (The randomness is in the Ensemble, not in the connection itself).  Although I suppose that seed could be used when computing the decoder for that connection.....

**Comment by hunse** [comment]
@tcstewar: good point. We had the property in there for some reason...

**Comment by hunse** [comment]
Yeah, it looks like we pass it to the solver in case it wants an rng, and when generating the eval points if they haven't been generated by the ensemble.
