### ISSUE TITLE
SPA network fails and it is non-obvious why

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#730]
It took me a while to figure out why the following network wasn't working:
```python
model = spa.SPA(seed=84)
with model:
    input_buf = spa.Buffer(d, vocab=vocab)
    spa.Input(input_buf='B')
    
    p_input_buf = nengo.Probe(input_buf.state.output, synapse=0.01)
```

Turns out that `spa.Input` has to be assigned to something and that almost everything has to be prefixed by `model.`. Working version:

```python
model = spa.SPA(seed=84)
with model:
    model.input_buf = spa.Buffer(d, vocab=vocab)
    model.input_node = spa.Input(input_buf='B')#, current_buf=lambda t: 'A' if t < 0.3 else '0')
    
    p_input_buf = nengo.Probe(model.input_buf.state.output, synapse=0.01)
```

In non-SPA examples we don't do the prefixing with `model.` which makes it non-obvious why it is suddenly needed. That `spa.Input` has to be assigned to someting (even though it is never referred to afterwards) might also be not obvious.

**Comment by jgosmann** [comment]
Note that the first case does not produce an exception. The network runs fine, but produces just noise.

**Comment by Seanny123** [comment]
Ran into the same problem today.

**Comment by xchoo** [comment]
Yup! That's the one quirk of the spa system. You have to assign it to model for it to be recognized by the underlying spa system.

**Comment by Seanny123** [comment]
Is it absolutely necessary to do that?

**Comment by xchoo** [comment]
Yes. The spa system hooks into the "onadd" (or something like that) system for objects. If you don't assign it to the network, the spa system doesn't call the onadd for it, and so it won't know about it.

**Comment by tcstewar** [comment]
> Is it absolutely necessary to do that?

I'm pretty sure I could fix it so that spa.Input would work without that.  But I still need it (I think) for figuring out what the names of Modules are so that the spa.Actions() thing will work.  Basically, if I did this:

```python
with model:
    wm = spa.Buffer(D)
    actions = spa.Actions(
        'dot(wm, A) --> wm=B'
    )
```

then there's no way for the Actions thing to know that ```wm``` refers to the ```spa.Buffer``` that has been created.

One possibility is to change the syntax to this:

```python
with model:
    spa.Buffer(D, name='wm')
    actions = spa.Actions(
        'dot(wm, A) --> wm=B'
    )
```

but that's also very different from normal syntax.

Another option:

```python
with model:
    wm=spa.Buffer(D, name='wm')
    actions = spa.Actions(
        'dot(wm, A) --> wm=B',
        modules = dict(wm=wm)
    )
```

or even:

```python
with model:
    wm=spa.Buffer(D, name='wm')
    actions = spa.Actions(
        'dot(wm, A) --> wm=B',
        modules = locals()
    )
```

**Comment by tcstewar** [comment]
> I'm pretty sure I could fix it so that spa.Input would work without that.

Er, never mind, the same naming problem comes up.  But it could be changed to

```python
    spa.Inputs((wm, 'A'), (wm2, lambda t: 'B' if t<0.1 else 'C'))
```
which is even uglier...  never mind....  :(

**Comment by jgosmann** [comment]
I think, it would already be a huge improvement if this code would raise an exception:
```python
model = spa.SPA()
with model:
    buf = spa.Buffer(64)
    buf2 = spa.Buffer(64)
    
    actions = spa.Actions('buf = bu2')
    cortical = spa.Cortical(actions)
```

**Comment by Seanny123** [comment]
+1 for raising an exception

If SPA has to be black magic to be useful, at the very least it should warn people.

**Comment by Seanny123** [comment]
After discussing with Terry, the approach to accomplish this seems to be hooking into the "on exit" function of the `with` and then doing some validation on the network. So, checking that any thing that's been added and inherits from `spa` has also been added to an attribute.

**Comment by tcstewar** [comment]
> So, checking that any thing that's been added and inherits from spa has also been added to an attribute.

Just to clarify, I think this should be "any spa.Module that's been added (i.e. it's in ```model.networks```) and that has a non-empty ```module.inputs``` or ```module.outputs```.

**Comment by tbekolay** [comment]
Right now the network calls `Network.add` ([here](https://github.com/nengo/nengo/blob/master/nengo/network.py#L95)). If we instead make this `self.add`, then SPA could do some custom stuff on add (just make you also call `super(...).add`)

**Comment by tcstewar** [comment]
> Right now the network calls Network.add (here). If we instead make this self.add, then SPA could do some custom stuff on add (just make you also call super(...).add)

Yes.  Unfortunately, that ```add``` occurs during the constructor, so there's no way to detect whether someone is doing ```wm = spa.Buffer()``` versus ```model.wm = spa.Buffer()``` since ```model.__setattr__``` hasn't been called yet.

**Comment by tbekolay** [comment]
Ah, gotcha. Right, in that case, the `__exit__` function makes sense to verify these things.

**Comment by Seanny123** [comment]
If I'm writing tests for this, what test file should it be put into? Should I make my own test file? Is our test file policy documented somewhere?

**Comment by tbekolay** [comment]
There's no test file policy... put it somewhere that makes sense to you, given all the test files that already exist. E.g., for this one, somewhere in the `nengo/spa/tests` directory tree. If it's super wrong we'll let you know, but that seems unlikely.

**Comment by hunse** [comment]
We've typically done one test file per code file.
