### ISSUE TITLE
Assigning BCM learning rule to connections without weight matrix gives misleading error

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#732]
Assigning the BCM learning rule to a connections using the normal decoder solver (and not a weight solver) gives the following exception:
`ValueError: Validation error when setting 'Connection.learning_rule_type': Learning rule 'BCM' cannot be applied to connection with pre of type 'Ensemble'`

But the problem here is not that pre is an ensemble, but that the connection's weight solver has to be changed.

**Comment by s72sue** [comment]
This was fixed in #642.
If you try now, you should get the following error:
![image](https://cloud.githubusercontent.com/assets/12284191/8536510/74b0b20c-2420-11e5-932b-065b9f9b03b4.png)

**Comment by tbekolay** [comment]
Confirmed that the ValidationError now raised is still what @s72sue stated (just in case!) so closing.
