### ISSUE TITLE
Feature Request: Refresh Simulator when Sourced file updates

### ISSUE THREAD

**Issue by wchapman** [nengo/nengo#735]
Currently if you have:
=== Main.py ===
from myFile.py import myClass

Whenever you edit main.py, nengo_gui will restart the simulation, taking the change in to account. However, if you edit myFile.py, the gui does not restart the simulation.

**Comment by tbekolay** [comment]
This repository only deals with the underlying scripting interface (i.e., what you get when you `import nengo`). All the GUI stuff is tracked at [this repository](https://github.com/nengo/nengo_gui). Do you mind [making a new issue](https://github.com/nengo/nengo_gui/issues/new) there instead?

**Comment by tbekolay** [comment]
Thanks! :rainbow:

**Comment by wchapman** [comment]
Yup, sorry about that!

**Comment by tbekolay** [comment]
Oh no worries, it pushes up our issue count and makes us look like a super active project ;)
