### ISSUE TITLE
Param defaults can be modified in-place

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#746]
One example is the connection solver:
```python
conn = nengo.Connection(a, b)
conn.solver.weights = True
```
This actually changes the default solver, so **all** connections using the default solver now solve for weights. We could have similar problems with other parameters, too.

Two possible solutions are:
  1. Have parameters make a copy when they're being set to their default value. This requires that they know how to copy the default value.
  2. Make objects such as neuron types, solvers, etc. frozen after creation, so that trying to change an instance will result in an error.

**Comment by Seanny123** [comment]
Are there trade-offs? I'm thinking that option 1 is more flexible and option 2 is more cautious. Since this is such an uncommon practice (or at least I think it is), I'm thinking option 1 is most practical.

**Comment by hunse** [comment]
The difficulty with option 1 is that copying can be difficult. If a neuron type has a parameter that's an array, do you copy the array? Or if it has a parameter that's a synapse, which has a parameter that's an array? Do you keep copying all the way down?

We've been talking about freezing objects for a while. That way, if someone makes their own e.g. NeuronType object, and passes it a bunch of places, they can't change it and accidentally have it change everywhere. I think it's much safer for descriptive objects like NeuronTypes, Synapses, Distributions, Processes, etc., to be frozen. This just seems like another good reason to do it.
