### ISSUE TITLE
Uncaught transform error

### ISSUE THREAD

**Issue by mundya** [nengo/nengo#750]
```python
with nengo.Network():
    a = nengo.Ensemble(300, 1)
    b = nengo.Ensemble(300, 1)
    nengo.Connection(a, b, transform=[1])
```
Should raise an error because the transform is a vector rather than a matrix or a scalar.

This is a problem in Nengo from Git on both my machine and Chris'.

**Comment by hunse** [comment]
No, that's a valid transform. If you pass a vector transform, Nengo treats it like you passed `np.diag(transform)` (except doesn't actually call that, since that would make the internals less efficient).

**Comment by tcstewar** [comment]
Ah.  Wacky.  I didn't know we supported that....  Does that situation come up much?  Does it only work when ```size_in==size_out```?  I suppose in combination with slicing it can be useful....

**Comment by mundya** [comment]
That's neat.  Given that I'd expect that `full_transform` would still return a matrix, returning a vector in this case seems wrong to me:

```python
>>> with nengo.Network():
...     a = nengo.Ensemble(100, 1)
...     b = nengo.Ensemble(100, 1)
...     c = nengo.Connection(a, b, transform=[1])
>>> nengo.utils.builder.full_transform(c)
array([ 1.])
```
