### ISSUE TITLE
Make piecewise able to return strings

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#762]
At the moment, `piecewise` is unable to return strings (it currently returns an array with `dtype=|S3`) which means it isn't possible to use it in `spa`. Would it be a bad idea to hard-code special treatment for strings? Alternatively, what about making a `piecewise_spa` function?

**Comment by tcstewar** [comment]
What's you situation for using this?  I've generally found that it's clearer to not use ```piecewise``` and just define the function for a lot of cases....

**Comment by Seanny123** [comment]
Just a toy example in a tutorial testing a lot of cases. But apparently, this was also requested in #512 for making SPA unit tests easily.

**Comment by tcstewar** [comment]
For simple things, I really like just doing

```python
function=lambda t: 'RED' if t < 1.0 else 'GREEN'
```

which is pretty readable.  In fact, I'd argue it's more readable than ```piecewise({0:'RED', 1:'GREEN'})```.  And sometimes I want things to alternate between options, giving

```python
function=lambda t: 'RED' if (t % 2.0) < 1.0 else 'GREEN'
```

of course, that can also be done with this, which extends to more options:

```python
function=lambda t: ['RED', 'GREEN', 'BLUE'][int(t / 1.0) % 3]
```

I'd really only use ```piecewise``` if I have some complex non-periodic thing going on.  Although in those cases I'll usually just go ahead and write it as a function with a big if statement.

**Comment by Seanny123** [comment]
Yeah, that looks good enough for me.
