### ISSUE TITLE
Update nengo.ca

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#763]
A person I talked to at the summer school ended up downloading Nengo 1.4 in preparation for the summer school and presenting it to his lab. I realize we didn't want to this initially because Nengo was still pretty beta, but we've done a few releases and I feel like our GUI is solid enough to link to.

Here's a list of things that need to be changed, ranked from most important to least important:
- [x] The "Download" page needs to be re-written. Maybe link to the "history" section of Nengo for people who might be confused?
- [x] The  "Documentation" page should should link to our python-hosted page
- [x] The "Development" page needs to be re-written
- [ ] The "Overview" page needs to be updated with Nengo 2.0 screenshots (currently just inserted a warning)
- [ ] The "FAQ" page needs to be re-written (half-way done)
- [ ] The Nengo 1.4 videos need to be archived and new videos created. Are videos of each network actually that useful?
- [ ] The contact page should be updated? Also, are those mailing lists still being used? Are they searchable?
- [ ] Possibly link to our newer videos on the video page?
- [ ] The front page should have a video of our actual GUI working
- [ ] The model archive should specify the version of Nengo or maybe we can just use GitHub for that?

Is there anything else I've missed? @tcstewar can I get the password to the Drupal site to make these changes?

Alternatively, should we just burn Nengo.ca and make a minimal Github page, with a link to a model archive?

**Comment by tcstewar** [comment]
> @tcstewar can I get the password to the Drupal site to make these changes?

Sure...  what's your standard uwaterloo account id?  I'll make a drupal account for you....

> Alternatively, should we just burn Nengo.ca and make a minimal Github page, with a link to a model archive?

There's enough other stuff there right now (including the summer school and video links and so on) that replacing nengo.ca would be a medium-sized job.  Probably something we should do at some point, but not now.  :)

**Comment by Seanny123** [comment]
Things that need changing:

Copy the installation instructions to the download page.
Make sure people can still install the old version.

**Comment by celiasmith** [comment]
Should probably give instructions for the 'book version' as well, which i guess is now different from the 'old version'

**Comment by Seanny123** [comment]
Fixed the problems talked about in the meeting.

**Comment by tcstewar** [comment]
I just made a few small tweaks to separate out the Python and Java versions a bit more.

**Comment by tbekolay** [comment]
Since the content in nengo.ca will eventually be moved to https://github.com/nengo/nengo.github.io, made an issue there linking here so we can close this.
