### ISSUE TITLE
Cannot supply array of eval_points to EnsembleArray

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#766]
```
...
  File "c:\users\aaron\ctn\nengo\nengo\networks\ensemblearray.py", line 55, in __init__
    self.config[nengo.Ensemble].update(ens_kwargs)
  File "c:\users\aaron\ctn\nengo\nengo\config.py", line 105, in update
    setattr(self, key, d[key])
  File "c:\users\aaron\ctn\nengo\nengo\config.py", line 56, in __setattr__
    param.validate(self, value)
  File "c:\users\aaron\ctn\nengo\nengo\dists.py", line 336, in validate
    dist = super(DistOrArrayParam, self).validate(instance, dist)
  File "c:\users\aaron\ctn\nengo\nengo\params.py", line 212, in validate
    "distribution instead." % attr)
ValueError: dimensions not yet initialized; cannot determine if shape is correct. Consider using a distribution instead.
```

Possible solutions?
- Force people to only use distributions with EnsembleArrays. This seems like an unreasonable limitation to me.
- Include the number of dimensions before the ensembles are configured, i.e.
  
  ```
  self.config[nengo.Ensemble].dimensions = ens_dimensions
  self.config[nengo.Ensemble].update(ens_kwargs)
  ```
  
  But this is hacky because this solution has to be repeated for all similar situations with other networks. Also, it's important to note that you can't just do `ens_kwargs['dimensions'] = ens_dimensions` otherwise you get undefined behaviour, because it relies on the order of dictionary iteration to update `dimensions` _before_ `eval_points`, which may or may not happen depending on the alignment of the sun with Neptune.
- Create a new `StaticDistribution` that always iterates through a fixed list, and then cast `eval_points` arrays to this distribution when the param is set (thus removing `DistOrArrayParam`)? I think this is a better long-term solution, assuming I'm not overlooking anything.

Note: Add a unit test for this.

**Comment by jgosmann** [comment]
Has this been resolved with the merge of #1233?

**Comment by jgosmann** [comment]
ping @arvoelke

**Comment by arvoelke** [comment]
Yep!

```
import nengo
import numpy as np
with nengo.networks.EnsembleArray(3, 2, eval_points=np.zeros((3, 1))) as model:
    for ens in model.ensembles:
        print ens.eval_points
```

```
Samples(samples=array([[ 0.],
       [ 0.],
       [ 0.]]))
Samples(samples=array([[ 0.],
       [ 0.],
       [ 0.]]))
```

Thanks.
