### ISSUE TITLE
Sparse probing of spike trains

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#770]
I'm probing neurons on a simulation with `dt=1e-4` (10 kHz) and the average firing rate is 0.2 kHz. This uses 10/0.2 = 50x more space than if one were to record the spike times or the interspike intervals. This is a pretty big issue for me at the moment as my probe data is on the order of a couple hundred gigabytes. I currently need to `sample_every` and reset the simulator every hour to avoid paging.

Would be nice to have a sparse format for probing spike trains. Being able to append directly to a neo file would solve this.

**Comment by hunse** [comment]
Duplicate of #161 and #447, see also #429 (first attempt at a solution). Maybe we should actually add this...

**Comment by arvoelke** [comment]
Yes please! Thanks.
