### ISSUE TITLE
Semantics of Vocabulary.create_subset

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#771]
I was assuming that `Vocabulary.create_subset` would return the same vectors as in the original vocabulary, but this doesn't seem to be the case. Not sure, if that's intended behavior and use case.

**Comment by xchoo** [comment]
Um... Further analysis of the problem is needed. :smile: 
Were the vectors already in the vocabulary before the subset was created? If so, it should return identical vectors.

**Comment by jgosmann** [comment]
I was accidentally modifying vectors in the vocabulary which changed the semantic pointers returned when accessing them with the key, but did not change the `vectors` attribute. Maybe we should make the semantic pointers readonly?

**Comment by tcstewar** [comment]
> I was accidentally modifying vectors in the vocabulary which changed the semantic pointers returned when accessing them with the key, but did not change the vectors attribute.

How were you modifying vectors in a Vocabulary without modifying ```vectors```?  That's the only place they are stored.  Or were you modifying the SemanticPointers that were returned out of the Vocabulary?  Changing those won't affect anything....  I'd be hesitant to make them immutable though, as there are a bunch of situations where I've liked being able to ```.normalize()``` them....

**Comment by jgosmann** [comment]
```python
v = model.get_default_vocab(d)['A'].v
v[:alpha] = 0.
return v
```

**Comment by jgosmann** [comment]
Easy way to reproduce:
```python
from nengo import spa
vocab = spa.Vocabulary(32)
vocab.parse('A+B')
v = vocab['A'].v
v[:16] = 0.
```
Now `vocab['A'].v` will be
```
array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.09463713, -0.58110597,  0.19689652, -0.03374787,
        0.11232108, -0.01746146, -0.05679393, -0.07588708, -0.13367433,
       -0.23685301,  0.10164089, -0.16013591, -0.11619642,  0.14302399,
       -0.06525624, -0.04868728])
```
But `vocab.vectors` is
```
array([[ 0.22961744, -0.03054376, -0.15719356,  0.29441729, -0.10023645,
         0.20138127, -0.23005973, -0.21369591, -0.05950654,  0.17842421,
        -0.05815623,  0.1612631 , -0.16367743,  0.15825772,  0.05266126,
        -0.08603211, -0.09463713, -0.58110597,  0.19689652, -0.03374787,
         0.11232108, -0.01746146, -0.05679393, -0.07588708, -0.13367433,
        -0.23685301,  0.10164089, -0.16013591, -0.11619642,  0.14302399,
        -0.06525624, -0.04868728],
       [-0.02127027, -0.11451335,  0.44414594, -0.17419019,  0.27381963,
        -0.04712555,  0.03847383, -0.13700343,  0.06402521, -0.23716384,
         0.08086054, -0.12177467, -0.18158035,  0.3041383 ,  0.02425396,
        -0.01641839, -0.04005394,  0.0606535 , -0.20813698,  0.02582912,
        -0.09338578,  0.03474193,  0.18836795,  0.15216382,  0.00143475,
         0.05208581,  0.15211444, -0.44775083,  0.15730145,  0.02255281,
         0.19283632,  0.21616461]])
```

**Comment by tcstewar** [comment]
Hmm... my feeling on that is it's a documentation issue.  You're asking the Vocabulary for something, and then after it returns it you're modifying it to something different, and then expecting the Vocabulary to know about that change.  So we need to make it clear that whenever you get something out of a Vocabulary, you're actually getting a new object, not some view into the internal object.

That said, what this is pointing out is that we should have a way to set the value of a pointer in a Vocabulary after it already exists.  We have ```add``` but that's only for completely new items.  Would something like ```vocab.set_value('A', v)``` be clear?  Or ```vocab.modify('A', v)```?

**Comment by jgosmann** [comment]
> and then expecting the Vocabulary to know about that change.

actually, I was expecting the Vocabulary to be unaffected. (But I forget that I have to be careful when modifying Numpy arrays.)

Also, I am not sure whether we should have a way to change pointers after they already exist.

And, I would argue that `SemanticPointer` should be immutable. If `SemanticPointer.v` had been readonly, I would have caught my error much earlier, but returning a copy would also work as in that case I would not have modified the original vector.

**Comment by jgosmann** [comment]
Just to totally clear: I did *not* intend to modify the vocabulary.

**Comment by tcstewar** [comment]
Ah, shoot, I was completely misunderstanding what you were saying.  I completely forgot that the Vocabulary caches the SemanticPointers, rather than re-creating them out of ```vocab.vectors```.  And since those are mutable everything can get completely screwed up the way you're describing.  I thought you were purposefully modifying the returned pointer in the hope that it would modify the value stored in the Vocabulary.

Now that I know what's going on, I think you are completely right about wanting some sort of immutable ability.  I like the idea of ```.v``` returning a copy...  that's pretty straightforward.  It might also be good to have an immutable flag for SemanticPointers and have it set on the cached versions inside the Vocabulary.....Hmm.

**Comment by jgosmann** [comment]
I would prefer to make all SemanticPointers immutable instead of introducing a flag for it. If you have to modify a SemanticPointer you can always create a new one with the modified data.

**Comment by tcstewar** [comment]
> I would prefer to make all SemanticPointers immutable instead of introducing a flag for it. If you have to modify a SemanticPointer you can always create a new one with the modified data.

Interesting.  I think I could be convinced that way.  That would mean removing ```normalize```, ```__iadd__```, ```__isub__```, and ```__imul__``` and making sure we don't use those anywhere.  I'm pretty sure I've used ```normalize``` relatively frequently, but that'd be a pretty small syntax change.  I'd definitely say we should do the process of deprecating those functions for a version or two (i.e. they'd still work, but they'd give a warning message), and I'd want to look through some more code to see if there are any counter-arguments, but I could see it working.

**Comment by hunse** [comment]
We can always have functions for normalizing, adding, etc. that return new objects, just not allow it in place.

**Comment by tcstewar** [comment]
> We can always have functions for normalizing, adding, etc. that return new objects, just not allow it in place.

Yup, and indeed all those functions already exist (other than ```normalize```, but that's pretty close to ```b = a / a.length()```.
