### ISSUE TITLE
Combining small ensembles within the same layer

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#778]
In certain cases, we might repeat lots of small ensembles in a single "layer" (e.g. the vision network of @hunse, or my texture classifier), and this turns out to be very inefficient because lots of small numpy vector operations are way more expensive than their grouped equivalent.

See, for example:

```
import numpy as np

import nengo

def model_slow(n_ensembles, neurons_per_ensemble):
    with nengo.Network() as model:
        stim = nengo.Node(output=[1])
        output = nengo.Node(size_in=1)
        for i in range(n_ensembles):
            ens = nengo.Ensemble(neurons_per_ensemble, 1)
            nengo.Connection(stim, ens)
            nengo.Connection(ens, output, transform=1./n_ensembles)
        return model

def model_fast(n_ensembles, neurons_per_ensemble):
    with nengo.Network() as model:
        stim = nengo.Node(output=[1])
        output = nengo.Node(size_in=1)
        ens = nengo.Ensemble(n_ensembles*neurons_per_ensemble, 1)
        nengo.Connection(stim, ens)
        nengo.Connection(ens, output)
        return model


from timeit import Timer

n_ensembles = 1000
neurons_per_ensemble = 5
duration = 0.1
trials = 20

def bootstrap(method, n_ensembles, neurons_per_ensemble, duration):
    sim = nengo.Simulator(method(n_ensembles, neurons_per_ensemble))
    return lambda: sim.run(duration)    

for method in model_slow, model_fast:
    t = Timer(bootstrap(method, n_ensembles, neurons_per_ensemble, duration))
    print t.timeit(trials)
```

In this (rather dramatic) example, there is a 200x performance gain by grouping together all of the ensembles:

```
130.49983397
0.644406616342
```

It's also more accurate whenever the sub-ensembles are encoding correlated (or, in this case, the exact same) information, because the decoders should be solved for jointly (as a brief aside: this is the case if you use a `Product` network and set either `A` or `B` to be a single scalar [i.e. scaling a vector]).

In general this sort of optimization isn't always so easy to do (either manually or automatically).
- Need to know when not to use the `EnsembleArray`
- Can be tricky to set different distributions on the different sub-ensembles
- May want different synapses on different sub-ensembles (this one is the killer for me, while it should be theoretically possible to group different synapse models together into a more efficient LTI)
- Or just may not be obvious that an optimization could be done when the code is scattered throughout a large-scale model
- ...?

Also related to #738.

**Comment by hunse** [comment]
Check out the `optimizer` branch. I had been working on this a while ago, but it's all out of date.

I agree that there are a lot of optimizations that can be done with EnsembleArrays if people don't change parameters on individual ensembles. Options would be:

1. Have an `optimize` flag. If set, we assume all the ensembles in the array are the same, so if the user makes changes they'll be lost (this flag would be unset by default).
2. Check that all ensembles are the same before optimizing.
3. Figure out some super optimizer that can optimize even if ensembles are different.

I think at different points, I've tried both optimizing EnsembleArrays and just putting *all* ensembles together. The advantage to the latter is that it's easier in some ways, but it won't put synapses or anything else together, just the neuron models themselves. Also, you can do even more with EnsembleArray optimization if all the ensemble encoders and decoders are the same.

**Comment by arvoelke** [comment]
I like options 2 or 3 in theory.

> Also, you can do even more with EnsembleArray optimization if all the ensemble encoders and decoders are the same.

Could you expand on this? Do you mean something like only computing one sub-ensembles set of activities and then using them for all? When would this happen?

**Comment by hunse** [comment]
No, they would all have different values, but if you have the same encoders, you can do a matrix-matrix multiply (encoders times stacked vectors) to compute all the input currents at once, rather than doing many matrix-vector multiplies. Ditto with the decoders.

**Comment by jgosmann** [comment]
These sorts of optimizations are something I would like to discuss at one of the next dev meetings. For spaopt (#941) semantic pointers are ideally stored in ensemble arrays with 1d ensembles. A much better simulation performance could be achieved by grouping the corresponding numpy operations.

**Comment by jgosmann** [comment]
Also, I would favor to solve this specific problem for now and we can then extend it later to more general cases (e.g., differing synapses) if needed. But it might make sense to think about how such future extensions could be integrated.

**Comment by jgosmann** [comment]
Made a PR #1035

**Comment by arvoelke** [comment]
This was implemented a while ago, and so marking this as closed! See paper for details: https://www.frontiersin.org/articles/10.3389/fninf.2017.00033/full.
