### ISSUE TITLE
Associative Memory interface change

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#780]
The current `AssociativeMemory` network constructor takes a whole bunch of parameters (14 of them if my count is right). This is partly because you can:
- Supply an input vector list, output vector list
- Define a default output vector if no match is found
- Supply a threshold 
- Change the input scale to the AM network (this can be removed)
- Make the AM network inhibitable, and change the scale on the inhibitory input
- Have a WTA network on the AM network, and set the mutual inhibitory scale, and the synapse on the WTA parts.
- Add a thresholding network on the output of the AM network

I'm thinking of reworking the network such that instead of passing the options to the constructor, you configure the network after it is constructed (like the `add_output` function call for ensemble arrays).
e.g.:

```
am_net = AssociativeMemory(vocab.vectors, label='my am')
am_net.add_default_vector_output(...)
am_net.add_wta(inhibit_scale=5, synapse=0.01)
am_net.add_thresholded_output()
am_net.make_inhibitable(inhibit_scale=3)
```

Comments? @jgosmann @tcstewar

**Comment by jgosmann** [comment]
Seems like a good idea to me.

What happens if those functions are called multiple times?

**Comment by xchoo** [comment]
Gooooooooood question. What should happen if the function is called multiple times?
I think I'll just make it such that once it a function is called, calling it another time will not alter the network.

**Comment by tcstewar** [comment]
Hmm.  Is there a reason to not allow those still to be set via the constructor, even if you have these extra functions as well?  I remember being hugely annoyed in some Java APIs where a whole bunch of things had to be done via this sort of extra function calls.....

(I like it for ```EnsembleArray.add_output``` because it does make sense to call it multiple times to make different outputs...  otherwise I would have had it as part of the constructor).

**Comment by jgosmann** [comment]
The reason to do so, is that function signatures should be short to keep them readable. ([Discussed in more detail in this book lying on my desk.](http://www.amazon.ca/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)) I admit, this is less of an issue in Python thanks to keyword arguments. But for the associative memory some arguments have only effect in relation to other arguments. Making separate functions calls would group these arguments semantically together.

It can be bothersome to be required to assign the created instance to an object to do further configuration. But, as it is a SPA module this has to be done anyways.

Another potential benefit would be that I can create distinct parts of the network with different active configs.

**Comment by jgosmann** [comment]
> I think I'll just make it such that once it a function is called, calling it another time will not alter the network.

Calling it twice should probably produce a warning.

**Comment by xchoo** [comment]
My reason for wanting to change it is to improve readibility of the code. For example, 

```
am_net = AssociativeMemory(vocab.vectors, label='my am')
am_net.add_default_vector_output(...)
am_net.add_wta(inhibit_scale=5, synapse=0.01)
am_net.add_thresholded_output()
am_net.make_inhibitable(inhibit_scale=3)
```

is currently done as this:

```
am_net = AssociativeMemory(vocab.vectors, label='my_am',
                           default_output_vector=...,
                           wta_output=True, wta_inhibit_scale=5.0, wta_synapse=0.01,
                           inhibitable=True, inhibit_scale=3.0,
                           threshold_output=True)
```

which is not the easiest to figure out what the associative memory is configured for.

**Comment by xchoo** [comment]
> Calling it twice should probably produce a warning.

Except there is one case where one of the functions will call another function. When you add a thresholded output, if there is no default output vector, it will add one in for you (but not "expose" it to the outside).

**Comment by tcstewar** [comment]
> The reason to do so, is that function signatures should be short to keep them readable. (Discussed in more detail in this book lying on my desk.) I admit, this is less of an issue in Python thanks to keyword arguments.

I find the keyword arguments stuff in Python pretty much makes up for that.  We certainly have lots of function signatures in nengo that are of similar size.

> But for the associative memory some arguments have only effect in relation to other arguments. Making separate functions calls would group these arguments semantically together.

This I completely agree with, and I like that general principle.  I'd take this as an argument that we should extract out ```am_net.add_wta(inhibit_scale=5, synapse=0.01)``` but that there'd be no reason to do  ```am_net.add_thresholded_output()```.

> Another potential benefit would be that I can create distinct parts of the network with different active configs.

Hmm...  I'm not sure what you mean by this.  Could you give an example?

**Comment by tcstewar** [comment]
> My reason for wanting to change it is to improve readibility of the code.

Hmm...  I don't immediately find either of those examples more readable than the other.  I can sort of see it in the cases where there are multiple related parameters, but when it's just a distinction between setting a single argument in the constructor versus calling a function afterwards, I'm not clear on the difference.

The reason I'm being a bit hesitant here is that in general in nengo we've been allowing people to do what they can in the constructor, and it's the exception to have to do something after the constructor.  So I'd like to have strong reasons to do so.  I think the point about grouping semantically related parameters is a strong reason, but that only applies to some of these cases.

**Comment by jgosmann** [comment]
> I find the keyword arguments stuff in Python pretty much makes up for that. We certainly have lots of function signatures in nengo that are of similar size.

Which doesn't mean that I'm 100% happy with it in all cases. Just not unhappy enough to do something about it so far (and I also didn't have a good idea how to improve it).

> that there'd be no reason to do am_net.add_thresholded_output()

I guess, what exactly to extract out and what to keep in the function arguments is an additional discussion. We should probably create some guideline rules to ensure consistency across Nengo objects.

> Another potential benefit would be that I can create distinct parts of the network with different active configs.
> 
> Hmm... I'm not sure what you mean by this. Could you give an example?

Sure:
```python
cfg1 = nengo.Config(nengo.Ensemble)
cfg1[nengo.Ensemble].max_rates = nengo.dists.Uniform(100, 200)
with cfg1:
    am_net = AssociativeMemory(vocab.vectors, label='my am')

cfg2 = nengo.Config(nengo.Ensemble)
cfg2[nengo.Ensemble].max_rates = nengo.dists.Uniform(400, 500)
with cfg2:
    am_net.add_default_vector_output(...)
```
Not sure if this is actually something someone wants to do ... but I have the feeling that I was thinking about wanting to do stuff like that at some point.

**Comment by xchoo** [comment]
I think my main gripe about the current code is the repeated elements in the constructor.

e.g.
inhibitable & inhibit_scale (although, inhibit_scale can be removed i think)
wta_output, wta_inhibit_scale, wta_synapse

**Comment by jgosmann** [comment]
I wonder, do we have any other networks where depending on the input arguments the network structure might change?

**Comment by xchoo** [comment]
No currently, no (well, maybe the BG network)

**Comment by tcstewar** [comment]
> We should probably create some guideline rules to ensure consistency across Nengo objects.

Yup.  :)  And I'm liking this general principle of looking to do this when there's multiple related parameters...  that might be an interesting guideline....

> Not sure if this is actually something someone wants to do ... but I have the feeling that I was thinking about wanting to do stuff like that at some point.

Ooo...  cool.  I hadn't thought of that.  Very much makes sense where there are parameters/options that clearly involve adding new structure to the network.

**Comment by jgosmann** [comment]
> No currently, no (well, maybe the BG network)

But that's only the same thing repeated over and over again depending on the number of actions.

> Yup. :) And I'm liking this general principle of looking to do this when there's multiple related parameters... that might be an interesting guideline....

I would probably add the requirement that something is added to the network.

**Comment by tcstewar** [comment]
> I think my main gripe about the current code is the repeated elements in the constructor.
> 
> e.g.
> inhibitable & inhibit_scale (although, inhibit_scale can be removed i think)
> wta_output, wta_inhibit_scale, wta_synapse

Definitely the case for the ```wta_*``` ones....  I do like the idea of removing inhibit_scale, though.  Would the idea be to sort of merge the parameters (i.e. a new parameter called ```inihibition``` which defaults to ```None``` but people can set it to 3.0 or something like that?

**Comment by tcstewar** [comment]
> > Yup. :) And I'm liking this general principle of looking to do this when there's multiple related parameters... that might be an interesting guideline....
> I would probably add the requirement that something is added to the network.

+1

**Comment by xchoo** [comment]
I was toying with that idea, but there is no 'default' value if you want to use inhibition. (the default value is current 1.5 - but the user wouldn't know that if it is all collapsed down into one parameter).

An idea I had was:
if the parameter = None or False, disable the feature
if the parameter = True, use the 'default' value
if the parameter = float value, use that value

The reason why I think the ```inhibit_scale parameter can be removed is because you can do it on the transform to the inhibitory input.

**Comment by tcstewar** [comment]
> I was toying with that idea, but there is no 'default' value if you want to use inhibition. (the default value is current 1.5 - but the user wouldn't know that if it is all collapsed down into one parameter)

Good point.

> The reason why I think the ```inhibit_scale parameter can be removed is because you can do it on the transform to the inhibitory input.

Ooo, that's an extremely good point.  :)  Yup, that's much more straightforward.

**Comment by jgosmann** [comment]
This is obsolete now as the associative memory has been rewritten in nengo_spa.
