### ISSUE TITLE
Associative memory breaks with vector vocab

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#783]
``` python
import nengo
import nengo.spa as spa
import numpy as np

upper = lambda x: map(lambda y: y.upper(), x)

names = upper(['John', 'Susan', 'Mary', 'Bob', 'Greg', 'Diane'])
other = upper(['foo', 'bar'])
words = names + other

model = spa.SPA(seed=9)
d = 32

with model:
    vocab = spa.Vocabulary(d, unitary=True, rng=np.random.RandomState(3))
    model._default_vocabs[d] = vocab

    for word in words:
        vocab.parse(word.upper())  # parsing adds the word

    subject_vocab = vocab.create_subset(names)
    print(len(subject_vocab.vectors))

    model.state = spa.Buffer(d)

    model.input = spa.Buffer(d)

    # model.name = spa.Buffer(d)
    # model.name = spa.AssociativeMemory(subject_vocab)
    model.name = spa.AssociativeMemory(subject_vocab.vectors)

    actions = spa.Actions(
        'dot(state, START) --> name = input',
    )

    model.bg = spa.BasalGanglia(actions=actions)
    model.thal = spa.Thalamus(model.bg)

    cortical_actions = spa.Actions(
        'state = START',
        'input = JOHN',
        )
    model.cortical = spa.Cortical(cortical_actions)

    print(len(subject_vocab.vectors))
```

The above script fails with error 

```
NameError: Left-hand module ' name ' from effect ' name = input' is not defined.
```

Also, if I use the vocab instead of the vectors (see the commented out line), then new vectors get added to  `subject_vocab`, which is unexpected.

**Comment by hunse** [comment]
Also, I'm not sure how I feel about automatically adding vectors to vocabularies. It might be nice to turn it off somehow, because having it on can lead to a lot of hard-to-detect bugs. Of course, for many scripts it's super handy, so I wouldn't want to get rid of it completely.

**Comment by jgosmann** [comment]
> Also, if I use the vocab instead of the vectors (see the commented out line), then new vectors get added to subject_vocab, which is unexpected.

Compare #731, #696, #699

**Comment by xchoo** [comment]
Technically, all spa modules should use vocabularies, and not vector lists. This issue is addressed in the ```assoc_mem_reorg``` branch. 

As for the adding of vectors to the vocabulary, it is a known issue. It has to do with the automatic calculation of a transform matrix between two vocabularies when you do a ```module1 = module2``` routing cortical rule. The ```spa_subvocab``` branch addresses this by adding a ```read_only``` option to vocabularies.

**Comment by jgosmann** [comment]
This will not be addressed in core nengo, but the documentation has been fixed and doesn't state that you can pass vectors lists any longer. nengo_spa will not allow to pass vector lists either, if you want to do this you can use one of nengo_spa's selection networks directly and set the appropriate transforms on the connections.
