### ISSUE TITLE
Redundant 'if' statement in Basal Ganglia?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#785]
While looking through the Basal Ganglia I found [this really weirdly if-statement](https://github.com/nengo/nengo/blob/master/nengo/spa/basalganglia.py#L57). It looks like the same condition is being repeated twice? @arvoelke is this the code that you wrote or was it @tcstewar?

**Comment by arvoelke** [comment]
Git `blame` shows it's my embarrassing copy-paste error. Feel free to make a PR with the correction.

**Comment by hunse** [comment]
Fixed in #786
