### ISSUE TITLE
Unable to pass in config object to CircularConvolution network

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#793]
The product network allows users to pass in a config object to override the default configs. The circular convolution network uses the product network but doesn't allow users to pass a config object, making it impossible for users to alter the configuration of the product network used inside the circular convolution network.

**Comment by Seanny123** [comment]
Is this no longer a bug given the conclusion of #790 ?

**Comment by xchoo** [comment]
Yes and no. The point of the bug being that all parameters configurable in the product network initialization should also be configurable when initializing the circular convolution ntework.

**Comment by Seanny123** [comment]
Now, that the config has been removed #814  the parameters do match up, so I'm a bit confused about what you're saying. Are there things in the Product network that you would like exposed and also passed up to the Circular Convolution network?

**Comment by tcstewar** [comment]
> The point of the bug being that all parameters configurable in the product network initialization should also be configurable when initializing the circular convolution network.

The only parameter for the Product network is now ```input_magnitude```, which CircularConvoluton already has.  So everything's covered.  So I'd say yes, this is no longer a bug (once #814 is merged).

**Comment by jgosmann** [comment]
#814 is merged, so is this still considered a bug?

**Comment by tbekolay** [comment]
> #814 is merged, so is this still considered a bug?

I'm going to say no :+1:
