### ISSUE TITLE
Update SPA code

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#798]
Some of the SPA code can be brought up to date / synchronized (i.e. updated to support the config system, and newer networks).

<hr>

The BG module:
- [x] Constructor should have ampa and gaba synapse parameters as well.
- [ ] Fix spacing around `+` operators.

<hr>

The compare module:
- [x] Has obsolete `direct` parameter (#841)

<hr>

The AssociativeMemory, Buffer, and Memory modules are being addressed in other PRs

**Comment by Seanny123** [comment]
Why is the `direct` parameter obsolete?

**Comment by xchoo** [comment]
Because you can use the config system to do that.

**Comment by Seanny123** [comment]
For consistency's sake, would it be worth changing the `spa.Compare` parameter `radius` to `input_magnitude` which the `Product` network uses?

**Comment by tcstewar** [comment]
> For consistency's sake, would it be worth changing the spa.Compare parameter radius to input_magnitude which the Product network uses?

Yup!  Good idea

**Comment by jgosmann** [comment]
> Fix spacing around + operators.

What spacing? What operators?
