### ISSUE TITLE
IPython 4/Jupyter adjustments

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#806]
Check the example notebooks in IPython 4/Jupyter. Apparently the markdown parser changed and requires now a space between the hashtags and the heading (that is `# foo` instead of `#foo`). There might be other adjustments necessary too.

**Comment by tbekolay** [comment]
I tested all of our notebooks in Jupyter and didn't see any issues. The only thing that came up was a warning in the console: `Deprecated widget Javascript path /static/widgets/js/*.js was used` However, looking through `nengo/ipynb.py` I can't see anywhere that we're doing this explicitly, so I'm guessing this is an internal notebook thing and not our fault. So, closing this! If we do run into any issues later, we can make new issues for them.
