### ISSUE TITLE
`spa.Compare` should inherit from the Product network

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#807]
The Product network is changing in #651 and will probably continue to change with time. When I changed `spa.Compare` to return a scalar, I didn't have the knowledge to make sure it inherited from the Product network or somehow used the product network. This error should be corrected. I'm pretty sure it will only require adding a bunch of pass-through nodes.

**Comment by xchoo** [comment]
See #798

**Comment by Seanny123** [comment]
Godammit. Today is not my day for Github.
