### ISSUE TITLE
StartedSimulatorException 

### ISSUE THREAD

**Issue by ivosonntag** [nengo/nengo#808]
I recently started learning how to use nengo, but already ran into a problem with the "Getting started" example.
I'm using the nengo_gui in chrome on Windows 10. The Python version is 2.7.10.

When I want to run the simulation e.g:

```
sim = nengo.Simulator(model)
sim.run(5.0)
```

the console returns the following:

```
Traceback (most recent call last):
  File "C:\Program Files\WinPython-64bit-2.7.10.1\python-2.7.10.amd64\lib\site-packages\nengo_gui\components\netgraph.py", line 65, in _reload
    exec(code, locals)
  File "<string>", line 39, in <module>
  File "C:\Program Files\WinPython-64bit-2.7.10.1\python-2.7.10.amd64\lib\site-packages\nengo_gui\monkey.py", line 29, in __init__
    raise StartedSimulatorException()
StartedSimulatorException
```

If I save the document and load it again, the simulation is initiated, but all consequent lines are being ignored.
This is the console output:

```
nengo.Simulator() started on line 39. Ignoring all subsequent lines.
```

So I'm not quite sure how to run the Simulator in the gui.
Any help would be appreciated.

**Comment by Seanny123** [comment]
Hey Ivo,

It looks like you're trying to run the simulator in the `nengo_gui` with code. You're actually supposed to hit the play button and not need to type the ```nengo.Simulator``` stuff. I can understand how that error message is a confusing for someone getting started and will make sure to change it.

**Comment by ivosonntag** [comment]
Hi Sean,
thanks for your fast reply!
I re-ran the script in Spyder and everything works fine.
For beginners it would be easiest to clarify that the examples should be
run in some Python interpreter rather than the gui/Jython.

cheers,
Ivo

**Comment by Seanny123** [comment]
I totally agree Ivo. We're in this awkward place where the GUI is so new
and incomplete that we haven't updated the documentation yet, but it's
definitely a priority. Thanks for reporting the bug!

**Comment by drasmuss** [comment]
This behaviour will be improved/documented in the rewrite of the GUI (currently underway).
