### ISSUE TITLE
Python 3 Travis-CI errors

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#809]
A recent commit prompted this error from Travis-CI:

Different tests were collected between gw1 and gw0. The difference is:
```
--- gw1
+++ gw0
@@ -292,86 +292,86 @@
```

According to Trevor, this is because tests run on different cores were returning different results. It's also discussed here:
https://github.com/pytest-dev/pytest/issues/437

Something to do with the way ```parameterize``` uses a python dictionary (which has a non deterministic ordering in Python >= 2.7)

Full job log is here: https://travis-ci.org/nengo/nengo/jobs/75833162

**Comment by Seanny123** [comment]
Did @tbekolay mention a way to fix this?

**Comment by xchoo** [comment]
I think he mentioned switching all of the tests over the ordered lists? Or something of the such.

**Comment by hunse** [comment]
This should be fixed by #830, but if anyone has trouble with this again, we can reopen it.
