### ISSUE TITLE
Filter banks in synapses

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#812]
Just throwing this out here as a possibility. The main reason to do this is speed, at the cost of complexity in the backend.

----

Right now, we implicitly assume that synapses will not change the shape of the signal being filtered. However, for speed reasons, it can be advantageous for a synapse to produce more values than are taken in -- essentially, to implement a filter bank instead of a single filter.

My use case: to filtering an incoming audio signal I use a bank of filters each picking out a particular frequency. I implemented a `Synapse` subclass called `Gammatone` that takes in `n` frequencies and emits those `n` values on each timestep; I can run this offline, but it won't work in Nengo because we assume that synapses produce the same shape of data that they take in.

Here's how I've incorporated it for now:

```python
frequencies = np.linspace(100, 200, 10)
with nengo.Network() as net:
    audio = nengo.Node(output=lambda t: sound[int(t / dt) % sound.size])
    gt = nengo.Node(size_in=frequencies.size)
    gt_p = nengo.Probe(gt, synapse=None)

    # 1. This is what I'm proposing to make possible
    nengo.Connection(audio, gt, synapse=Gammatone(frequencies))

    # 2. This works, but feels like a hack
    def wrap_gt(dt, freq):
        output = np.zeros(freq.size)
        step = Gammatone(freq).make_step(dt, output)
        def wrapped(x):
            step(x)
            return output
        return wrapped
    nengo.Connection(audio, gt, function=wrap_gt(dt, frequencies), synapse=None)

    # 3. This works, but is very slow compared to 2.
    #  (2. in nearly instantaneous, while 3. takes 7 seconds to run)
    for i, freq in enumerate(frequencies):
        nengo.Connection(audio, gt[i], synapse=Gammatone(freq))
```

Is 1. something that we might want to support?

----

Another alternative to explore that would give us the speed upgrades without needing to make API changes in the backend would be to implement an optimization step that pools together all synapses that are the same. For me, that would mean converting all of the `Gammatone` instances that get the same input signal to be a single `Gammatone` instance. But we could do something similar for any `Synapse` types.

**Comment by hunse** [comment]
My gut instinct is that this should be done as a Process. Then you can do whatever you want, including writing a custom builder if you need it, without having to add anything to Nengo.

**Comment by tbekolay** [comment]
A process attached to a node? That's essentially what I'm doing in 2., but yeah, you're right that I should go all the way and make it a process. You wouldn't be able to do that across a connection though, which is what the synapse gets you. But if it's not really obvious why that would be a good thing, then I think that's as much an answer as any ;)

**Comment by hunse** [comment]
Really the only advantage I see to allowing it on a Connection is that it's slightly more compact, and even then you could easily write a `connect_gammatone` function or something that will make intermediary node for you to do the filtering.

This is essentially the same conclusion I came to with convolution: I want populations that have convolutional encoders, but actually implementing those would be a lot of work, so I just do it as a process in a node. It makes it easier for backends, too, since they don't have to support many different types of encoders (dense, sparse, convolutional, etc.), they can just support simple dense encoders, and then as many of the fancy processes as they want. They can even fall back on the Numpy version of the process (just like with Nodes), so that they can at least have a slow version of the extra functionality without implementing it.

**Comment by tbekolay** [comment]
I'm convinced! Makes a lot of sense.

BTW, since it's sort of related, did we talk at some point about unifying synapses and processes? Synapses are kind of a special case of a process. `filt` is mostly `Process.run`, so we might save some code by unifying. Thoughts?

**Comment by hunse** [comment]
Yeah, I think we briefly mentioned it. I agree that unifying them is a good idea.

Also, I've found a way to use Process `make_step` functions in NengoOCL. I can just pull the values I need out of the step function closures; kind of hacky, but it works well.

**Comment by tbekolay** [comment]
Very cool! OK, I'll implement the unifying since I've been staring at synapse code for a long time this past week. I'll review/merge your synapse related PRs first though.
