### ISSUE TITLE
Things to change in 3.0

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#822]
Figured we'd better track these, or else we're unlikely to actually do it.

Should be completed before switch-over:
- [ ] Builder refactor
- [ ] Nengo GUI re-write

Remove Python 2.6 support (should list out specific things):
- [x] Remove support note from the README
- [x] Remove a bunch of the utility functions (`nested` comes to mind)

Remove obsolete things:
- [ ] Remove all `ObsoleteParams`, like `ObsoleteError` for `Connection.modulatory`
- [ ] Remove all things attached to `DeprecationError`, like  `EnsembleArray.neuron_nodes`
- [ ] Remove all `self.tau` attributes from the learning rules

Switch over to `nengo_spa`:
- [ ] remove support for underscore notation in SPA
- [ ] remove deprecation warning for `spa.SPA()`
- [ ] `spa.Memory` and `spa.Buffer`, which means changing the SPA test 
- [ ] if `nengo_gui` supports `nengo_spa` and `nengo_spa` reaches a `1.0` release, then remove `nengo.spa` entirely

Deprecate:
- [ ] [`ProbeDict` should be renamed](https://github.com/nengo/nengo/issues/1388)
- [ ] Change `nengo.utils.connection.target_function` to raise `DeprecationError`

**Comment by jgosmann** [comment]
Does nothing in 2.1 break Python 2.6 compatibility?

**Comment by tbekolay** [comment]
Not yet, I don't think... I don't know if anyone's actively tried, but the unit tests run in 2.6 at least.

**Comment by Seanny123** [comment]
Are we planning on completely removing `nengo.spa` from `nengo` or are we leaving some sort of basic skeleton? Because the current state of this issue seems to be the latter.

**Comment by tbekolay** [comment]
> Are we planning on completely removing nengo.spa from nengo or are we leaving some sort of basic skeleton?

Hm... I think I was originally planning to do this, but I hadn't anticipated that nengo_spa would change as rapidly as it's currently changing. So, my current feeling is to leave `nengo.spa` as is for 3.0 but add deprecation messages everywhere. We'd remove it fully the first major release after `nengo_spa` has a stable (1.0) release.

**Comment by Seanny123** [comment]
Alternatively, if `nengo_spa` reaches 1.0 before `nengo` reaches 3.0 would you be comfortable with removing it?

**Comment by tbekolay** [comment]
Could be convinced yep.

**Comment by tcstewar** [comment]
> Are we planning on completely removing nengo.spa from nengo or are we leaving some sort of basic skeleton? Because the current state of this issue seems to be the latter.

Other than nengo_spa still being in a state of possible change, there's also the limiting factor that we don't yet have a good way of having the spa tutorials showing up in the GUI when you install nengo_spa.  We've got some of the infrastructure for that in place, but it hasn't been done yet.  So for now I'd lean to keeping `nengo.spa` in place for 3.0.

**Comment by jgosmann** [comment]
> Other than nengo_spa still being in a state of possible change, there's also the limiting factor that we don't yet have a good way of having the spa tutorials showing up in the GUI when you install nengo_spa.

That should be fairly simple to add. I just didn't do it because of the ongoing refactoring.

**Comment by drasmuss** [comment]
Closing this, as we have created more specific issues to track these various TODO items for the 3.0 release.
