### ISSUE TITLE
Method to convert model to direct mode only where possible

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#829]
I have a somewhat complicated network which I would like to run in direct mode. In theory this can be done by setting the `neuron_type` in the model config to `nengo.Direct()`. However, I have some inhbitory populations where I connect to the neurons and those raise an exception if I set them to direct mode. It would be useful if there were a method which would set all ensembles where I do not connect to the neurons to direct mode and leave everything else untouched.

Not exactly sure what the best way to implement this is ... for now I'll probably go through my model and manually set ensembles to `nengo.LIF()` where needed.

**Comment by studywolf** [comment]
yeah i ran into this a bunch too, and i ended up doing the same thing where you specify ```neuron_type=nengo.LIF()``` for those that need to be in neurons and then change the config to direct to get everything else going. Another situation where i needed to keep things out of direct mode, aside from inhibition, was with anything that depends on saturation, but the inhibition case you could at least check for.

**Comment by tcstewar** [comment]
That sounds like it'd be a useful utility function.  And, indeed, with some careful mucking about with Nodes and modifying the functions computed on Connections I'm pretty sure you could even make the inhibitory populations and saturation work, if we wanted to get fancy.  I might even have some code around where I tried that....

But I could definitely see something like

```python
nengo.utils.convert.to_direct(model)
```

as a built-in helper function to do this sort of thing.

**Comment by drasmuss** [comment]
We added this here https://github.com/nengo/nengo/blob/master/nengo/utils/network.py#L33
