### ISSUE TITLE
Things that need refactoring

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#831]
- [x] The `basal_ganglia.on_add` function should be reduced in complexity as discussed in #828 
- [ ] A lot of the neuron equation code assumes that `dt` and `synapse` is variable. This might be hurting performance

**Comment by jgosmann** [comment]
In the new SPA system there are no `on_add` methods anymore, which resolved the first point. I have no idea about the second point, but we'll hit this issue eventually on our quest of going through old issues. :crossed_swords:

**Comment by drasmuss** [comment]
We've made a number of changes/improvements to the neuron implementation since this was created; we'll create new issues for any more specific ideas that come up.
