### ISSUE TITLE
Create a spa wrapper for the Circular Convolution network

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#847]
In Nengo GUI, I want to be able to visualise the output of a CircularConvolution network in the same way that I visualise the output of all other SPA modules.
 
- Is this a good idea?
- What should this module be named? `spa.CircularConvolution`?

**Comment by tcstewar** [comment]
I'd go with ```spa.Binding```

**Comment by xchoo** [comment]
Actually, thinking about it, it would be nice to have a generic module that you can pass a network to (as well as input and output vocabularies) and it'll handle the wrapping.

**Comment by xchoo** [comment]
:+1: for ```spa.Binding``` or ```spa.Bind```

**Comment by Seanny123** [comment]
@tcstewar I didn't like that name initially because sometimes you're also unbinding, but now I realise that unbinding is just binding the inverse

@xchoo do you mean that for the user-side or to use in Nengo code as well to simplify `spa.Compare` and `spa.Bind`? I think it has limited utility either way because once you put something into a module, you generally want to have much different parameters being passed to it

**Comment by xchoo** [comment]
To use in Nengo code. (i.e. you could make a module by doing:
```
net1 = nengo.Network()
with net1:
    # Add stuff to net1

spa_net = spa.SPA()
with spa_net:
    spa_net.my_module = ModuleWrapper(net1, [vocab params])
```

**Comment by tcstewar** [comment]
> Actually, thinking about it, it would be nice to have a generic module that you can pass a network to (as well as input and output vocabularies) and it'll handle the wrapping.

Hmm, I'd disagree on that, but that's because I can't think of any reliable way to do that automatic wrapping that's flexible enough and clearer than just writing the 7-line module that should implement this.  

For the Binding case, the code ends up looking something like this:

```
class Binding(spa.module.Module):
    def __init__(self, D):
        super(Binding, self).__init__()
        with self:
            self.circconv = nengo.networks.CircularConvolution(dimensions=D, n_neurons=50)
        self.inputs = dict(A=(self.circconv.A, D), B=(self.circconv.B, D))
        self.outputs = dict(default=(self.circconv.output, D))
```

(with perhaps a bit more logic to handle a passed-in vocab).  It's not clear to me what the ```[vocab params]``` you're envisioning would do, or how it would figure out what the inputs and outputs of the Module would be.

**Comment by xchoo** [comment]
Oh yeah. I was just spitballing. :laughing:
