### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#851]
A TODO list of things we need to update in the docs for the 2.1 release

- [x] Fix docstring "parameters" and "arguments". Many of these have been removed (see e.g. Connection). Also, it would be nice to have a consistent ordering (I would prefer the same order as they appear in the constructor).

**Comment by arvoelke** [comment]
My initial feeling is to order the parameters by how they appear in the constructor, and the attributes alphabetically (since it may include additional variables that need to be visually searched).

**Comment by hunse** [comment]
> the parameters by how they appear in the constructor, and the attributes alphabetically

Agreed.

**Comment by tbekolay** [comment]
Done in #959.
