### ISSUE TITLE
What to do with `input_magnitude` argument of `spa.Compare` and `spa.Bind`?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#854]
Both `spa.Compare` and `spa.Bind` have `input_magnitude` arguments because the networks they are wrapping also have that argument. Is this necessary? Should that argument be removed and set to something more logical?

I was talking to @xchoo about this and he recommended that they be removed and both set to 3.5/sqrt(dimensions) due to the nature of semantic pointers being sampled from the distribution sqrt(dimensions). What does everyone else think?

I may have mis-represented Xuan's arguement. Feel free to edit the post to clarify it.

**Comment by tcstewar** [comment]
That sounds right to me, although we'd also need a notebook that systematically explores the effect of adjusting that parameter -- it's not clear to me that both of those situations should be using the magic number of ```3.5/sqrt(D)```.   But I do think there is some value based on the number of dimensions that should be used.

**Comment by xchoo** [comment]
I've found that ```3.5/sqrt(D)``` works for ```D > 64```. For lower ```D```, decreasing the scaling factor is the thing to do. There is also a way of determining the scaling factor to use. I believe it's in the ```spa-opt``` branch?

**Comment by Seanny123** [comment]
> I believe it's in the spa-opt branch?
Yep, so I guess we just have to wait for that to be merge and then we'll apply it to this issue?

**Comment by tcstewar** [comment]
Did you find that scaling factor for circular convolution or for the dot product?

**Comment by xchoo** [comment]
For the dot product. The scaling factor for the circular convolution (i.e. 1) is correct I believe.

**Comment by jgosmann** [comment]
`input_magnitude` gets removed in the new-spa. It will assume everything to be unit vectors. Where this is not the case inputs and outputs can be scaled accordingly.
