### ISSUE TITLE
Improve labels of Thalamus objects

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#860]
Would it be possible to label the thalamus object according to the actions they are contributing to for easier understanding of the Thalamus circuit in the GUI? For example, in this code:

```
import nengo
import nengo.spa as spa

D = 32  # the dimensionality of the vectors

model = spa.SPA()
with model:
    model.vision = spa.Buffer(D)
    model.memory = spa.Memory(D)

    actions = spa.Actions(
        'dot(memory, A) --> memory=B',
        'dot(memory, B) --> memory=C',
        'dot(memory, C) --> memory=D',
        'dot(memory, D) --> memory=E',
        'dot(memory, E) --> memory=vision',
        )

    model.bg = spa.BasalGanglia(actions)
    model.thalamus = spa.Thalamus(model.bg)
```

I would expect each of the `action` ensembles in the `action` network, as well as the `gate` ensembles and `channel` networks to be labeled according to what rule they're implementing.

My one concern is that this might make the thalamus a bit crowded in terms of labels, but I figure if a user really wants to dig into it anyways, they can expand it themselves. I'd rather give too much information that requires a little bit of sorting for someone who's curious than confusing information in this case.

**Comment by tbekolay** [comment]
This would help clarity a lot, I think! It could only be done for `spa.Thalamus` and not necessarily `net.networks.Thalamus`, but that's to be expected.

**Comment by jgosmann** [comment]
Check out #1014. I think, its doing exactly what you want.

**Comment by jgosmann** [comment]
will be fixed in new-spa-overhaul
