### ISSUE TITLE
allow spa.Actions to add more arguments after being initialised

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#861]
For the TOH, I have a build process where I add more production rules if I have more disks. I can't do that very elegantly right now because `spa.Actions` can't be modified after it's initialised. I would suggest adding a function `spa.Actions.add()` that would accept arguments in the same way as the `spa.Actions` builder.

Is this a good/bad idea?

**Comment by tcstewar** [comment]
Sounds fair to me!

**Comment by jgosmann** [comment]
Couldn't you build up the string of actions dynamically and once it's complete you instantiate `spa.Actions`? Though, `spa.Actions.add()` is probably clearer.

**Comment by Seanny123** [comment]
It's pretty easy to use the splat operator to pass in a tuple or a dict as
arguments, but it gets really messy once you have a mix of both. I'd rather
just go with the intuitive clear version that requires less Python magic.

**Comment by xchoo** [comment]
This is what I'm currently doing for spaun:
```
action_group1 = ['this --> that', 'this --> other']
action_group2 = ['cow --> moon']
...
all_actions = action_group1 + action_group2 + ...  # Concatenates all the actions together

actions = spa.Actions(*all_actions)
```

**Comment by Seanny123** [comment]
Right, but keep in mind that you can also have actions in the form of a dictionary

`key_actions = {A='this --> that', B='this --> other'}`

And you can really combine them efficiently until you pass them in as arguments to `spa.Actions` which isn't really intuitive or clear to someone who's reading your code.

**Comment by xchoo** [comment]
Oh. Right. I've never used the dictionary method before (never needed to name each action. haha)
