### ISSUE TITLE
Add biological plausibility notes to network docstrings

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#877]
In some situations, we've optimized networks to make them more robust / faster / more charming, but at the cost of biological plausibility. It's a subtle thing of course, but pink flags might be things like synaptic filters that can't be linked to known synaptic dynamics, and nonlinearities whose corresponding error signals would be difficult to generate (as these would be necessary for development).

At the dev meeting, the resolution was basically to add some notes to the docstrings in networks that we provide with Nengo noting areas which may not be biologically plausible. Something more objective would be nice in the future, but like, the far off future.

**Comment by drasmuss** [comment]
See #878, we think adding some kind of "biological plausibility checker" would be a cool idea, but we don't have any plans to add that based on our current development resources/priorities.
