### ISSUE TITLE
spa.AssociativeMemory give obscure memory when empty vocab given

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#879]
To replicate run:
```
import nengo
from nengo import spa

D = 32
vo = spa.Vocabulary(D)
model = spa.SPA()

with model:
    model.ass = spa.AssociativeMemory(vo)
```

A warning that the problem is that the vocab is empty would be appreciated

**Comment by tcstewar** [comment]
Wow, that dies in a particularly nasty way, too, crippling nengo_gui.  So that's also a bug that should be fixed....

**Comment by Seanny123** [comment]
Would you mind clarifying what you mean by "crippling" in an issue in `nengo_gui`?

**Comment by tcstewar** [comment]
> Would you mind clarifying what you mean by "crippling" in an issue in nengo_gui?

Done in https://github.com/nengo/nengo_gui/issues/591

**Comment by tcstewar** [comment]
Edit: never mind; the gui crash thing was my fault, due to me being on a weird branch with weird changes.

**Comment by Seanny123** [comment]
What type of error should this throw? I was thinking maybe `KeyError`.

**Comment by xchoo** [comment]
I gave it a ```ValueError``` because the vocabulary passed to the assoc mem is invalid for said assoc mem.
