### ISSUE TITLE
Look into IPython traitlets

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#882]
Note: this is mostly a note to self.

Seems like our config / params system has eerie similarities to [IPython's traitlets](http://traitlets.readthedocs.org/en/latest/). Since it's now been extracted from the rest of the IPython source, and is pure Python, it would be pretty trivial to include as a dependency if it's worth doing so (i.e., allows us to remove a good chunk of confusing code).

**Comment by jgosmann** [comment]
It probably won't be possible to the the `with` stuff to temporarily overwrite defaults. But I might be wrong.

**Comment by drasmuss** [comment]
It would be nice to separate out the Parameter system in Nengo, but the current system is working for us so we don't have any plans to rework it unless some new incentive comes up.
