### ISSUE TITLE
Setting subdimensions as vocab should not be allowed

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#884]
Right now, if you set a `spa.Vocabulary` object as the `subdimensions` parameter of `spa.State` no error gets throw. For example, consider the code below that does not, but should throw an error:

```
import nengo
from nengo import spa

vo = spa.Vocabulary(16)
model = spa.SPA()

with model:
    model.state = spa.State(16, vo)
```

I'm not clear if this means we just need stronger type checking for arguments in general or if this is a corner case. I'll investigate and update this issue once I figure it out.

**Comment by jgosmann** [comment]
Does it throw an error when building the model?

**Comment by Seanny123** [comment]
Nope

**Comment by jgosmann** [comment]
Fixed in new-spa-overhaul.

Feel like this exact same issue has been posted a quadrillion times. ;)
