### ISSUE TITLE
Default vocab assignment in SPA modules is awkward

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#886]
As discussed [here](https://github.com/nengo/nengo/pull/849), the way default vocabs are assigned in SPA modules is badly documented.

**Comment by s72sue** [comment]
These are two separate things:
1) Default vocabs get assigned when no vocab is passed to a SPA module (i.e., vocab=None)
2) An error is thrown when a vocab is passed to a SPA module, but its dimensions do not match the dimensions of the module. 

1) needs to be documented, but I don't see a problem with the error thrown in 2). It makes it clear that the dimensions of the vocab should be the same as that of the module.

**Comment by Seanny123** [comment]
Yeah, I made a mistake and thought that there was no error thrown. You're right the error thrown is actually fine and the other thing just needs to be documented.

**Comment by jgosmann** [comment]
Moved to nengo/nengo_spa#17.
