### ISSUE TITLE
Resetting the simulator without resetting probes or time

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#888]
For certain experimental setups, I've found it convenient to "batch" together all of my tests into a single run, and then collect all of the probe data together into a single array for offline analysis. Currently this is achievable, but there are a couple subtle issues:
- If you don't reset the simulator between tests, then the state of neurons/synapses can carry over across tests. In my case, this contaminates the results. Moreover, dynamical systems that are unstable or slowly decaying need to be inhibited, otherwise adding a pause in between won't solve the problem.
- If you do reset the simulator between tests, then you lose all of your probes, and so you need to manually combine them into your own array. Moreover, nodes lose their ability to distinguish between runs (unless you make them into callable classes and then modify some additional state), since time resets back to zero. 

As my workaround to both of these issues, I've copy-pasted the code from `sim.reset()` and deleted the parts that reset probes/time:

```
def soft_reset(sim):
    """Resets the simulator without resetting probes or time."""
    # copied from nengo/simulator.py
    logging.info("Resetting simulator at time %s", sim.time)
    for key in sim.signals:
        if key != '__time__':
            sim.signals.reset(key)
    # rebuild steps (resets ops with their own state, like Processes)
    sim.rng = np.random.RandomState(sim.seed)
    sim._steps = [op.make_step(sim.signals, sim.dt, sim.rng)
                  for op in sim._step_order]
```

I can put this into a PR, but before going through the effort I wanted to see if (a) something like this would be acceptable, and (b) would this make things too difficult for other backends that can't support such a soft-reset (not sure what our policies are regarding features with varying levels of support).

**Comment by mundya** [comment]
> (b) would this make things too difficult for other backends that can't support such a soft-reset

Soft-reset is fine for SpiNNaker.  That said I don't think there's any support for `reset` at all at the moment, shouldn't be too hard to add.

**Comment by adityagilra** [comment]
Hi,  
  
This is very useful!  
  
I've also extended this to do a soft reset i.e. without resetting time and probes, when using nengo_ocl   
`OCL = True` / `False` is used earlier to `import nengo_ocl` or not, and then `sim = nengo_ocl.Simulator(mainModel,dt)` or not.  
  
For soft reset:  
  
```
        if sim.closed:
            raise SimulatorClosed("Cannot reset closed Simulator.")
        if OCL:
            if seed is not None:
                raise NotImplementedError("Seed changing not implemented")
            # reset signals
            for base in sim.all_bases:
                #print(getattr(base, 'name', ''))
                # TODO: copy all data on at once
                if not base.readonly:
                    # clear a Signal.base only if it is not time
                    if getattr(base, 'name', '') != 'time' and getattr(base, 'name', '') != 'step':
                        sim.all_data[sim.sidx[base]] = base.initial_value
            for clra, ra in iteritems(sim._raggedarrays_to_reset):
                # TODO: copy all data on at once
                for i in range(len(clra)):
                    clra[i] = ra[i]
            sim._reset_rngs()
            #sim._reset_probes() -- commented: do not reset probes
        else:
            if seed is not None:
                sim.seed = seed
            # reset signals
            for key in sim.signals:
                # do not reset the time signal
                if key != '__time__':
                    sim.signals.reset(key)
            # rebuild steps (resets ops with their own state, like Processes)
            sim.rng = np.random.RandomState(sim.seed)
            sim._steps = [op.make_step(sim.signals, sim.dt, sim.rng)
                           for op in sim._step_order]
            ## clear probe data -- commented: do not reset probes
            #for probe in sim.model.probes:
            #    sim._probe_outputs[probe] = []
            #sim.data.reset()
            #sim._probe_step_time()
```

**Comment by arvoelke** [comment]
Closing this as the use-case is now covered by the batching features of `nengo-dl`: https://www.nengo.ai/nengo-dl/examples/from-nengo.html#Batch-processing.
