### ISSUE TITLE
Compare network doesn't check for dimensions mismatch

### ISSUE THREAD

**Issue by s72sue** [nengo/nengo#889]
Compare network doesn't make sure that the vocab dimensions are the same as the module dimensions, i.e., the check `vocab.dimensions != dimensions` is missing. Ideally an error should be raised in case of a dimension mismatch, just like in other SPA modules.

**Comment by xchoo** [comment]
This might warrant a different discussion, but I think that spa modules should get rid of the ```dimensions``` property altogether. Instead, the primary property of each module should be the vocabulary you pass into it (you can pass in an integer, but it'll use the default vocabulary of that dimensionality -- as it is currently)

**Comment by s72sue** [comment]
That will definitely allow us to get rid of all those dimension checks. However, it might be confusing for a user to pass in an integer for a vocab argument. And if they don't pass in an integer, then they will be forced to pass a vocab (which is optional right now).

**Comment by xchoo** [comment]
Right. I guess my point is that the vocabulary parameter shouldn't be optional. Perhaps a way of getting the default vocabulary (```spa.default_vocab(D)```)?

**Comment by tcstewar** [comment]
> Right. I guess my point is that the vocabulary parameter shouldn't be optional. Perhaps a way of getting the default vocabulary (spa.default_vocab(D))?

Gah...  I'd really prefer not to have to do

```python
with model:
    model.state = spa.State(model.get_default_vocab(D))
```

instead of 

```python
with model:
    model.state = spa.State(D)
```

I will note that we have a precedent for doing something like this: the ```synapse``` parameter accepts a float, automatically changing it into ```nengo.Lowpass(value)```.  That's sort of the same thing that's happening here, so I could kinda see merging the parameters into one...

**Comment by xchoo** [comment]
I'm fine with ```spa.State(D)``` as well. We'd just have to document that if you pass it an integer, it uses the default vocabulary of the given dimensionality.

**Comment by tbekolay** [comment]
I wouldn't use the `synapse` parameter as an example of good API design; I'd rather it have to be fully specified, but there's too long of a precedent of just using numbers to bother making that change. It's worth brainstorming other options, but yeah, I don't have any suggestions :)

**Comment by s72sue** [comment]
I think we should just document that if you do not pass it a vocab, the default vocab of the specified dimensionality will be used. We should probably keep it a secret that its possible to pass an integer for the vocab argument and still use the default vocabulary. Basically you should pass in a vocab only if you want to use a vocabulary different from the default one for that particular dimension.

**Comment by tcstewar** [comment]
> We should probably keep it a secret that its possible to pass an integer for the vocab argument and still use the default vocabulary.

I think I'd intended the idea to be that we could consolidate the ```vocab``` and ```dimensions``` argument into one argument: it'd be called ```vocab``` and if you passed in a Vocabulary that'd be the same as currently doing ```spa.State(v.dimensions, vocab=v)``` but if you passed in an integer that'd be the same as currently doing ```spa.State(16)```.  So people could either do ```spa.State(16)``` or ```spa.State(v)```.

**Comment by s72sue** [comment]
I like the idea of consolidating them into one, however I think no one would end up using spa.State(16) and most people will use spa.State(V). This is because its counter-intuitive to pass in an integer for a vocab (since the argument name ```vocab``` makes it sound like a vocabulary object is being expected). However, if we clearly document this, then I can see it being useful.

**Comment by jgosmann** [comment]
Has been consolidated in new-spa-overhaul.
