### ISSUE TITLE
Building a model with a node that has a node as a parameter causes unbounded memory usage

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#892]
Discovered this after making a typo in my code. Minimal example:

```
with nengo.Network() as model:
    node1 = nengo.Node(output=lambda t: t)
    node2 = nengo.Node(node1)

sim = nengo.Simulator(model)
```

The code is meant to be ```node2 = nengo.Probe(node1)```, but my brain farted. :smile:

**Comment by hunse** [comment]
Weird. It actually doesn't seem to be a builder problem; I can reproduce it even without making a simulator. I'll find it.
