### ISSUE TITLE
Add AdEx neuron

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo#900]
The adex (adaptive exponential LIF) neuron is simple and has been used to do a very good job of reproducing a wide variety of cortical neuron types.

In short, this is something that would be great to include in Nengo:
http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004165

**Comment by hunse** [comment]
I've started working on this in the [`reif` branch](https://github.com/nengo/nengo/tree/reif). There are two versions of the model in the paper, the EIF (exponential integrate-and-fire), which is fully implemented and working, and the rEIF (refractory exponential integrate-and-fire), which is still in progress.

**Comment by drasmuss** [comment]
Since there hasn't been any demand for this in the last 5 years we'll close this, but if there was renewed demand for an AdEx neuron we'd be happy to reconsider.
