### ISSUE TITLE
Silly spa action should throw an error

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#901]
This code does not throw an error, despite the fact that any assignment that involves itself (in this case `mem=mem*ONE` and `mem=mem*~ONE`) is a bad idea.

```
import nengo
from nengo import spa

from collections import OrderedDict

D = 32
vocab = spa.Vocabulary(D, unitary=["ONE"])
number_dict = {"ONE":1, "TWO":2, "THREE":3, "FOUR":4, "FIVE":5,
               "SIX":6, "SEVEN":7, "EIGHT":8, "NINE":9}
number_ordered = OrderedDict(sorted(number_dict.items(), key=lambda t: t[1]))

number_range = 4
vocab.parse("NONE")
vocab.parse("ONE")
number_list = number_ordered.keys()
for i in range(number_range):
    vocab.add(number_list[i+1], vocab.parse("%s*ONE" % number_list[i]))

model = spa.SPA(vocab)

with model:
    model.vision = spa.State(D)
    model.motor = spa.State(D)
    model.mem = spa.State(D, feedback=1)
    
    actions = spa.Actions(
        "dot(vision, START) --> mem=ONE",
        "dot(vision, PLUS) --> mem=mem*ONE",
        "dot(vision, MINUS) --> mem=mem*~ONE",
        "dot(vision, DONE) --> motor=mem"
    )
    
    model.bg = spa.BasalGanglia(actions)
    model.thal = spa.Thalamus(model.bg)
```

It would be helpful to inform the user that this type of assignment is not allowed, since opening a feedback loop with a module not something `spa.Actions` is intended to do.

**Comment by xchoo** [comment]
Why is this having a recurrent statement a bad idea? The spa actions module is just doing what is was told to do.

**Comment by Seanny123** [comment]
What do you expect it to do and how is spa.actions doing it?

**Comment by xchoo** [comment]
I expect it to create a gated recurrent connection on ```mem```. Now, that's not to say that the recurrent connection will work properly. One might expect to have it increment nicely. I expect it to spin wildly out of control.

**Comment by xchoo** [comment]
So, pulling it up in the gui, i see that it does create a gated recurrent connection.

**Comment by Seanny123** [comment]
The actual behaviour is that nothing happens, which I interpreted as a bit of a bug.

**Comment by Seanny123** [comment]
I guess it comes down to the fact that spa.Actions has a lot of limitations on what it can and cannot do, based off what is useful to do. My hypothesis is that this is never a useful thing to do, but I'm not 100% sure on that.

**Comment by xchoo** [comment]
Hmmm. I'm not sure what you mean by "nothing happens". When I run the network, values are changing for me. Please elaborate.

**Comment by Seanny123** [comment]
Ah. Nvm. I must have run it or read it incorrectly last time. In which case, I'm fine with allowing the user to write this code.
