### ISSUE TITLE
dot() not allowed in Cortex?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#903]
Can I enable the `dot` operator in `spa.Cortical` given it only changes the kind of connection made and does not create any intermediary networks?

**Comment by Seanny123** [comment]
After talking to Terry and reviewing this conversation, putting compares in `spa.Cortical` should be allowed, but is really that much of a priority given that there aren't any networks in SPA that accept scalar inputs.

**Comment by jgosmann** [comment]
This should be resolved by #1014, but I haven't verified this yet.

**Comment by jgosmann** [comment]
I'm pretty sure that this is resolved by #1137.
