### ISSUE TITLE
Why are transforms allowed from pass-through nodes but not functions?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#904]
I was trying to create a dot product between the output of an ensemble array and I noticed that I could accomplish this with a transform, but not a function, since functions aren't allowed on pass-through nodes. I was surprised that a transform was allowed, given that between the pass-through node and my next node, there technically isn't any connection weights to implement that transform, so I'm not clear on why it should be allowed.

I feel like this was discussed in a previous Nengo meeting? I think the conclusion was that this type of transform should trigger a "biologically implausible" error?

If this actually shouldn't be allowed, should there be a utility for adding a transform to the output of an Ensemble Array, just like there is for adding a function?

**Comment by xchoo** [comment]
Transforms are allowed because a transform is linear (which means it can be rolled into either the afferent or efferent weight matricies).

**Comment by Seanny123** [comment]
So I can see that making sense between the EnsembleArray and the node, but what about node-to-node connections?

**Comment by jgosmann** [comment]
As long as you have neurons in the beginning and neurons in the end, all the transform matrices can be multiplied together to a single linear transform which can be rolled into the neural weight matrix.

**Comment by hunse** [comment]
Does this explanation make sense, @Seanny123?

**Comment by Seanny123** [comment]
Not totally, but I'll need to do some thinking to explain why. When I
figure it out, I'll re-open the issue.
