### ISSUE TITLE
For convolution effects in the Cortical, the connections do not appear in the nengo_gui

### ISSUE THREAD

**Issue by s72sue** [nengo/nengo#905]
The connections for convolution effects do not appear in the nengo_gui since the convolution network is being created in the 'cortical' context. Since cortical is not represented by a separate entity in nengo_gui, the convolution network as well as the connections do not show up. I think it would make sense to create the convolution network in the context of the target module.

**Comment by Seanny123** [comment]
What network did you try this out with?

**Comment by s72sue** [comment]
The network in the cortical tests (`test_convolution` method) in nengo/spa/test/test_cortical.py

**Comment by Seanny123** [comment]
After discussing during the meeting and with Terry, the convolution networks should be moved from the `cortical` network into the target network, thus enabling us to eliminate the `cortical` network

**Comment by Seanny123** [comment]
Resolved via #906
