### ISSUE TITLE
Thalamus spa.Buffer usage

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#908]
[This line of code](https://github.com/nengo/nengo/blob/master/nengo/spa/thalamus.py#L200) in `spa.Thalamus` needs to also include `spa.State`.  Or ideally, it should just be replaced with a more reasonable methodology of getting the dimensions of SPA modules.

**Comment by tcstewar** [comment]
Good catch.  Although I assume you mean ```spa.State```.

This sort of thing might be a good candidate for aspects of the Factory @jgosmann  was talking about for the spaopt branch.

**Comment by jgosmann** [comment]
Fixed in new-spa-overhaul
