### ISSUE TITLE
Seed and caching documentation

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#914]
It would be nice to have some documentation on how the cache works and how to leverage it by setting seeds. In particular, I'm a little confused how the seed system works. For example, if I set a seed at the top network of my network hierarchy, does it get passed down automatically to the lower networks?

**Comment by tbekolay** [comment]
> if I set a seed at the top network of my network hierarchy, does it get passed down automatically to the lower networks?

That seed does not propagate down to lower networks, but the process that generates the seeds for those lower networks is seeded by the network that owns it, so if you set a seed on the top-level network, the entire build process becomes deterministic (assuming the model stays the same). Additionally, we assign seeds to networks first, meaning that if you change something in one subnetwork, it should affect the build process for a different subnetwork.

**Comment by jgosmann** [comment]
> Additionally, we assign seeds to networks first, meaning that if you change something in one subnetwork, it should affect the build process for a different subnetwork.

I suppose you meant "should **not** affect the build process"?

**Comment by tbekolay** [comment]
That is what I meant yeah.

**Comment by Seanny123** [comment]
I consider this resolved by via the [documentation section Improving Performance](https://www.nengo.ai/nengo/improving_performance.html).
