### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by MarcoSaku** [nengo/nengo#916]
Hi all! I'm working on Spiking Neural Networks and I found this framework, it seems very interesting!
I have two initial questions (surely stupid questions :D).
I know that this is the place where ask about issues, but I don't know where I can ask these things.

1) I saw that it is implemented the Leaky-Integrate-and-fire neuron, it is possible to have the Integrate-and-fire-neuron (without leaky)
2) I read somewhere that this framework is based on Theano (maybe I am wrong): is it possible to use the GPU computation like Theano?

Thanks all

**Comment by tbekolay** [comment]
Hello! We don't have a good place to ask general questions at the moment, so here's as good a place as any!

1) Currently we don't have a non-leaky integrate-and-fire model implemented, but it wouldn't take long to implement. If you don't mind, could you make a separate issue to request that we implement integrate-and-fire neurons?

2) There was an early experiment using Theano to back Nengo simulations; unfortunately, it didn't work out very well, as Nengo requires many updates to be evaluated on each timestep. However, it is possible to utilize the GPU if your network needs it. It's worth nothing that Nengo is pretty fast without the GPU if you have a good NumPy install, but if you do need to eke out some extra speed, then you can use your GPU with OpenCL by using the [NengoOCL simulator](https://github.com/nengo/nengo_ocl).

Hope that's helpful!

**Comment by MarcoSaku** [comment]
Thanks for the reply! I open a thread in pull request regarding the IF Neuron implementation.
I will try NengoOCL! :D

**Comment by bmorcos** [comment]
Take a look at [forum.nengo.ai ](https://forum.nengo.ai) for questions and discusison :smile:

**Comment by retiredtoo** [comment]
This too is a question, if a stupid one.  I have no background in neurology/computational cognition and my last electrical engineering course was 50+ years ago but I'm trying to learn with Nengo.  I've run it with python on jupyter with the gui app.  I'm using Nengo 2.6 and trying to sync it with the book (published 2013).  The screen captures all show an app that I haven't been able to generate so the instructions/text and the 2.6 version of Nengo that I use, seem somewhat hazy.  What is the best way too self-instruct using Nengo?

**Comment by tbekolay** [comment]
Hi @retiredtoo! The tutorials in the How to Build a Brain book have been updated to work in more recent versions of Nengo; see https://github.com/nengo/nengo_examples/tree/master/htbab_tutorials which includes Jupyter notebooks and .py versions which work with [Nengo GUI](https://github.com/nengo/nengo_gui). I think that going through those tutorials (especially along with the book) is a nice way to get up to speed with Nengo! And if you have any questions when going through those tutorials, post a question at [the Nengo forum](https://forum.nengo.ai/) and we'll help as best we can!

**Comment by tbekolay** [comment]
Thanks for letting us know! I'll make sure the GUI team knows about this.

**Comment by celiasmith** [comment]
@retiredtoo I think you may need to do a couple more steps if you want to run those tutorials directly in Nengo.  Right now, they are made to be run in jupyter notebooks.  However, if you want to run them in Nengo, make a directory, copy all the .cfg files in there, and then for each tutorial, copy all the *code boxes only* from the .ipynb into the gui, and save that as a .py file.  You can see the code boxes online, e.g. for the first tutorial: https://github.com/nengo/nengo_examples/blob/master/htbab_tutorials/ch1-singleneuron.ipynb

Sorry this isn't easier!  And, if you do go through these steps for all the tutorials, please let us know and perhaps we could post the .py files for others to use 😄

**Comment by jgosmann** [comment]
Aren't the GUI-compatible versions of the tutorials bundled with the GUI?

**Comment by celiasmith** [comment]
@jgosmann is absolutely right, I had forgotten.  If you go to <file menu>->built-in examples->hbb_tutorials, they are all there.  ignore my previous instructions, although i think they indicate what your initial error was from (i.e. trying to load the .cfg into the regular nengo gui, where they are intended for jupyter notebooks).

**Comment by retiredtoo** [comment]
Thanks for reply....I did as instructed but my gui won't let me paste into
the python box and when I typed python code in I get a syntax error on
"%matplotlib inline" and further down on a line that starts with "neuron =
nengo.Ensemble...."  which dosen't make sense to me...so I'll go back to
this at some later time.  The notebook app doesn't give me any problems if
I don't use the .cfg files....and they have your instructions/explanations
which is what I need.
Thanks John

**Comment by retiredtoo** [comment]
I've downloaded the "SYDE 556/750: Simulating Neurobiological Systems"  course.  Some of the python code calls for a  syde556 module.  Does that come with the Nengo download?  My notebook app is not finding it.

**Comment by celiasmith** [comment]
sorry you can't run those parts as we aren't able to make that public.
