### ISSUE TITLE
Current release of nengo is behind nengo_gui

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#917]
I just noticed (thanks to a user email) that spa.State is not in the current release of nengo (2.0.2), but it is being used in the nengo_gui tutorials!  

Is it possible to do a 2.0.3 release with this commit https://github.com/nengo/nengo/commit/6d0b6f823ab17acbedeffe3cf26753d07aa9a104

Alternatively, we could revert the nengo_gui tutorials to earlier versions....

**Comment by tbekolay** [comment]
Do the tutorials work if you switch `State`s to `Memory`/`Buffer`? If so, that'd be a quicker fix... if not, we can do this release.

**Comment by tcstewar** [comment]
There's a whole bunch of documentation changes in the tutorials as well, due to the terms being merged together, and the new ```State``` having slightly different parameters and defaults, so I'd prefer not to revert them.  I can take a look at what that'd take though...  I'll start a branch with that.

**Comment by tbekolay** [comment]
It's not that much trouble to do a 2.0.3 release if it requires more than an hour or so of work. I can do it later today.

**Comment by tcstewar** [comment]
Hmm...  yes, if you could do a 2.0.3 release with that one commit, that's looking much easier than making the changes to the nengo_gui tutorials, testing those changes, then doing a 0.1.6 release of nengo_gui, and then undoing those changes again in a future release.

Sorry about this.  I really should have noticed that the ```spa.State``` changes were being included in the 0.1.5 release.  :(

**Comment by tbekolay** [comment]
OK, [released](https://github.com/nengo/nengo/releases/tag/v2.0.3) ([pypi link](https://pypi.python.org/pypi/nengo/2.0.3)). I tested this with a few of the Nengo GUI tutorials and they seemed to run fine, but please pip install `nengo==2.0.3` version and test it a bit. If it looks good, then close the issue!

**Comment by jgosmann** [comment]
It seems this can be closed ...
