### ISSUE TITLE
Integrate and Fire Neuron Model

### ISSUE THREAD

**Issue by MarcoSaku** [nengo/nengo#919]
Hi all! I would ask if it is possible to integrate in nengo the Integrate-and-fire Neuron model (without leaky). I think that it is similar to LIF Neuron.
Any help would be appreciated.
Regards,
Marco

**Comment by Seanny123** [comment]
Yep, it's quite possible. Assuming you've figured out the equations, you just need to follow the same process that can be found in the docs for the Rectified Linear Neuron: https://pythonhosted.org/nengo/examples/rectified_linear.html

**Comment by MarcoSaku** [comment]
Can't someone help me with the implementation?

**Comment by Seanny123** [comment]
What aspect of the tutorial are you having a problem with?

**Comment by MarcoSaku** [comment]
To implement Integrate-and-fire neuron I would start from LIF Neuron (I think that they are very similar also in the implementation). Debugging code using LIF Neuron I didn't understand some points:
1) The voltage updating of neuron is done in "neurons.py" in function "step_math" in class "LIF(LIFRate)"
``` python
dV = -np.expm1(-dt / self.tau_rc) * (J - voltage)
voltage += dV```
I think that the first term is the leaky term (where tau_rc is resistance parameter): could you explain me how is calculated J? It seems that it uses gain and bias to calculate it. In IF Neuron I need simply voltage=input+voltage, without any other parameter

2) If I debug the code, i will run the line above multiple times for each dt: I think that the voltage updating should be done once for each dt, isn't it?

**Comment by Seanny123** [comment]
If you look at the example from the link I posted, it's explained that J is a parameter indicating the input current to the ensemble.

**Comment by arvoelke** [comment]
As a side note, it should in theory be possible to get this by setting `tau_rc` to some negligibly low amount (say, `1e-6`), such that `dv` will be approximately zero. However, the problem occurs when Nengo automatically sets the gains and biases, which results in a gain of zero on the neuron (and so it doesn't respond to input). Just taking note of this because it seems more difficult than it should be.

**Comment by studywolf** [comment]
Hi Marco, 

the NEF is based around population decoding. To efficiently implement this the input signals to our neurons are typically represented in a low-dimensional 'vector space' signal (x), which needs to be transformed into input voltage for each neuron (J). To do this, each neuron has an encoder (e) which specifies how it responds to different parts of the vector space. To transform from vector space to voltage input we use 
J = (np.dot(x, e)*gain + bias)
and that's where the extra terms come in. If you weren't representing things in vector space and were tracking the inputs to each neuron you would be able to do J = input + J like you said. Does that help?

**Comment by hunse** [comment]
@arvoelke : Actually, to make a LIF neuron look like an IF, you want a really large `tau_rc`, and a short or zero `tau_ref` to remove saturation.

**Comment by MarcoSaku** [comment]
Thanks for your support! I would show you a simple example
``` python
import numpy as np
import nengo

model = nengo.Network(label='Two Neurons')
with model:
    neurons = nengo.Ensemble(2,1)
    neurons.neuron_type=nengo.LIF(tau_rc=0.000000001)
    neurons.gain = 1 * np.ones(neurons.n_neurons)
    neurons.bias = 0 * np.ones(neurons.n_neurons)

with model:
    sin = nengo.Node(0.5)

with model:
    nengo.Connection(sin, neurons,synapse=None)
    sin_probe = nengo.Probe(sin)  # The original input
    spikes = nengo.Probe(neurons.neurons)  # Raw spikes from each neuron
    voltage = nengo.Probe(neurons.neurons, 'voltage')  # Subthreshold soma voltages of the neurons

sim = nengo.Simulator(model)  # Create a simulator
print 'Run Network'
sim.run(0.10)  # Run it for 5 seconds
```
Setting tau_rc to that value, -np.expm1(-dt / self.tau_rc) is 1, in this way I deleted the leaky term. 
I setted te synapse=None so I have at each iteration J=0.5 for each neuron: but I don't know why the value is always 0.5, but sometimes I have J=[0.5 -0.5], J=[-0.5 0.5] etc..
There is some variable that modify the sign of J at each iteration, do you know which one? Of course in that case I will edit the updating formula in this way
```python 
dV = -np.expm1(-dt / self.tau_rc) * (J)
voltage += dV
```
Does it make sense for you? Thanks a lot

**Comment by studywolf** [comment]
Hi Marco, 

yup, you also need to take into account the encoders. The output of the node is in vector space, and on a connection to an ensemble to transform from a vector space signal to voltage you dot product with the encoder, then multiply by the gain, then add the bias to get J. 

```J = np.dot(x, encoders)*gain + bias```

So you can also set those to be 1 with 
```
neurons.encoders = np.ones((neurons.n_neurons, 1))
```
or you can avoid the encoders by connecting your input directly to the neurons with 
```
node_in = nengo.Node(output=np.ones(neurons.n_neurons))
nengo.Connection(node_in, neurons.neurons, synapse=None)
```

Also, as @hunse mentioned, you want to have a high ```tau_rc``` value. So you can get what you want with
```
import nengo
import numpy as np

model = nengo.Network(label='Two Neurons')
with model:
    neurons = nengo.Ensemble(n_neurons=2, dimensions=1)
    neurons.neuron_type=nengo.LIF(tau_rc=1e10)

    node_in = nengo.Node(output=np.ones(neurons.n_neurons))
    nengo.Connection(node_in, neurons.neurons,synapse=None)

    in_probe = nengo.Probe(node_in)  # The original input
    spikes = nengo.Probe(neurons.neurons)  # Raw spikes from each neuron
    voltage = nengo.Probe(neurons.neurons, 'voltage')  # Subthreshold soma voltages of the neurons

sim = nengo.Simulator(model, dt=.0001)  # Create a simulator
print 'Run Network'
sim.run(.01) 
```

which gives me

![image](https://cloud.githubusercontent.com/assets/2473097/12425671/e57ac3ba-bea3-11e5-8403-2afe8598b91b.png)

**Comment by xchoo** [comment]
Just a point of clarification, the 'leaky' part of the LIF model comes from the membrane capacitance of the neuron model. Essentially, the capacitance of the membrane allows charge to 'leak' out of the neuron. In an IF neuron model, there is no 'leak' out of the neuron. In essence, the capacitance of the membrane is infinite. Since `tau_rc = R_m * C_m` (`R_m` being the membrane resistance, and `C_m` being the membrane capacitance), to get the LIF model to behave like an IF model, you'd have to set `tau_RC = R_m * inf` (ie something really really big)

**Comment by hunse** [comment]
In practice, it doesn't have to be that big, and you probably want to remove the refractory time, too, since I've never seen the IF model used with a refractory period (though there's no reason why it can't be). So something like `nengo.LIF(tau_rc=100., tau_ref=0.)` is going to be very much like an IF neuron. I would stick away from huge `tau_rc` just for numerical reasons, though @studywolf and @xchoo are right, technically you want it to be as long as possible. But `tau_rc=100` means that the membrane voltage is going to take 100 seconds to decay to 37% of its original value, and after 1 second it's still going to be at 99% of its original value, so for stimuli changing faster than 1 second it's essentially an IF neuron.

**Comment by MarcoSaku** [comment]
Thanks all for the explanations!

**Comment by MarcoSaku** [comment]
Hi all! I would understand well how is calculated the input current J. As reported by @studywolf, J = (np.dot(x, e)*gain + bias). I set the gain and the bias manually. I don't know how x is calculated. In specific, I would understand how the synapse filters the input current. For example, if I set the synapse with `model.config[nengo.Connection].synapse = nengo.synapses.Alpha(0.005)`
I have 
`alpha(t) = (t / tau) * exp(-t / tau)`
I think that this alpha(t) is used to calculate x: if yes, could anyone explain me how? 
Thanks all.

**Comment by hunse** [comment]
We want `voltage += (J - voltage) * (1 - np.exp(-delta_t / self.tau_rc))`, but since `-np.expm1(-delta_t / self.tau_rc) = (1 - np.exp(-delta_t / self.tau_rc))`, we subtract to include that negative sign.

**Comment by drasmuss** [comment]
We have `nengo.SpikingRectifiedLinear` now, which is a style of Integrate and Fire model. In combination with using `nengo.LIF` with a large `tau_rc` value as discussed above, this probably covers most use cases. If anyone has use cases that aren't covered by these options, let us know!
