### ISSUE TITLE
Connection for Convolution operation

### ISSUE THREAD

**Issue by MarcoSaku** [nengo/nengo#920]
Hi all! I would implement a SNN in nengo that has the same architecture of Convolutional Neural Network for image classification: I get the weights and the biases from a trained CNN (in Theano for example).
I have to create the connections between the neurons in two layers simulating the convolution operation: for example if the size of the kernel is 5, I have to connect 5x5=25 neurons (the neurons covered by the kernel) of the previous layer with one neuron of the current layer.
Could anyone help me to implement it? At first glance, it seems that with nengo.Connection(A,B) it is possbile to connect each neuron of A with all the neurons of B. I need to specify the connections using the position of the neurons.
Any help would be appreciated

**Comment by arvoelke** [comment]
Hi, have you thought about using `nengo.Connection(A.neurons, B.neurons, transform=W)`, where `W` is a weight matrix with a row per neuron in `B`, and a column per neuron in `A`? This reference may also be helpful: https://pythonhosted.org/nengo/user_api.html (please excuse the brevity; sent from phone)

**Comment by hunse** [comment]
The things that you want for this are in PR #800. It has processes for convolution and for pooling. For examples of them in action, look [here](https://github.com/hunse/cuda-convnet2/blob/softlif/run_nengo.py#L164) and [here](https://github.com/hunse/cuda-convnet2/blob/softlif/run_nengo.py#L176).

**Comment by Seanny123** [comment]
Hey @MarcoSaku did our comments resolve your problem? If yes, would you mind closing this issue? If not, would you mind continuing the conversation at forum.nengo.ai?

**Comment by Seanny123** [comment]
Closing to keep the issue tracker tidy. If you still have this issue or related issues please post on the forums. (:
