### ISSUE TITLE
Make model.operators a property

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#927]
As discussed in #926, to encourage the use of `add_op`, `operators` should be changed to an property that returns a copy and the actual attribute should be named `_operators`.

**Comment by hunse** [comment]
It needs to return a tuple. Otherwise you can do `model.operators.append` and have it run but do nothing.

**Comment by drasmuss** [comment]
While this isn't a bad idea, it's also pretty low priority since this isn't user-facing. And since it hasn't come up in ~5 years, just going to close this. (It also might become redundant after the planned builder refactoring).
