### ISSUE TITLE
Include `dtype` in `NdarrayParam`

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#930]
Currently, if a user passes in a numpy array to an `NdarrayParam`, we use it as is. If they pass in a list, we make a `float64` numpy array. There might be situations, however, where we want to make sure that a particular param uses an int array, or something of that nature. One way to allow this would be add a `dtype` argument to the `NdarrayParam` which would ensure that all values use the correct dtype.

**Comment by hunse** [comment]
Yeah, sounds good. In the default case (`dtype=None`?), I assume we wouldn't enforce the dtype if the user passes an array. But if we have to cast (e.g. we get a list), would we make the dtype float64 (`np.asarray(x, dtype=np.float64)`) or let Numpy decide (`np.asarray(x)`)?

**Comment by tbekolay** [comment]
Agree about the default case! Letting Numpy decide makes sense, or we could have a configurable default like in #640... in most cases it should be a float of some precision.

**Comment by drasmuss** [comment]
Looks like we did this at some point (https://github.com/nengo/nengo/blob/master/nengo/params.py#L384)

**Comment by hunse** [comment]
7b06474
