### ISSUE TITLE
Print time spent on building model

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#937]
The progress bar shows how long it took a simulation to finish. It would be nice to have an output how long it took to build the model, too. (A progress bar for that would be even more awesome, but more complicated to implement.)

**Comment by hunse** [comment]
I do this in Nengo OCL with the logging system. I log info level messages timing various parts of the build process. I guess in Nengo we don't split up the build process in the same way, so it's harder to get info about how much time is spent building connections, ensembles, etc. 

An overall timing that we display to the user no matter what, as @jgosmann is suggesting here, should be quite easy and makes sense.

**Comment by tcstewar** [comment]
It'd also be nice if such a system could also have hooks in it that would allow nengo_gui to pass the information along as well....  :)

**Comment by xchoo** [comment]
I currently do it manually (i.e. using timestamps from `time.time`) for spaun builds.

**Comment by jgosmann** [comment]
> I currently do it manually (i.e. using timestamps from time.time) for spaun builds.

I know that I could do that, but sometimes I build a model and wonder afterwards how long it took.

**Comment by drasmuss** [comment]
I'm kind of the opposite, I'm constantly disabling the progress bar for every model I run because I'd rather not have information cluttering the console output unless I ask for it.  So not saying that we shouldn't put this in, just that it'd be nice if there was a way to turn it off.

**Comment by hunse** [comment]
Do we have a config option for the progress bar? If not, we should. And one for this, too.

**Comment by jgosmann** [comment]
Yes, we have a config option for that. Just put
```ini
[progress]
progress_bar: False
```
in your `~/.config/nengo/nengorc`

**Comment by drasmuss** [comment]
Ah sweet, I didn't realize that was used for more than just decoder caching settings :tada:
