### ISSUE TITLE
Move pretty_spike_raster into Nengo utils

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#939]
Terry has a [nice repository](https://github.com/tcstewar/pretty_spike_raster) for making spike rasters pretty and meaningful, especially when being over-layed with SPA plots. Brent, Ivana, Jan, Su and I all used this for our CogSci papers.

To merge this into Nengo utils, the following things need to be done:
- [ ] The actual useful part of the code (the `add_spikes` function) needs to be extracted
- [ ] Arguments need to be documented
- [ ] A warning about some PDF readers messing up drawing the spikes should be noted
- [ ] Tests need to be written
- [ ] Example usage should be given

**Comment by Seanny123** [comment]
Should this live in this repository or should it be moved to `nengo_extras`? @tbekolay could you provide some guidance for me?

**Comment by hunse** [comment]
For things like this, my general idea is that it will be very common for user utilities of any sort to go straight into Nengo. I think almost all will go to `nengo_extras` at first, and then we can always migrate them over once they're tried and tested, if we so desire.

**Comment by tbekolay** [comment]
> I think almost all will go to nengo_extras at first, and then we can always migrate them over once they're tried and tested, if we so desire.

Seems right to me; we don't have as much process in `nengo_extras` and it's fine to have things in there without tests. We can move them here once they've been used a bit and tested, if we find they're pretty commonly used.

**Comment by Seanny123** [comment]
Resolved in https://github.com/nengo/nengo_extras/pull/39
