### ISSUE TITLE
Allow Connection.transform to accept distribution

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#942]
This will help with learning, where we may want a random initial matrix of a particular distribution for the transform. This was suggested in #639.

**Comment by drasmuss** [comment]
I put together a quick implementation of this for my deep learning stuff in https://github.com/nengo/nengo/commit/7bf9d2c33dac7b191d287f2a5daa30eaaa1086f1.  Not thoroughly tested, but seems to work.

**Comment by drasmuss** [comment]
This is in master now.
