### ISSUE TITLE
How should we deal with advanced indexing?

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#948]
Currently, we sort of support NumPy-style [advanced indexing](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing) of objects in the context of connections. I say sort of because there are currently bugs related to it (#947) and it only shows up a few times in our unit tests (e.g., [here](https://github.com/nengo/nengo/blob/master/nengo/tests/test_connection.py#L369)), so we are likely not testing all cases.

There are a few directions we could go with advanced indexing, so it's worth discussing which one we want to take before implementing things.
1. Support all the advanced indexing cases.
   
   In addition to lists of integers, there's also boolean arrays and a few other weird cases. We'd have to implement tests and make sure they work across different backends. This may be possible to do with minimal changes to backends (possibly through a helper function that gives an equivalent network with only basic indexing). However, it might also require lots of changes for some backends; note that in NumPy, for example, advanced indexing always triggers an array copy, rather than constructing a view.
   
   Pros: Shorter / simpler code for certain use cases; less surprise for those experienced with NumPy.
   
   Cons: More complicated backend code; more things we need to teach users about.
2. Explicitly drop advanced indexing support and require only basic indexing.
   
   There shouldn't be loss in the type of models that one can implement here, just a difference in how those models are written. Connections with advanced indexing can be replaced with one or more connections with basic indexing.
   
   Pros: Simpler frontend and backend Nengo code; simpler for other backends to implement.
   
   Cons: Breaks some existing user scripts; disappointing for experienced NumPy users that want to use advanced indexing.
3. Support advanced indexing, but internally transform to basic indexing equivalents.
   
   This keeps the pros of the above approaches while easing the burdens on backends. This could be done either automatically and silently at the frontend (modifying the model as connections with advanced indices are created), or it could be done explicitly through a utility function that we will instruct backend designers to call in their `Simulator.__init__`.
   
   Pros: Pros of above.
   
   Cons: Magical. May confuse users when the mapping from advanced index to basic indices results in slow simulations (due to many additional connections, for example).

**Comment by hunse** [comment]
4. Support some types of advanced indexing and not others.

Specifically, I'm thinking of extending our support for lists or arrays of indices (i.e. by fixing #947), but not allowing boolean arrays. What are the "few other weird cases" you were referring to, @tbekolay? We could either allow or disallow these as we see fit.

We would throw a clear error for cases we don't support, and have better testing of all cases to ensure functionality for supported cases and errors for unsupported ones.

**Comment by drasmuss** [comment]
I'm definitely on the fence on this one.  On the one hand, on the occasions where I have wanted to use advanced indexing, it's been great to have it.  But probably my more common experience has been working with the backend code, where supporting advanced indexing is kind of a pain (and error prone).

A supplemental 2b) option would be to drop advanced indexing (so just use multiple connections instead), but then add some optimization on the backend where we try to group connections with the same pre/post (which could have benefits beyond this issue).  Not saying that's a better solution, just another option.

**Comment by tbekolay** [comment]
I think the only other case (other than integer lists and boolean arrays) is mixed basic and advanced indices (e.g. `x[1:2, [1, 2]]`). But we may not have to worry about this since we're only dealing with one dimension when we're slicing objects in the context of a connection.

**Comment by tcstewar** [comment]
My vote's for (4) (Support some types of advanced indexing and not others).  In particular, the index can be an integer, a slice, or a list of integers (or an nparray of integers).  I don't think the boolean list indexing is needed.

The list indexing approach is handy, and I haven't found it too bad to support in various backends.  I think the main problem has just been the lack of tests for it.

**Comment by tbekolay** [comment]
We discussed this issue at the dev meeting on Sept 18, 2017. The consensus was to try to fix #947, and if that's relatively easy to fix, then we should essentially fully support advanced indexing (as boolean arrays should not be difficult to get working, if they don't work already).

**Comment by drasmuss** [comment]
We've made various improvements to the handling of advanced indexing since this was made, so I'll close this (and we can create new issues if we discover any specific problems).
