### ISSUE TITLE
odd cache interaction with testing solvers

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo#961]
I'm not entirely sure, but I believe this is from an interaction between the cache and decoder solver.  I was exploring what the effect of regularization was on my network.  However, the `reg` parameter was having no effect, until i changed the ensemble to not specify n_eval_points.  Code example is below (if you run it and change reg, there's no effect.  If you remove the n_eval_points parameter, it works fine):

```
import nengo

T = 5.0
dt = 0.001
seed = 0

n_neurons = 5000
tau_recurrent = 0.005
scale_input = 20
tau_stim = 0.1
tau_probe = 0.005

with nengo.Network("Integrator") as model:
    stim = nengo.Node(output=nengo.processes.WhiteSignal(T))
    my_input = nengo.Node(size_in=1)
    nengo.Connection(stim, my_input, synapse=tau_stim, transform=scale_input)
    
    ens = nengo.Ensemble(n_neurons, dimensions=1, n_eval_points=1000)
    nengo.Connection(my_input, ens, synapse=None, transform=tau_recurrent)
    nengo.Connection(ens, ens, synapse=tau_recurrent,
                    solver = nengo.solvers.LstsqL2(reg=0.00001))   
    
    p_input = nengo.Probe(my_input, synapse=tau_probe)
    p_output = nengo.Probe(ens, synapse=tau_probe)

sim = nengo.Simulator(model, dt=dt, seed=seed)
sim.run(T)

figure()
plot(sim.trange(), sim.data[p_output], label="Actual")
plot(sim.trange(), cumsum(sim.data[p_input])*dt, label="Expected")
legend()
show()
```

**Comment by jgosmann** [comment]
I cannot reproduce the problem.
Also, there is no network seed set and thus only cache misses should occur.

It is possible to get some more information about whether cached decoders are loaded when setting the log level to 'debug' with `nengo.log('debug')`.

**Comment by celiasmith** [comment]
When you say you cannot reproduce the problem, do you mean that if you run that code and change reg, you can see changes in the output? (e.g. make it 0.0000001 and it should fail; if it doesn't fail, remove the n_eval_points bit and run it again and it should fail).

**Comment by jgosmann** [comment]
I see a change when increasing reg to 1 or 10. When removing `n_eval_points` the default will be to use 10000 instead of 1000 eval points. When setting `reg=0.0000001` and `n_eval_points=10000`, I get the same result as with `reg=0.0000001` and removing the `n_eval_points` part. I think using less evaluation points acts as a form of regularization here.

**Comment by celiasmith** [comment]
There is something inexplicably different between n_eval_points = 1000 and 10000.  I read through the solver and the number of eval points shouldn't be causing an issue (because you always do A.T * A), but the cholesky call is failing... so something numerically odd is going on.  Thanks, I'll talk to eric about it.
