### ISSUE TITLE
Add an easy way to clear probe data

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#963]
Sometimes you want to run a simulator several times and take each run as a separate chunk of data to analyze. Currently, that's not straightforward to do because probed data accumulates each time you run the simulator.

The easiest way to do this currently is

``` python
for probe in sim.model.probes:
    del sim._probe_outputs[probe][:]
```

But, clearly that's not a great solution since it requires accessing an underscored attribute. So it would be good to add something to the API to support this (though it will increase the burden on other backends).

This is somewhat related to #888; a more flexible notion of "reset" would fix both issues (e.g., having a `reset_probes`, `reset_synapses`, etc that are all called in the general `reset` method).

**Comment by Edward-CNRG-NTU** [comment]
excuse me, so did this feature implemented yet? or got canceled?

**Comment by tbekolay** [comment]
We haven't added anything to do this specifically yet, no. If you just want to clear probes, the two-line workaround above still works and will until the next major release (3.0). If you want a more flexible resetting system, that work will start in #1189.

**Comment by Seanny123** [comment]
@psipeter this is the issue for the feature that you'd like

**Comment by arvoelke** [comment]
Since time has passed, I think this is the new work-around:
```python
for probe in sim.model.probes:
    sim._probe_outputs[probe] = []
````

**Comment by drasmuss** [comment]
A `Simulator.clear_probes()` method was added in https://github.com/nengo/nengo/pull/1387
