### ISSUE TITLE
Check for unused arguments in test functions

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#965]
In #932, @tbekolay came across some test functions that did not use some of the arguments that were passed to them (most notably `Simulator`, instead opting for the incorrect `nengo.Simulator`). It would be nice to have static checks for this.

I think PyLint can do this, but @tbekolay says it also detects many things we don't care about ATM, so we would have to just pick out the tests we want. We can also add our own [flake8 plugin](http://flake8.readthedocs.org/en/latest/extensions.html) if we want. We could use this plugin to do something like make sure `nengo.Simulator` never appears in any of the tests.

**Comment by jgosmann** [comment]
According to #1278 it is not enabled and at that point I was of the opinion that the `unused-argument` check should stay disabled. I assume it gives a lot of false positives? Maybe it could just be enabled in test files ...

**Comment by drasmuss** [comment]
`unused-argument` is currently disabled on Nengo Bones, but we plan on enabling it (tracked in a separate issue).
