### ISSUE TITLE
Sliced voltage Probes don't work

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#967]
This used to work but does not any more:

```python
import nengo

model = nengo.Network()
with model:
    ens = nengo.Ensemble(100, 1)
    p = nengo.Probe(ens.neurons[:2], 'voltage')
    
sim = nengo.Simulator(model)
with sim:
    sim.run(1)
```

This seems to be broken as of commit 82fa822 and means that Nengo GUI voltage probes do not work with the latest nengo.

**Comment by hunse** [comment]
As a workaround you can do
```python
p = nengo.Probe(ens.neurons[:2], 'voltage', synapse=0)
```

I'll try and see what the problem is.
