### ISSUE TITLE
matplotlib.py not included in utils submodule

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#971]
Wondering if there is a reason we're not including `matplotlib.py` in `nengo/utils/__init__.py`? Maybe something to do with naming conflicts?

**Comment by tbekolay** [comment]
It's because that file imports matplotlib, which is not a requirement of Nengo; we only require that you have NumPy. Same reason we don't import `nengo/ipynb.py`.

**Comment by arvoelke** [comment]
Ah, right. Thanks for the quick reply. Maybe a comment should be made to this effect near the top of these two files? To me it's unintuitive that I can do `from nengo.utils.matplotlib import rasterplot` but I can't do `nengo.utils.matplotlib.rasterplot(...)`.

**Comment by tbekolay** [comment]
Makes sense, will do!

**Comment by shreab373** [comment]
Hello, i'm new to open source, can i take this? could you help too ?
