### ISSUE TITLE
Store operators in a more organized way

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#986]
Currently, in `Model`, we just keep one big list of all the operators. It might help to have these operators more organized, for example for things like optimization.

One option is to store them based on the object that creates them, like we do with signals. This is what I wanted when I was looking into making an optimizer for LIF ensembles, and I think it would work fairly well. It's not quite as clear-cut as with signals, since many operators copy things from signals belonging to one object to signals belonging to another object. But each operator is unambiguously created in some object's builder, so I think it makes sense to assign ownership that way.

Another option would be to group operators by type.

Places where this would be useful (please add any ideas you have):
- optimizers
- Checking to see whether we've already added a PreserveValue for a set of encoders (see [here](https://github.com/nengo/nengo/pull/915/files/4df4cc621f425dbbe1af5feed3c373c80118ae8f#diff-d88c987696c16673f33089794ccd0bbfR223))

**Comment by jgosmann** [comment]
A grouping by type is useful for #1035. Apart from that #1035 is doing its own specific sortings. A grouping based on the creating object is not particularly relevant in that case. But the ownership information could be quite useful for debugging.

**Comment by hunse** [comment]
I'm also thinking ownership information could be useful for rebuilding individual parts of the model (e.g. a node), since then it's easy to remove old operators and replace them with new operators.

**Comment by drasmuss** [comment]
We'll look into this as part of the overall builder refactoring that is planned (which we have separate issues for).
